### ISSUE TITLE
Change editor name

### ISSUE THREAD

**Issue by theArianit** [VSCodium/vscodium#503] opened 2020-09-16 08:04 UTC
I would like to suggest to change the name of vsCodium to just Codium, to remove the vs part.
The vs part (visual studio) doesn't fit for this IDE/Editor, since it has no visualization like visual studio had when they introduced the drag and drop function of tools or whatever the reason was for this kinda dumb name.

**Comment by CountZachula** [comment] 2020-09-16 09:15
@theArianit This is an active topic. Check out #193. 



> ...whatever the reason was for this kinda dumb name.

😒 The "Visual" aspect comes from the ability to perform "visual" point-and-click composing of Windows Forms (the drag and drop utility you mention), interactive debugging, class design, data modeling, and more; i.e. less time coding. Although I agree VSCodium should be renamed to Codium, the "visual" component isn't completely irrelevant.

**Comment by theArianit** [comment] 2020-09-16 11:27
you are right, but today everything is represented visually.

**Comment by stripedpajamas** [comment] 2020-09-18 00:29
duplicate of #193 as @CountZachula mentioned

**Closed by stripedpajamas** 2020-09-18 00:29 UTC
Labels: bug

**Comment by theArianit** [comment] 2020-09-18 04:45
that's even better
