### ISSUE TITLE
File Menu crashes codium on GNU/Linux|arm64 (Raspberry Pi 4, 64-bit)

### ISSUE THREAD

**Issue by JTHartzfeld** [VSCodium/vscodium#2100] opened 2024-11-09 08:14 UTC
**Describe the bug**
When the File menu is accessed, the application crashes.  This is consistent behavior on a Raspberry Pi 4 Model B Rev 1.2 (4-core, 64-bit) running Debian 12 (bookworm) and Mate.

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and my issue is not mentioned there.

**To Reproduce**
(On Raspberry Pi 4, certainly, but possibly other debian-linux/aarch64 platforms.)
1. Open the Application
2. Click on the File menu.
4. See error: (Application crashes completely.)

**Expected behavior**
The File menu should open and operation should continue as normal.

**Screenshots**
N/A (not necessary).

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12 (bookworm)
 - Architecture: aarch64
 - Application Version: 1.95.x
 - Package Manager: apt
 - Sandboxed: no
 - 
**Additional context**
All other functionality seems to be accessible and functional, but accessing the File menu causes it to crash *every* time.  I'm at a loss.

**Comment by daiyam** [comment] 2024-11-09 10:42
Duplicate of #2082

**Closed by daiyam** 2024-11-09 10:42 UTC
Labels: bug
