### ISSUE TITLE
Apple MX architecture Support

### ISSUE THREAD

**Issue by netzeroo** [VSCodium/vscodium#722] opened 2021-05-18 20:44 UTC
Hello, can we get a native VSCodium binaries for the new M1 platform, VSCode has it for a while, but it's VSCode...

**Comment by stripedpajamas** [comment] 2021-05-19 15:25
Duplicate of https://github.com/VSCodium/vscodium/issues/597

**Closed** 2021-05-19 15:25 UTC
Labels: bug
