### ISSUE TITLE
Picked as default to open folder

### ISSUE THREAD

**Issue by sbalmer** [VSCodium/vscodium#409] opened 2020-06-01 20:49 UTC
**Describe the bug**
Codium is launched when I want to open a folder.

**Please confirm that this problem is VSCodium-specific**
I did not have this problem in VS-Code.

**Please confirm that the issue/resolution isn't already documented**
- [:heavy_check_mark: ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Click on "Show in folder" in Firefox Download
2. Codium opens but doesn't show folder contents

The same happens in other contexts where normally a file-manager would open.

**Expected behavior**
A file-manager opens when I click on "Show in folder"

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version 1.45.0 x64

**Cause**

The file `/usr/share/applications/codium.desktop` includes this line:

    MimeType=text/plain;inode/directory;

In `/usr/share/applications/mimeinfo.cache` the codium entry is first:

    inode/directory=codium.desktop;org.gnome.Nautilus.desktop;org.gnome.baobab.desktop;

When I remove `inode/directory=codium.desktop` from that file, a file-manager opens like expected. I understand that in some situations I might want to open a folder in Codium so the option is useful. It's just  that on my system it ended up being the default which was very confusing.

**Comment by stripedpajamas** [comment] 2020-07-29 00:10
Yeah that doesn't sound ideal. How did you install VSCodium?

**Comment by RuhtraX** [comment] 2020-09-25 14:18
I had the same problem.

**Please confirm that this problem is VSCodium-specific**
I haven't tested with VS-Code

**Desktop:**
   - OS: Fedora 32
   - Version 1.49.1 x64

Removing the `inode/directory=codium.desktop` fixed it for me as well.

I installed VSCodium via the rpm package.

**Comment by daiyam** [comment] 2022-01-24 18:16
Hi, the issue seems to be recurring but I'm not able to reproduce it...

First of all, the command `xdg-mime query default inode/directory` will display the default file manager.

In `codium.desktop`, the line `MimeType=text/plain;inode/directory;` is only indicating that the app is able to open directory (it's normal). As that in `/usr/share/applications/mimeinfo.cache`, you can have `inode/directory=codium.desktop,....`.

I do think a process during the install see that the vscodium can handle `inode/directory` and set it as the default file manager when it shouldn't.

**Comment by GannonTdW** [comment] 2022-01-24 19:09
Hi, 
So my OS is Archlinux and I have the same issue with vscodium-bin 1.63.2-2. but not with vscodium 1.63.2-1.

**Desktop:**
- ArchLinux (last update)
- Kernel 5.16.1
- Gnome File 41.2

Note:
- I use [paru](https://github.com/morganamilo/paru), it's a [aur helper](https://wiki.archlinux.org/title/AUR_helpers) like [yay](https://github.com/Jguer/yay), [trizen](https://github.com/trizen/trizen), ...
- `paru -Qkkl ` gives the list of files modified by installing the package

-  vscodium-bin 1.63.2-2. **BUG**
```bash
> $ xdg-mime query default inode/directory
codium.desktop
> $
> $
> $ paru -Qkkl vscodium | grep desktop
vscodium-bin /opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.css
vscodium-bin /opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js
vscodium-bin /opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.nls.js
vscodium-bin /opt/vscodium-bin/vscodium-bin-uri-handler.desktop
vscodium-bin /usr/share/applications/codium-uri-handler.desktop
vscodium-bin /usr/share/applications/codium.desktop
> $
> $
> $ cat /usr/share/applications/codium.desktop
[Desktop Entry]
Name=VSCodium
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/opt/vscodium-bin/bin/codium --no-sandbox --unity-launch %F
Icon=vscodium
Type=Application
StartupNotify=true
StartupWMClass=VSCodium
Categories=Utility;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/opt/vscodium-bin/bin/codium --no-sandbox --new-window %F
Icon=vscodium

```

- vscodium 1.63.2-1 **NO BUG**
```bash
> $ xdg-mime query default inode/directory
org.gnome.Nautilus.desktop
> $
> $
> $ paru -Qkkl vscodium | grep desktop          
vscodium /usr/share/applications/vscodium.desktop
vscodium /usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.css
vscodium /usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js
vscodium /usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.nls.js
> $ cat /usr/share/applications/vscodium.desktop
[Desktop Entry]
Name=VSCodium
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/vscodium/bin/codium --no-sandbox --unity-launch %F
Icon=vscodium
Type=Application
StartupNotify=true
StartupWMClass=VSCodium
Categories=Utility;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/vscodium/bin/codium --no-sandbox --new-window %F
Icon=vscodium

```
So
- `vscodium.desktop` and `codium.desktop` are the same.
- But `xdg-mime query default inode/directory`
  - vscodium: org.gnome.Nautilus.desktop
  - vscodium-bin: codium.desktop

I haven't found out yet who is changing this

**Comment by daiyam** [comment] 2022-01-24 21:39
@GannonTdW Which Arch distro are you using?

**Comment by GannonTdW** [comment] 2022-01-24 21:57
@daiyam

> @GannonTdW Which **Arch distro** are you using?

??
 
Well, Archlinux, installed with my little hands ? :)
Not Manjaro, EndeavourOS or other Arch-based Linux distros :)

```bash
> $ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
> $ uname -a
Linux MyHostname 5.16.1-arch1-1 #1 SMP PREEMPT Sun, 16 Jan 2022 11:39:23 +0000 x86_64 GNU/Linux
```

**Comment by indicozy** [comment] 2022-01-27 21:06
I have found the solution on Arch linux + GNOME + VSCodium installed via Flatpak, but I'm sure it's applicable to other methods of installation. 

First I tried to solve it "the right way":
xdg-open parses files from several files:
- For flatpak it's `/var/lib/flatpak/exports/share/applications/mimeinfo.cache`
- For global it's `/usr/share/applications/mimeinfo.cache`
- For local it's `$HOME/.local/share/applications/mimeinfo.cache`
- For snap, please let me know where it's located!
- 
To configure xgd-open for local user only just add `inode/directory=nautilus.desktop` or any other File Manager you use to `.config/mimeapps.list`.

But it didn't work and I did the other way

### Solution:
For GNOME, just open Nautilus, right click to any folder and open as nautilus. It somehow changes the default `inode/directory` and the problem is now solved. I am not sure how GNOME did that, but that worked.

Hope that it helped!

**Comment by GannonTdW** [comment] 2022-01-29 15:41
@indicozy : thx

diff for the file `/usr/share/applications/mimeinfo.cache`
```bash
> $ diff mimeinfo.cache_NOBUG mimeinfo.cache_BUG
372c372
< inode/directory=org.gnome.Nautilus.desktop;vscodium.desktop;
---
> inode/directory=codium.desktop;org.gnome.Nautilus.desktop;
383c383
< text/plain=libreoffice-writer.desktop;org.gnome.gedit.desktop;vim.desktop;vscodium.desktop;
---
> text/plain=codium.desktop;libreoffice-writer.desktop;org.gnome.gedit.desktop;vim.desktop;
487a488
> x-scheme-handler/vscode=codium-uri-handler.desktop;

```

So as say indicozy, I have remove  `codium.desktop` at the line `inode/directory=codium.desktop;org.gnome.Nautilus.desktop;` and I have no problem.

**Comment by daiyam** [comment] 2022-01-29 16:07
`mimeinfo.cache` indicates applications able to open a file based on its mime-type. Since VSCodium is able to open directories, `inode/directory=codium.desktop` should be ok.
Then I'm not an expert on Linux DE so I'm not sure what's happening here...

**Comment by daiyam** [comment] 2022-01-29 16:09
Have you tried to create the file `~/.local/share/applications/defaults.list` with the following content:
```
[Default Applications]
inode/directory=org.gnome.Nautilus.desktop;
```

**Comment by indicozy** [comment] 2022-01-29 16:17
> Since VSCodium is able to open directories, inode/directory=codium.desktop should be ok.

I'm not expert too, but it should stay there. It's the list of available apps that can open files but they do not set the defaults.

**Comment by indicozy** [comment] 2022-01-29 16:20
> [Default Applications]
> inode/directory=org.gnome.Nautilus.desktop;

I tried it with `thunar.desktop` and it worked! I don't know how GNOME makes defaults, but I hope that it will work for other DEs too.

**Comment by GannonTdW** [comment] 2022-01-29 18:36
>mimeinfo.cache indicates applications able to open a file based on its mime-type. Since VSCodium is able to open directories, inode/directory=codium.desktop should be ok.

Not really, the problem is that `codium.desktop` is put before `org.gnome.Nautilus.desktop`.
So VScodium is the default application to open the folder.

I just took the test, with `inode/directory=org.gnome.Nautilus.desktop;codium.desktop;` (for VSCodium-bin) , no problem 
And inversely with `inode/directory=vscodium.desktop;org.gnome.Nautilus.desktop;` (for VSCodium).

**Comment by GannonTdW** [comment] 2022-01-29 20:06
@daiyam 
Yes with the following content it's work
```
> $ cat /usr/share/applications/mimeinfo.cache | grep de/direc                   
inode/directory=vscodium.desktop;org.gnome.Nautilus.desktop;
> $ cat ~/.local/share/applications/defaults.list
[Default Applications]
inode/directory=org.gnome.Nautilus.desktop;
```

Nautilus is use

**Comment by daiyam** [comment] 2022-01-29 23:03
I've made the PR #983 to add a section in the doc for this issue. Can you check it? Thx

`~/.local/share/applications/defaults.list` has been [deprecated](https://wiki.archlinux.org/title/XDG_MIME_Applications#Nonstandard_association). `~/.config/mimeapps.list` is the correct file...

**Comment by GannonTdW** [comment] 2022-01-30 12:53
@daiyam 
Yes it's work.


```
> $ grep direct /usr/share/applications/mimeinfo.cache      
inode/directory=codium.desktop;org.gnome.Nautilus.desktop;
> $ grep direct ~/.config/mimeapps.list                       
inode/directory=org.gnome.Nautilus.desktop;
```

**Comment by daiyam** [comment] 2022-01-30 13:17
I'm closing the issue since we found out why it's happening and how to fix it. The fix has been added to [DOCS.md](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#file-manager).

**Closed by daiyam** 2022-01-30 13:17 UTC
