### ISSUE TITLE
current ms-python won't install under VSCodium (mstoolsai.jupyter incompatibility)

### ISSUE THREAD

**Issue by mariobrostech** [VSCodium/vscodium#819] opened 2021-09-04 16:14 UTC
**Describe the bug**
The official VSCode Python extension fails to install under VSCodium. Downloading the files from the Marketplace and manually from the GitHub repo shows an identical error about the extension not being compatible with the current version of VSCode. This happens even with older versions being downloaded directly via the GitHub releases page for the extension, which can be found [here](https://github.com/microsoft/vscode-python/releases). 

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install the official ms-python extension from the Marketplace and observe the install failing
OR
1. Download the latest VSIX installer of the ms-python extension from [https://github.com/microsoft/vscode-python/releases](https://github.com/microsoft/vscode-python/releases)
2. Open the Command Palette and run the `Extensions: Install from VSIX...` command
3. Locate the file downloaded from the GitHub repo and attempt to install it
4. Observe the install failing

**Expected behavior**
The extension should install, even if it only works via a manual download

**Screenshots**
![Screenshot 2021-09-04 120108](https://user-images.githubusercontent.com/17557442/132101100-746626f6-5571-4a3e-b553-5dbf22047a59.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, version 20H2
 - Architecture: x64
 - Version 1.59.1

**Additional context**
PS: If you care about Python being supported on VSCodium, please [upvote this issue](https://github.com/microsoft/vscode-python/issues/17173) where a user is petitioning Microsoft to add their Python extension to the Open VSX Repo. Thanks in advance!

**Comment by TechnoDiver** [comment] 2021-09-05 17:38
I came here for the exact same issue. No solution yet, been searching all morning

**Comment by k4sei** [comment] 2021-09-05 18:15
Same here. I wonder if it's because the VS Code is on 1.60, while Codium still is under 1.59.

**Comment by TechnoDiver** [comment] 2021-09-05 18:31
That's possible, I've been looking around for hours and haven't been able to solve anything. I was happy to see this issue was raised here only yesterday and not 4 months ago

**Comment by mariobrostech** [comment] 2021-09-05 18:32
> Same here. I wonder if it's because the VS Code is on 1.60, while is Codium still under 1.59.1

If that were the case, though, why wouldn't the older, manual downloads work (since they were designed for older versions of VSCode)?

**Comment by daiyam** [comment] 2021-09-05 19:01
In `product.json`, there is the property `extensionAllowedProposedApi`. The default one in VSCode repository is missing lots of extensions. We are adding some but we the Python extension might require one or more that we have missed. If somebody can test, it would be great ;)

**Comment by k4sei** [comment] 2021-09-05 19:51
> > Same here. I wonder if it's because the VS Code is on 1.60, while is Codium still under 1.59.1
> 
> If that were the case, though, why wouldn't the older, manual downloads work (since they were designed for older versions of VSCode)?

yeah man, I dunno, but will upvote the issue you pointed.

**Comment by k4sei** [comment] 2021-09-05 20:07
In the meantime, I managed to make it work. Keep in mind that this is by no means a long term solution. But, if someone needs this to be working exactly right now (like me), it may be a temporary solution.
[Here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace), there's a way to use the actual VS Code marketplace, instead of open-vsx. You just need to make a "new" product.json in a specific folder (depends on your OS).

Some considerations:
1. [Here](https://github.com/microsoft/vscode/issues/31168), there's a discussion if it's illegal or not. I personally "don't think" it is. But, again, it's just until this situation is resolved.
2. I dunno how it will work in windows (I use "linux"), but I downloaded an AppImage, so it won't mess with my "original".
3. With the VSCode market place in my Codium, everything seems to be working just fine.
4. During the week I will try to look better at this.

**Comment by mariobrostech** [comment] 2021-09-05 20:34
This seems like it was a recent change because one of my other machines has the newest version of Codium on it with a slightly older version of the Python extension, downloaded via the default VSCodium Extensions marketplace. And, for what it's worth, that older extension seems to be working perfectly fine (but trying to update it still shows the same error pictured in my original issue). Would it help to have a copy of that `.vscodium` folder with the extension installed for troubleshooting?

**Comment by daiyam** [comment] 2021-09-05 21:32
@k4sei There is a way to use VS Code marketplace in VSCodium: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace
But it seems the issue is, as I expected, in the `product.json`...

**Comment by amadejpapez** [comment] 2021-09-05 21:48
> But it seems the issue is, as I expected, in the `product.json`...

I think this line is causing the error:
`"serviceUrl": "https://open-vsx.org/vscode/gallery",`
The URL does not seem to work and if I remove this line, installing Python extension seems to work normally. I hope this helps @daiyam :)

**Comment by daiyam** [comment] 2021-09-05 21:57
Ya, it's weird! Just switching to Visual Studio Marketplace is fixing the issue. So I guess I was wrong...

**Comment by TechnoDiver** [comment] 2021-09-06 12:50
where are you folks finding product.json?

**Comment by daiyam** [comment] 2021-09-06 12:52
@TechnoDiver follow https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace

**Comment by TechnoDiver** [comment] 2021-09-06 12:56
daiyam, thanks, I'm doing that as we type

**Comment by GitMensch** [comment] 2021-09-06 13:02
Work-around without any adjustments: use "install another version" and choose "2020.10.332292344", which works fine.

**Comment by daiyam** [comment] 2021-09-06 13:09
The issue seems to be fixed in the futur `VSCodium v1.60`

**Comment by GitMensch** [comment] 2021-09-06 13:12
In this case: duplicate of #818.

**Comment by GitMensch** [comment] 2021-09-07 20:33
So I've installed the 1.60 update - and the issue with the current python extension not installing is still there.
Guess it is reasonable to report that there in any case.

**Comment by GitMensch** [comment] 2021-09-07 20:39
Looks like a known bug, seems to only work on "insiders" currently: https://github.com/microsoft/vscode-python/issues/17296

**Comment by daiyam** [comment] 2021-09-08 18:07
Weird, I don't have the issue from either my macOS, Windows or Linux...

**Comment by pascalpuffke** [comment] 2021-09-08 18:21
> Weird, I don't have the issue from either my macOS, Windows or Linux...

I just updated to Codium 1.60, still doesn't install for me from marketplace (macOS, can try Win and Linux if it helps)

**Comment by k4sei** [comment] 2021-09-08 18:29
> Weird, I don't have the issue from either my macOS, Windows or Linux...

A really silly question, but you are sure you're using the open-vsx, right?

**Comment by daiyam** [comment] 2021-09-08 18:45
The issue was about installing the newest .vsix directly. It was what I've tested.
But, yeah, the version from OpenVSX isn't installing...

**Comment by p-inks** [comment] 2021-09-12 13:28
![Screenshot_20210912_221345](https://user-images.githubusercontent.com/29687306/132989104-2e63cde5-1269-4378-8d1b-e7e9cc179ab9.png)

I faced same problem yesterday, and it seems solved for me now. (I use open-vsx)
But I'm sorry,  I don't know why this problem was solved. 
I didn't do anything (as far as I can tell)

**Comment by daiyam** [comment] 2021-09-12 14:49
Yep, it's working. I did remember a network error.

**Comment by mariobrostech** [comment] 2021-09-13 04:45
Python is installing once again for me as well, so something must've been patched up server-side!

On a slightly unrelated note, I've found that Python in VSCodium won't properly handle turtle commands, while everything works out-of-the-box with Microsoft's Visual Studio Code. Please let me know if I should open a separate issue for this or if I should go and make an issue directly on the Python repo, but this also looks like a VSCodium-specific issue to me.

**Comment by GitMensch** [comment] 2021-09-13 05:57
Please remember that the default installation of the python plugin in VSCode is not free [since May 2021](https://devblogs.microsoft.com/python/python-in-visual-studio-code-may-2021-release/) any more, as it automatically installs and uses Pylace, an extension that MS explicit told will not be available under a free license. The "good" thing here: if the Pylace extension is not available (disabled or cannot be auto-installed like in the case of Open-VSX as extension provider) then the free language support is still activated.
I _guess_ that MS will not put very much efforts to improve the free language support in the future, but one could still try to PR missing features (I hope that they don't deprecate that too soon).

So in the comparison of VSCode + Python against any build of vscode + Python: please always deactivate the Pylace extension in VSCode and restart it, then compare.
@mariobrostech If you do this, are the turtle commands still "properly handled" in VSCode? If yes: please create a new issue with the details.

I'm closing this one as the installation now works.

**Closed by GitMensch** 2021-09-13 05:57 UTC
Labels: bug

**Comment by daiyam** [comment] 2021-09-13 07:16
@GitMensch I've added the fact you pointed out to the [wiki compatibility page](https://github.com/VSCodium/vscodium/wiki/Extensions-Compatibility).
