### ISSUE TITLE
Memory leak and CPU ramp up on Arch Linux after latest update

### ISSUE THREAD

**Issue by cristianovitorino** [VSCodium/vscodium#408] opened 2020-05-24 17:24 UTC
**Describe the bug**
VSCodium is leaking memory and ramping up CPU usage on Arch Linux. This started after the latest updates. Tested on version 1.44.2 and later.

**Please confirm that this problem is VSCodium-specific**
- [X ] No, it happens also with _Code OSS_ and _Visual Studio Code_.

**Please confirm that the issue/resolution isn't already documented**
- [ X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Update your Arch Linux with `sudo pacman -Syu --noconfirm`.
2. Either install VSCodium from AUR, in my case, I use _Aura_ `sudo aura -Ax vscodium-bin`, or install the latest (v1.44.2 or later) AppImage from the _Releases_ page.
2. Install some extensions.
3. Open VSCodium and work on it about 5 to 10 minutes.
4. Use some reliable _System Monitor_ software. Stacer and Polybar modules was used to track this issue.
5. Memory should drain and CPU usage should ramp up.
6. I observed 6 to 8 GBs of usage by VSCodium alone. On the attached screenshot about 6 GBs is observed.
7. I have 37 extensions installed.

**Expected behavior**
Memory shouldn't leak and CPU shouldn't ramp up with VSCodium usage. It was not like this before, this happened after the latest updates.

This behavior **doesn't happen** with version 1.42.0

**Screenshots**
Click for full view.

![dfjk265](https://user-images.githubusercontent.com/57003922/82760340-3b791600-9dc9-11ea-8dbb-4a53b928d25f.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Architecture: x86_64
 - Version: Rolling Release Model
- Kernel: Linux 5.6.14-arch1-1 

**Additional context**
#### PKGBUILD
```
# Maintainer: Plague-doctor <plague <at>> privacyrequired <<dot>> com >
# Contributor: me at oguzkaganeren dot com dot tr
# Contributor: Rowisi < nomail <at> private <dot> com >

pkgname=vscodium-bin
pkgver=1.45.1
pkgrel=1
pkgdesc="Binary releases of VS Code without MS branding/telemetry/licensing."
arch=('x86_64' 'aarch64' 'armv7h')
url="https://github.com/VSCodium/vscodium"
license=('MIT')
depends=(
        fontconfig libxtst gtk3 python cairo alsa-lib nss gcc-libs libnotify libxss
        'glibc>=2.28-4'
        )
optdepends=(
        'gvfs: For move to trash functionality'
        'libdbusmenu-glib: For KDE global menu'
)
provides=('code')
conflicts=('code')

sha256sums_x86_64=('b7535c73bf6881919a5e4f0ff6b5f45bb1195f764dbdece1724ebcf7502b26d5')
sha256sums_aarch64=('0f67273a3b862afbc2917bfd0c87f7b5e52c06e94f2612fefa520e8d148cb619')
sha256sums_armv7h=('9bc2e842ec99b728377a7fb92725131fd9ebe918caa7948237337854643d5a36')

source=(vscodium-bin.desktop)
sha256sums=('5504e93bd55f2bc068c29e4fa962c1eddc6e08edb39c3255319dd5ad998a1b86')
source_x86_64=("${pkgname}-${pkgver}-${pkgrel}-x64.tar.gz::${url}/releases/download/${pkgver}/VSCodium-linux-x64-${pkgver}.tar.gz")
source_aarch64=("${pkgname}-${pkgver}-${pkgrel}-arm64.tar.gz::${url}/releases/download/${pkgver}/VSCodium-linux-arm64-${pkgver}.tar.gz")
source_armv7h=("${pkgname}-${pkgver}-${pkgrel}-arm.tar.gz::${url}/releases/download/${pkgver}/VSCodium-linux-arm-${pkgver}.tar.gz")

case ${CARCH} in
    x86_64) _arch=x64 ;;
    aarch64) _arch=arm64 ;;
    armv7h) _arch=arm ;;
    *) _arch=unknown ;;
esac

noextract=("${pkgname}-${pkgver}-${pkgrel}-${_arch}.tar.gz")

prepare() {
    mkdir -p ${srcdir}/${pkgname}
    tar -xf ${srcdir}/${pkgname}-${pkgver}-${pkgrel}-${_arch}.tar.gz -C ${srcdir}/${pkgname}
}

package() {
    install -d -m755 ${pkgdir}/usr/bin
    install -d -m755 ${pkgdir}/usr/share/{${pkgname},applications,pixmaps}
    cp -r ${srcdir}/${pkgname} ${pkgdir}/usr/share
    ln -s /usr/share/${pkgname}/bin/codium ${pkgdir}/usr/bin/code
    ln -s /usr/share/${pkgname}/bin/codium ${pkgdir}/usr/bin/codium
    ln -s /usr/share/${pkgname}/bin/codium ${pkgdir}/usr/bin/vscodium
    install -D -m644 vscodium-bin.desktop ${pkgdir}/usr/share/applications/${pkgname}.desktop
    install -D -m644 ${srcdir}/${pkgname}/resources/app/resources/linux/code.png \
            ${pkgdir}/usr/share/pixmaps/vscodium.png
}
```

#### System information
![asgfr745](https://user-images.githubusercontent.com/57003922/82760412-be01d580-9dc9-11ea-8272-09bd0b7e06d6.png)

**Comment by stripedpajamas** [comment] 2020-05-29 15:56
Hi @cristianovitorino :D

> No, it happens also with Code OSS and Visual Studio Code.

This means the issue is out of scope for VSCodium -- remember that we are only building + packaging the code that MS has produced in the vscode repository. So if an issue is present in both VSCodium and Visual Studio Code, it's an indication that the problem isn't in our build process. I recommend opening an issue directly in vscode's issue tracker. 

(I've also noticed a CPU ramp up in latest release, perhaps others have already told MS).

**Closed by stripedpajamas** 2020-05-29 15:56 UTC
Labels: bug

**Comment by cristianovitorino** [comment] 2020-05-30 05:03
I see. Thanks for the explanation. I'll see if there is a bug report up already, if not, I'll open one.

 I'll stay on **1.42.0** until this is solved in upstream.
