### ISSUE TITLE
Sign in with Github?

### ISSUE THREAD

**Issue by DestroyerXyz** [VSCodium/vscodium#593] opened 2020-12-21 14:51 UTC
Can you sign in with GitHub to carry over your settings from VSCode?

**Comment by MusheAbdulHakim** [comment] 2020-12-24 09:48
Yes Ofcourse you can sign in with github in vscodium.

1. Make sure the git extension is enabled.
2. Click on the opensource icon at the left side panel.
3. If you have a project opened, you would be asked to publish to github or initialize a repository.Choose the one you want to do.
4. After that, you would be asked to sign in to github but when it prompts you to open the browser, don't accept.
5. After you cancel the prompt to open in the browser, you would be asked to enter your github username .Enter and press enter, then your password too. and you are signed in to github.


After this, you can now publish and initialize projects to github.

**Comment by DestroyerXyz** [comment] 2020-12-24 18:55
No, I meant the sign in to VSCode which is used to sync settings and extensions

**Comment by yadavgulshan** [comment] 2020-12-25 07:02
Facing the same issue... after clicking profile icon, its saying "loading" but nothing seems to be happening.

**Comment by MusheAbdulHakim** [comment] 2020-12-25 09:08
Okay i haven't try that yet.

**Comment by daiyam** [comment] 2020-12-29 00:07
There is a workaround at https://github.com/VSCodium/vscodium/issues/401#issuecomment-631502370

**Comment by GitMensch** [comment] 2021-01-14 15:18
Isn't this a duplicate of #401?

**Comment by Micronetic** [comment] 2021-02-02 14:28
So you install vscodium to escape the botnet and then you're trying to connect to github aka Microsoft? lol

**Comment by DestroyerXyz** [comment] 2021-02-02 14:49
Well you are commenting on an issue on a repo on GitHub and you clearly have a GitHub account so....? lol?

**Comment by hazarek** [comment] 2021-02-02 16:18
I recommend this extension. your settings are saved in the secret Gist. You know where settings is. https://github.com/shanalikhan/code-settings-sync

**Comment by Micronetic** [comment] 2021-02-02 16:29
> Well you are commenting on an issue on a repo on GitHub and you clearly have a GitHub account so....? lol?

I don't use vscodium anymore.

**Comment by hazarek** [comment] 2021-02-02 17:49
> > Well you are commenting on an issue on a repo on GitHub and you clearly have a GitHub account so....? lol?
> 
> I don't use vscodium anymore.

then why are you watching vscodium issues.

**Comment by MusheAbdulHakim** [comment] 2021-02-02 18:46
You guys are funny.Remember this is for issues not memes.  lol

**Comment by hazarek** [comment] 2021-02-02 19:40
> You guys are funny.Remember this is for issues not memes. lol

this issue is already a duplicate. a little chat is good.

**Comment by stripedpajamas** [comment] 2021-02-02 19:59
Closing in favor of #401

**Closed by stripedpajamas** 2021-02-02 19:59 UTC

**Comment by GiDevEon** [comment] 2022-03-27 11:28
401 didn't work for me.
