### ISSUE TITLE
Why include built-in extensions?

### ISSUE THREAD

**Issue by playgithub** [VSCodium/vscodium#449] opened 2020-07-15 01:05 UTC
I think it's better for user to choose freely.
By disabling some built-in extention and install another is not simple enough.
If the reason is easy to use by default, I don't think so, it's better to suppose the user should be professional, and vscodium should be professional, proper professional = simple and powerful.

**Comment by spoenemann** [comment] 2020-07-16 09:53
Duplicate of #423?

**Closed** 2020-07-16 11:25 UTC
