### ISSUE TITLE
Unable to connect to extension marketplace on 1.58.0

### ISSUE THREAD

**Issue by pmahend1** [VSCodium/vscodium#762] opened 2021-07-13 00:37 UTC
Recent update has broken extension marketplace connectivity.

![image](https://user-images.githubusercontent.com/21352870/125371734-63219980-e34f-11eb-913a-fd458aea0103.png)

Also on **Getting Started** it says **VS Code** while it should say **VSCodium**

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Update VS codium to latest
2. Go to extension
3. Search for any extension

**Expected behavior**
- Should be able to connect to open-vsx.org extension marketplace
- VS Code should be refactored to VSCodium on welcome screen.

**Desktop (please complete the following information):**
 - OS: Windows and Mac, should be same on Linux if I am not wrong.
 - Architecture [e.g. x64, ia32, arm64] - NA
 - Version [e.g. 1.33.0] : 1.58.0
[vscodium_1580.log](https://github.com/VSCodium/vscodium/files/6805117/vscodium_1580.log)

**Additional context**
Log attached.

**Comment by daiyam** [comment] 2021-07-13 06:57
Hi, it's a duplicate of #746.

**Closed by daiyam** 2021-07-13 06:57 UTC
Labels: bug

**Comment by pmahend1** [comment] 2021-07-16 00:42
Sorry. Not sure why I couldn't get that in search result or I dint see it.
