### ISSUE TITLE
`build-version.patch` is not sync with language pack translations

### ISSUE THREAD

**Issue by Crystal-RainSlide** [VSCodium/vscodium#1301] opened 2022-10-24 10:59 UTC
**Describe the bug**

With the addition of `"Release:"`, there are 9 lines for English, but only 8 lines & value got shifted after `"Version:"` for non-English. 

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**

1. Open VSCodium
2. Click on Help - About
3. Change display language from / to English
4. Click on Help - About

**Expected behavior**

Honestly, I don't know...
- Should we hide the Release version?
- Should we merge the Release version into "Version:"?
- Should we patch the language packs instead?

**Screenshots**

English | Simplified Chinese
------- | ------------------
![About Dialog in English](https://user-images.githubusercontent.com/16851802/197509930-206b0085-69ab-4b6f-8fb9-9d50ecc69f69.png) | ![About Dialog in Simplified Chinese](https://user-images.githubusercontent.com/16851802/197510210-b64f448a-04e0-4b47-b86c-1efa4de4fd07.png)

**Desktop (please complete the following information):**
 - OS: All
 - Architecture: All
 - Version: Most of the recent versions
 - App Manager: Not related

**Additional context**

https://github.com/VSCodium/vscodium/blob/10582b3c86c800f43dbe7836203420dde9862c60/patches/build-version.patch#L145

**Comment by daiyam** [comment] 2022-10-24 11:59
duplicate of #1281

**Closed by daiyam** 2022-10-24 11:59 UTC
Labels: bug
