### ISSUE TITLE
Debian Certificate verification failed

### ISSUE THREAD

**Issue by chris122380** [VSCodium/vscodium#1645] opened 2023-09-17 16:38 UTC
**Describe the bug**
Certificate verification failed when updating the repository.

**Please confirm that this problem is VSCodium-specific**
Specific to the VSCodium repository 

**Please confirm that the issue/resolution isn't already documented**
Not in documentation and didn't find under issues. 

**To Reproduce**
Just add the VSCodium repo for Debian as outlined at https://vscodium.com/

**Expected behavior**
Expect no errors when running sudo apt update 

**Screenshots**
```
W: Failed to fetch https://download.vscodium.com/debs/dists/vscodium/InRelease  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 2400:52e0:1a01::985:1 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Desktop (please complete the following information):**
 - OS: Debian Testing 
 - Architecture: x64
 - Version: 1.82.2
 - App Manager: apt
 - Sandboxed: no

**Comment by QuickMythril** [comment] 2023-09-17 17:00
duplicate of:
https://github.com/VSCodium/vscodium/issues/1643

**Closed** 2023-09-17 20:51 UTC
Labels: bug
