### ISSUE TITLE
Monokai Pro not appearing on the extension install list.

### ISSUE THREAD

**Issue by Ceebox** [VSCodium/vscodium#422] opened 2020-06-15 13:25 UTC
**Describe the bug**
I just installed VSCodium on manjaro from flatpak, and most of the extensions I ususally use (including Monokai Pro, the extension I really want to install) are not there.

**Please confirm that this problem is VSCodium-specific**
- I use these extensions in VSCode all the time, so no clue why they are not appearing.

**To Reproduce**
1. Go to extensions, and try to type monokai pro
2. It won't be there

**Expected behavior**
It to be on the extension list.

**Desktop (please complete the following information):**
 - OS: Manjaro Rolling Release
 - Intel x64
 - Latest Version on flatpak

**Comment by ThinkTwiceCodeOnce-prog** [comment] 2020-06-15 14:58
This is not a bug, see #421 for more information.
The last update to version 1.46.0 replaced the Microsoft market place for VSCode extensions by the more privacy-oriented open-source one [open-vsx.org](open-vsx.org). Because it is open-source and just started as a project not all extensions are already available or some (owned by Microsoft) are not expected to appear there due to licencing.
Read more e.g. how to change back to MS Market Place in the [docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md).

**Comment by stripedpajamas** [comment] 2020-06-25 16:23
@Mazwak changing the vscode's UI during the build process is out of scope for this project. We are very limited to changing values of the `product.json` file. 

I will pin an issue to this repo regarding what to do about missing extensions so that hopefully people can find the help they need quicker.

**Closed by stripedpajamas** 2020-06-25 16:23 UTC
Labels: bug
