### ISSUE TITLE
VSCodium update file infected with trojan

### ISSUE THREAD

**Issue by roslamir** [VSCodium/vscodium#704] opened 2021-04-15 01:44 UTC
When updating my copy of VSCodium (not VSCode) I got this "Threat Quarantined" notification from Windows Defender. Attached is the screenshot of the notification.
![antivirus-1](https://user-images.githubusercontent.com/1100516/114801842-1d484a00-9dcf-11eb-9286-83fa2e10086a.png)

**Comment by daiyam** [comment] 2021-04-15 01:47
Closing as duplicate of #699

**Closed by daiyam** 2021-04-15 01:47 UTC
