### ISSUE TITLE
Replace default icon with vscodium one

### ISSUE THREAD

**Issue by Aviortheking** [VSCodium/vscodium#156] opened 2019-05-14 13:00 UTC
![image](https://user-images.githubusercontent.com/15822031/57699790-d092ec00-7658-11e9-8b43-74a69ef702ac.png)
Icon on the top left and in the middle of the screen are the base one I think

it could be better to change them with VSCodium logo

**Comment by lsmoura** [comment] 2019-05-14 14:25
Duplicate of #104

**Comment by Aviortheking** [comment] 2019-05-14 14:27
not exactly one for the icon in the center of the screen

**Comment by lsmoura** [comment] 2019-05-14 14:36
@Aviortheking Oh! I see...

The middle icon you're talking about is located on `<vscode_root>/src/vs/workbench/browser/parts/editor/media/letterpress-dark.svg`. There's also other versions on the same folder.

We'd need to change those to the vscodium icon. Maybe @stripedpajamas has a SVG version of the icon that he could share so someone can create the replacements for this view?

**Comment by stripedpajamas** [comment] 2019-05-14 14:58
All the icon files are linked in this comment https://github.com/VSCodium/vscodium/issues/4#issuecomment-427070331

**Comment by stripedpajamas** [comment] 2019-05-29 00:35
Created these letterpress svgs loosely based off the existing (normal, dark, high contrast)

[letterpress_codium_svgs.zip](https://github.com/VSCodium/vscodium/files/3230240/letterpress_codium_svgs.zip)

Will open a PR to use them

**Closed** 2019-05-29 15:37 UTC
