### ISSUE TITLE
bash processes lingering after VSCodium is closed

### ISSUE THREAD

**Issue by sid-the-sloth** [VSCodium/vscodium#1474] opened 2023-04-12 01:02 UTC
**Describe the bug**
Running VSCodium appimage.
Operating system: Debian 11.6 bullseye
After closing VSCodium there are many lingering bash processes.

**Please confirm that this problem is VSCodium-specific**
- How can I confirm if it doesn't occur in VSCode??? I won't install VSCode for that...

**To Reproduce**
1. Run VSCodium, then close it.
2. Check processes in Task Manager
3. There are MANY (20-40) lines similar to this:

```
bash --init-file /tmp/.mount_codium8gWDuH/usr/share/codium/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellintegration-bash.sh
```

**Expected behavior**
When VSCodium is closed, I expect no lingering processes in memory.

**Desktop (please complete the following information):**
OS: Debian 11.6 bullseye
Architecture - 64bit
Version: 1.77.1
Release: 23095
Commit: 8311b9c0ddd6ed7738146332e5a0629c76f17be3
Date: 2023-04-05T18:20:42.031Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.10.0-21-amd64
Sandboxed: No

**Comment by punpun0** [comment] 2023-04-14 08:56
I can confirm the issue on Fedora 37 using the codium RPM package. It also prevents my computer from shutting down and waits for a minute until it kills the processes. Issue is duplicate of #1407 I think. Seems like this issue has been here for a few months now.

**Comment by daiyam** [comment] 2023-04-14 10:16
Yes, same issue. I will close the current one in favor #1407. I will also post an update there.

**Closed by daiyam** 2023-04-14 10:16 UTC
Labels: bug
