### ISSUE TITLE
open folder bad symbols on manjaro kde

### ISSUE THREAD

**Issue by cryptoEcho** [VSCodium/vscodium#984] opened 2022-01-30 11:04 UTC
Hello everyone.
I just installed fresh VSCodium from snap store.
The issue on the picture
![vscodium folders](https://user-images.githubusercontent.com/65803140/151696913-b3b7762d-c4fd-4ac8-a891-ec3153484db6.png)
.
ms's vscode doesn't have this problem.

Any ideas? I would be greatful.

**Comment by bopaquin** [comment] 2022-01-31 05:23
I get the same thing on Fedora with gnome.
It happens on all prompts (Open file/folder, Help > About, Save as, the confirmation prompt when you close an unsaved file, etc.)

**Comment by daiyam** [comment] 2022-01-31 06:17
The issue is a duplicate of #426. See my comment there.

**Closed by daiyam** 2022-01-31 06:17 UTC
