### ISSUE TITLE
 Oh no! An error occurred!  Please restart the sign in process from the editor.  Forbidden(Parrot Os)

### ISSUE THREAD

**Issue by MusheAbdulHakim** [VSCodium/vscodium#534] opened 2020-10-13 00:34 UTC
**Describe the bug**

**Please confirm that this problem is VSCodium-specific**
- [Yes ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ Yes] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to 'Any folder and open it in vscodium'
2. Click on 'the version control icon '
3. Scroll down to 'publish to github ,Allow to open in the browser or even just add the url to trusted urls and open in the browser'

**Expected behavior**
I wanted to authenticate my github account with vscodium so that I can publish and initialise repositories from my github account

**Screenshots**
![Screenshot at 2020-10-12 20-33-35](https://user-images.githubusercontent.com/58814410/95802036-d8423e80-0ceb-11eb-95fb-96073a802ccb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS, Ubuntu 16.04, etc]
 - Architecture [e.g. x64, ia32, arm64]
 - Version [e.g. 1.33.0]

**Additional context**
'
Oh no! An error occurred!
Please restart the sign in process from the editor.
Forbidden
'This is the error am getting in the browser.Any help or explanation would be appriciated.

**Comment by quyvsquy** [comment] 2020-10-17 16:31
same issue

**Comment by adejonghm** [comment] 2020-11-20 14:32
Same issue
OS: Ubuntu 18.04.5 x64
Linux-kernel: 5.4.0-53-generic
VSCodium: 1.51.1

**Comment by MusheAbdulHakim** [comment] 2020-11-22 01:15
There has been no solution to this problem.But the trick i use is when it comes for you to open the link, click on no then it would ask you to enter your github username in the editor after you enter that, press enter and a prompt for password too would come.

**Comment by MusheAbdulHakim** [comment] 2020-11-22 01:16
you could also use this command for the latest version **sudo apt update && sudo apt install vscodium
**

**Comment by adejonghm** [comment] 2020-11-23 15:28
Thanks for the information, I will test it and send feedback.

**Comment by ulyssi** [comment] 2020-11-28 13:32
You have to use this process [https://github.com/microsoft/vscode-pull-request-github/issues/1778#issuecomment-625986692](url)

**Comment by chrise86** [comment] 2020-12-23 22:12
The linked issue seems to have been removed. What's the solution here? I'm seeing the same thing on Big Sur using VSCodium `1.52.1`.

**Comment by MusheAbdulHakim** [comment] 2020-12-24 09:56
Yes his link is broken.
But if you are having the same issue, you can solve it by not signing in with the browser.
Sign in using vscodium.
When it prompt you to open in the browser, click on cancel and then a prompt box would appear asking you to enter github username.Enter it and press enter then enter the password too and you are good to go.

**Comment by paleboot** [comment] 2021-01-05 07:47
Confirmed issue still persists.

OS: Ubuntu 18.04.5 x64
Linux-kernel: 5.4.0-53-generic
VSCodium: 1.51.1

**Comment by sks72589** [comment] 2021-01-11 02:09
> Sign in using vscodium.
> When it prompts you to open in the browser, click on cancel, and then a prompt box would appear asking you to enter GitHub username. Enter it and press enters then enter the password too and you are good to go.

This Issue still remains the same. 
OS: Parrot OS
Architecture: x86_64

**Comment by madeddy** [comment] 2021-01-30 18:55
I'd say its a duplicate of #401

**Comment by GitGangGuy** [comment] 2021-03-08 21:47
> There has been no solution to this problem.But the trick i use is when it comes for you to open the link, click on no then it would ask you to enter your github username in the editor after you enter that, press enter and a prompt for password too would come.

Yes that does work, but I have to do it every single time I push (plus I have to recopy+paste my GitHub PAT since I use 2FA) - it becomes a minor annoyance after a while. Would be cool if maintainers could look into it!

**Comment by suugaarglaass** [comment] 2021-04-01 20:00
> This Issue still remains the same.
> OS: Parrot OS
> Architecture: x86_64

Made it work on a fresh debian install in a VM, Ubutnu, and Kali. ParrotOS has the issue, regardless of update of all packages or not. Seems like an issue might be occurring in ParrotOS. If anyone would be willing to try the workaround and share logs of something like Wireshark running so we could look at what is being sent, that might be able to help? This is frustrating as all hell.

**Comment by Duter2016** [comment] 2021-04-20 07:52
You just need a new github token for vscodium. I tried and succeed.

**Comment by Perpetuous** [comment] 2021-04-29 11:41
Confirmed that this issue still persists. Clicking "cancel" also doesn't work for me like it has for some people, no popup window appears after declining.

OS: windows 10 x86 build 19041.928

**Comment by GitGangGuy** [comment] 2021-04-29 17:18
Not sure what I did over the past weeks, but some workaround suggested somewhere made everything work a while ago.

**Comment by maxime50** [comment] 2021-05-31 06:40
Same issue here... The workaround for me is to press cancel and manually sign in with VSCodium everytime but this is very annoying.

For somebody that doesn't see the login box after pressing cancel, you should be able to see this button on the bottom bar to manually trigger the login prompt, if that can help..

![image](https://user-images.githubusercontent.com/51096534/120150093-9dc4dd80-c1b8-11eb-9877-a348ccc1f228.png)

**Comment by AlexLondonK** [comment] 2021-06-11 15:36
I've had the same issue on Windows 10 using Microsoft Edge. I've solved it by installing Google Chrome and setting it as default browser, everything work the moment I tried to authenticate with chrome. I really did give a chance to Microsoft Edge....

**Comment by ngdangtu-vn** [comment] 2021-06-16 05:35
> I've had the same issue on Windows 10 using Microsoft Edge. I've solved it by installing Google Chrome and setting it as default browser, everything worked the moment I tried to authenticate with chrome. I really did give a chance to Microsoft Edge....

Not in my case, I'm using Chrome right now and it doesn't work :'(

**Comment by HohShenYien** [comment] 2021-06-23 11:24
For those who are facing this issue, the simple way to solve it is by clicking "signing in Github" on bottom left and create a token from [https://github.com/settings/tokens](https://github.com/settings/tokens) and paste it into the box that appears on top. 

Using this method, you don't have to click authenticate everytime you want git push

**Comment by thewiru** [comment] 2021-06-24 22:13
You need to use a chromium-based browser (e.g. Google Chrome, Brave, Opera, Edge, etc) and change the URL from `?callbackUri=vscodium` to `?callbackUri=vscode`.

**Comment by creativetim** [comment] 2021-06-28 19:28
> You need to use a chromium-based browser (e.g. Google Chrome, Brave, Opera, Edge, etc) and change the URL from `?callbackUri=vscodium` to `?callbackUri=vscode`.

This worked for me! I had to manually copy the token back in VSCodium, but that was a small price to pay to have GitLens signed into my GH account.

Thank you, @thewiru!!

**Comment by kiprasmel** [comment] 2021-07-08 20:53
fyi I had some issues with the keychain on linux - see the docs for troubleshooting:

https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues

and also a pending PR for an additional case: https://github.com/microsoft/vscode-docs/pull/4666/files

**Comment by Masutier** [comment] 2021-07-12 13:55
I have VSCodium 1.58.0 & Git 2.25.1 on Ubuntu 20.04
and I have the same issue, I try the push in the Ubuntu Terminal and ask for a pull action wish I did it, then I perform the push and work very well, but in the system terminal... in the VSCodium Terminal did't work

**Comment by cybertcode** [comment] 2021-07-25 19:35
**gente aquí la solución**
https://www.mclibre.org/consultar/informatica/lecciones/vsc-git-repositorio.html

**Comment by godalming123** [comment] 2021-08-08 18:40
same issue OS: fedora could be related to the fact I'm running from app image as packaging format. Also - possibly related - I cannot access the extension marketplace but that could be because I also use a separate folder for home and config directory EG: vscodium.appimage.home + vscodium.appimage.config

**Comment by zakaria-chahboun** [comment] 2021-08-14 10:13
Confirmed issue still persists.

OS: Pop!_OS 21.04
Architecture: x86_64
Version: 1.59.0

**Comment by remilia-grimm** [comment] 2021-08-16 23:23
Same issue,
OS X 11.4
Apple M1 Air

**Comment by Boatengbismark** [comment] 2021-08-24 11:48
Same issue
Os: parrot os
Architecture : x86
Version : 1.59

**Comment by mvargas33** [comment] 2021-09-13 12:26
Same issue
Os: Xubuntu 20.04 LTS
Architecture: x86_64
VSCodium version: 1.56

**Closed** 2022-06-17 14:16 UTC
Labels: bug
