### ISSUE TITLE
Missing `GLIBCXX_3.4.22` 

### ISSUE THREAD

**Issue by rhizene** [VSCodium/vscodium#761] opened 2021-07-12 03:16 UTC
**Describe the bug**
After downloading Codium, I cant proceed after welcome  screen.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Follow the Debian / Ubuntu (deb package) installation instruction
2. Run Codium
3. Window appears but not responsive

**Expected behavior**
Codium installed successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Architecture: x64
 - Version: VSCodium 1.58.0 x64 2d23c42a936db1c7b3b06f918cde29561cc47cd6

**Additional context**
Log:
```
~$ codium -v
1.58.0
2d23c42a936db1c7b3b06f918cde29561cc47cd6
x64
~$ 
~$ 
~$ 
~$ 
~$ codium --verbose
[main 2021-07-12T02:48:11.637Z] Starting VS Code
[main 2021-07-12T02:48:11.638Z] from: /usr/share/codium/resources/app
[main 2021-07-12T02:48:11.638Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/userdir/.config/VSCodium/logs/20210712T104811'
}
[main 2021-07-12T02:48:11.642Z] Resolving machine identifier...
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/codium/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/usr/share/codium/resources/app/out/vs/loader.js:4:698)
    at bindings (/usr/share/codium/resources/app/node_modules.asar/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/codium/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/codium/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/share/codium/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:4:1722)
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:3:10249)
    at l (/usr/share/codium/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/codium/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/codium/resources/app/out/vs/loader.js:3:10613)
    at /usr/share/codium/resources/app/out/vs/loader.js:3:10319
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:4:1739)
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:3:10249)
    at l (/usr/share/codium/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/codium/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/codium/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/codium/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/codium/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/codium/resources/app/out/vs/loader.js:5:9420)
    at D.P (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:4497)
    at new Promise (<anonymous>)
    at D (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:4477)
    at n._createSpdLogLogger (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:5457)
    at new n (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:5273)
    at /usr/share/codium/resources/app/out/vs/code/electron-main/main.js:61:2090
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async se.startup (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:61:1899) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
[main 2021-07-12T02:48:11.646Z] Resolved machine identifier: 6b4d33ddee9d7365ebdebb1ef13491bf7443ea1c99825c5fd76b1a8c4853fc04
[main 2021-07-12T02:48:11.647Z] Main->SharedProcess#connect
[main 2021-07-12T02:48:11.839Z] StorageMainService: creating global storage
[main 2021-07-12T02:48:11.840Z] lifecycle (main): phase changed (value: 2)
[main 2021-07-12T02:48:11.842Z] windowsManager#open
[main 2021-07-12T02:48:11.843Z] windowsManager#open pathsToOpen [
  {
    backupPath: '/home/userdir/.config/VSCodium/Backups/1624534218688',
    remoteAuthority: undefined
  }
]
[main 2021-07-12T02:48:11.847Z] IPC Object URL: Registered new channel vscode:d4b13679-c0d6-4fae-a9aa-b9c602581251.
[main 2021-07-12T02:48:11.848Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 173, y: 31, width: 1024, height: 708 }
[main 2021-07-12T02:48:11.848Z] window#validateWindowState: 1 monitor working area { x: 1, y: 0, width: 1365, height: 740 }
[main 2021-07-12T02:48:11.849Z] window#ctor: using window state { mode: 1, x: 173, y: 31, width: 1024, height: 708 }
[main 2021-07-12T02:48:11.849Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[main 2021-07-12T02:48:12.012Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-07-12T02:48:12.013Z] lifecycle (main): phase changed (value: 3)
[main 2021-07-12T02:48:12.015Z] update#setState idle
[main 2021-07-12T02:48:12.018Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2021-07-12T02:48:12.636Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/codium/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/usr/share/codium/resources/app/out/vs/loader.js:4:698)
    at bindings (/usr/share/codium/resources/app/node_modules.asar/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/codium/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/codium/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/share/codium/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:4:1722)
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:3:10249)
    at l (/usr/share/codium/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/codium/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/codium/resources/app/out/vs/loader.js:3:10613)
    at /usr/share/codium/resources/app/out/vs/loader.js:3:10319
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:4:1739)
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:3:10249)
    at l (/usr/share/codium/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/codium/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/codium/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/codium/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/codium/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/codium/resources/app/out/vs/loader.js:5:9420)
    at D.P (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:4497)
    at new Promise (<anonymous>)
    at D (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:4477)
    at n._createSpdLogLogger (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:5457)
    at new n (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:5273)
    at /usr/share/codium/resources/app/out/vs/code/electron-main/main.js:61:2090
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async se.startup (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:61:1899) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
[main 2021-07-12T02:48:13.862Z] StorageMainService: creating workspace storage (1624534218688)
[18861:0712/104813.959378:INFO:CONSOLE(627)] "%cTRACE color: #888 Error while resolving configuration file 'vscode-userdata:/home/userdir/.config/VSCodium/User/settings.json': Unable to read file 'vscode-userdata:/home/userdir/.config/VSCodium/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-userdata:/home/userdir/.config/VSCodium/User/settings.json')", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[18861:0712/104813.960628:INFO:CONSOLE(627)] "%cTRACE color: #888 Error while resolving configuration file 'vscode-userdata:/home/userdir/.config/VSCodium/User/tasks.json': Unable to read file 'vscode-userdata:/home/userdir/.config/VSCodium/User/tasks.json' (Error: Unable to resolve non-existing file 'vscode-userdata:/home/userdir/.config/VSCodium/User/tasks.json')", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[18861:0712/104815.335202:INFO:CONSOLE(627)] "%cTRACE color: #888 [lifecycle] starting up (startup kind: 1)", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[18861:0712/104815.350659:INFO:CONSOLE(627)] "%cTRACE color: #888 lifecycle: phase changed (value: 2)", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[18861:0712/104815.357013:INFO:CONSOLE(627)] "%cTRACE color: #888 Renderer->SharedProcess#connect", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[18861:0712/104815.359443:INFO:CONSOLE(627)] "%cTRACE color: #888 Skipping initializing user data in desktop", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[18861:0712/104815.564746:INFO:CONSOLE(627)] "%cTRACE color: #888 Layout#layout, height: 683, width: 1024", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[18861:0712/104815.586162:INFO:CONSOLE(627)] "%cTRACE color: #888 workbench configuration {"_":[],"diff":false,"add":false,"goto":false,"new-window":false,"reuse-window":false,"wait":false,"help":false,"list-extensions":false,"show-versions":false,"version":false,"verbose":true,"status":false,"prof-startup":false,"no-cached-data":false,"prof-v8-extensions":false,"disable-extensions":false,"disable-gpu":false,"telemetry":false,"debugRenderer":false,"logExtensionHostCommunication":false,"skip-release-notes":false,"skip-welcome":false,"disable-telemetry":false,"disable-updates":false,"disable-keytar":false,"disable-workspace-trust":false,"disable-crash-reporter":false,"skip-add-to-recently-opened":false,"unity-launch":false,"open-url":false,"file-write":false,"file-chmod":false,"driver-verbose":false,"force":false,"do-not-sync":false,"trace":false,"force-user-env":false,"force-disable-user-env":false,"open-devtools":false,"__sandbox":false,"no-proxy-server":false,"nolazy":false,"force-renderer-accessibility":false,"ignore-certificate-errors":false,"allow-insecure-localhost":false,"logsPath":"/home/userdir/.config/VSCodium/logs/20210712T104811","machineId":"6b4d33ddee9d7365ebdebb1ef13491bf7443ea1c99825c5fd76b1a8c4853fc04","windowId":1,"mainPid":18861,"appRoot":"/usr/share/codium/resources/app","execPath":"/usr/share/codium/codium","codeCachePath":"/home/userdir/.config/VSCodium/CachedData/2d23c42a936db1c7b3b06f918cde29561cc47cd6","backupPath":"/home/userdir/.config/VSCodium/Backups/1624534218688","homeDir":"/home/userdir","tmpDir":"/tmp","userDataDir":"/home/userdir/.config/VSCodium","userEnv":{"VSCODE_IPC_HOOK":"/run/user/1000/vscode-8d1ddd04-1.58.0-main.sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}"},"logLevel":0,"product":{"nameShort":"VSCodium","nameLong":"VSCodium","applicationName":"codium","dataFolderName":".vscode-oss","win32MutexName":"vscodium","licenseName":"MIT","licenseUrl":"https://github.com/microsoft/vscode/blob/main/LICENSE.txt","win32DirName":"VSCodium","win32NameVersion":"VSCodium","win32RegValueName":"VSCodium","win32AppId":"{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}","win32x64AppId":"{{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}","win32arm64AppId":"{{D1ACE434-89C5-48D1-88D3-E2991DF85475}","win32UserAppId":"{{C6065F05-9603-4FC4-8101-B9781A25D88E}","win32x64UserAppId":"{{2E1F05D1-C245-4562-81EE-28188DB6FD17}","win32arm64UserAppId":"{{3AEBF0C8-F733-4AD4-BADE-FDB816D53D7B}","win32AppUserModelId":"Microsoft.VSCodium","win32ShellNameShort":"VSCodium","darwinBundleIdentifier":"com.visualstudio.code.oss","linuxIconName":"vscodium","licenseFileName":"LICENSE.txt","reportIssueUrl":"https://github.com/microsoft/vscode/issues/new","urlProtocol":"vscodium","webviewContentExternalBaseUrlTemplate":"https://{{uuid}}.vscode-webview.net/{{quality}}/{{commit}}/out/vs/workbench/contrib/webview/browser/pre/","extensionAllowedProposedApi":["ms-vscode.vscode-js-profile-flame","ms-vscode.vscode-js-profile-table","ms-vscode.remotehub","ms-vscode.remotehub-insiders","GitHub.remotehub","GitHub.remotehub-insiders","ms-vscode.cpptools","ms-azuretools.vscode-docker","visualstudioexptteam.vscodeintellicode","GitHub.codespaces","GitHub.vscode-pull-request-github-insiders","GitHub.vscode-pull-request-github","Microsoft.vscode-nmake-tools","ms-ai-tools.notebook-renderers","ms-dotnettools.dotnet-interactive-vscode","ms-python.gather","ms-python.python","ms-toolsai.jupyter","ms-toolsai.vscode-ai","ms-toolsai.vscode-ai-remote","ms-vscode-remote.remote-containers-nightly","ms-vscode-remote.remote-containers","ms-vscode-remote.remote-ssh-edit-nightly","ms-vscode-remote.remote-ssh-edit","ms-vscode-remote.remote-ssh-nightly","ms-vscode-remote.remote-ssh","ms-vscode-remote.remote-wsl-nightly","ms-vscode-remote.remote-wsl","ms-vscode-remote.remote-wsl-recommender","ms-vscode-remote.vscode-remote-extensionpack-nightly","ms-vscode-remote.vscode-remote-extensionpack","ms-vscode.azure-account","ms-vscode.azure-sphere-tools-ui","ms-vscode.azure-sphere-tools","ms-vscode.github-browser","ms-vscode.github-richnav","ms-vscode.js-debug-nightly","ms-vscode.js-debug","ms-vscode.lsif-browser","ms-vscode.vscode-js-profile-flame","ms-vscode.vscode-js-profile-table","ms-vscode.vscode-selfhost-test-provider","ms-vsliveshare.cloudenv-explorer","ms-vsliveshare.cloudenv","ms-vsliveshare.vsliveshare","ms-vsonline.vsonline","dbaeumer.vscode-eslint"],"builtInExtensions":[{"name":"ms-vscode.node-debug","version":"1.44.28","repo":"https://github.com/microsoft/vscode-node-debug","metadata":{"id":"b6ded8fb-a0a0-4c1c-acbd-ab2a3bc995a6","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}},{"name":"ms-vscode.node-debug2","version":"1.42.7","repo":"https://github.com/microsoft/vscode-node-debug2","metadata":{"id":"36d19e17-7569-4841-a001-947eb18602b2","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}},{"name":"ms-vscode.references-view","version":"0.0.80","repo":"https://github.com/microsoft/vscode-references-view","metadata":{"id":"dc489f46-520d-4556-ae85-1f9eab3c412d","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}},{"name":"ms-vscode.js-debug-companion","version":"1.0.13","repo":"https://github.com/microsoft/vscode-js-debug-companion","metadata":{"id":"99cb0b7f-7354-4278-b8da-6cc79972169d","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}},{"name":"ms-vscode.js-debug","version":"1.58.2","repo":"https://github.com/microsoft/vscode-js-debug","metadata":{"id":"25629058-ddac-4e17-abba-74678e126c5d","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}},{"name":"ms-vscode.vscode-js-profile-table","version":"0.0.18","repo":"https://github.com/microsoft/vscode-js-profile-visualizer","metadata":{"id":"7e52b41b-71ad-457b-ab7e-0620f1fc4feb","publisherId":{"publisherId":"5f5636e7-69ed-4afe-b5d6-8d231fb3d3ee","publisherName":"ms-vscode","displayName":"Microsoft","flags":"verified"},"publisherDisplayName":"Microsoft"}}],"checksumFailMoreInfoUrl":"https://go.microsoft.com/fwlink/?LinkId=828886","tipsAndTricksUrl":"https://go.microsoft.com/fwlink/?linkid=852118","twitterUrl":"https://go.microsoft.com/fwlink/?LinkID=533687","requestFeatureUrl":"https://go.microsoft.com/fwlink/?LinkID=533482","documentationUrl":"https://go.microsoft.com/fwlink/?LinkID=533484#vscode","introductoryVideosUrl":"https://go.microsoft.com/fwlink/?linkid=832146","extensionAllowedBadgeProviders":["api.bintray.com","api.travis-ci.com","api.travis-ci.org","app.fossa.io","badge.fury.io","badge.waffle.io","badgen.net","badges.frapsoft.com","badges.gitter.im","badges.greenkeeper.io","cdn.travis-ci.com","cdn.travis-ci.org","ci.appveyor.com","circleci.com","cla.opensource.microsoft.com","codacy.com","codeclimate.com","codecov.io","coveralls.io","david-dm.org","deepscan.io","dev.azure.com","flat.badgen.net","gemnasium.com","githost.io","gitlab.com","godoc.org","goreportcard.com","img.shields.io","isitmaintained.com","marketplace.visualstudio.com","nodesecurity.io","opencollective.com","snyk.io","travis-ci.com","travis-ci.org","visualstudio.com","vsmarketplacebadge.apphb.com","www.bithound.io","www.versioneye.com"],"updateUrl":"https://vscodium.now.sh","releaseNotesUrl":"https://go.microsoft.com/fwlink/?LinkID=533483#vscode","keyboardShortcutsUrlMac":"https://go.microsoft.com/fwlink/?linkid=832143","keyboardShortcutsUrlLinux":"https://go.microsoft.com/fwlink/?linkid=832144","keyboardShortcutsUrlWin":"https://go.microsoft.com/fwlink/?linkid=832145","quality":"stable","extensionsGallery":{"serviceUrl":"https://open-vsx.org/vscode/gallery","itemUrl":"https://open-vsx.org/vscode/item"},"linkProtectionTrustedDomains":["https://open-vsx.org"],"serverDataFolderName":".vscode-server-oss","commit":"2d23c42a936db1c7b3b06f918cde29561cc47cd6","date":"2021-07-10T14:21:16.884Z","checksums":{"vs/base/parts/sandbox/electron-browser/preload.js":"M+kHnRDshORRB7NZhN5knA","vs/workbench/workbench.desktop.main.js":"9ZyR5uefXQNdmAg9OSU15A","vs/workbench/workbench.desktop.main.css":"m0Uxh4RrUE56MyX+R+wHBA","vs/workbench/services/extensions/node/extensionHostProcess.js":"CDLaWQKpSOd4CqkuZEjPEg","vs/code/electron-browser/workbench/workbench.html":"TrJuwpwo4qJ4rtoFdVJZoA","vs/code/electron-browser/workbench/workbench.js":"Q8F6NfpFL2quSfgNoyvVtw"},"version":"1.58.0"},"isInitialStartup":true,"perfMarks":[{"name":"code/timeOrigin","startTime":1626058089518},{"name":"code/didStartMain","startTime":1626058091185},{"name":"code/willStartCrashReporter","startTime":1626058091230},{"name":"code/didStartCrashReporter","startTime":1626058091249},{"name":"code/mainAppReady","startTime":1626058091309},{"name":"code/willLoadMainBundle","startTime":1626058091393},{"name":"code/fork/willLoadCode","startTime":1626058091408},{"name":"code/registerFilesystem/file","startTime":1626058091568},{"name":"code/didLoadMainBundle","startTime":1626058091574},{"name":"code/willStartMainServer","startTime":1626058091600},{"name":"code/willStartMainServer","startTime":1626058091605},{"name":"code/didStartMainServer","startTime":1626058091605},{"name":"code/willCreateCodeWindow","startTime":1626058091846},{"name":"code/willRestoreCodeWindowState","startTime":1626058091848},{"name":"code/didRestoreCodeWindowState","startTime":1626058091849},{"name":"code/willCreateCodeBrowserWindow","startTime":1626058091850},{"name":"code/didCreateCodeBrowserWindow","startTime":1626058091949},{"name":"code/didCreateCodeWindow","startTime":1626058091951},{"name":"code/willOpenNewWindow","startTime":1626058092006}],"os":{"release":"4.15.0-142-generic","hostname":"ndimalanta-Inspiron-15-3567"},"autoDetectHighContrast":true,"accessibilitySupport":false,"colorScheme":{"dark":false,"highContrast":false},"fullscreen":false,"maximized":false}", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[18861:0712/104815.595009:INFO:CONSOLE(627)] "%cTRACE color: #888 lifecycle: phase changed (value: 3)", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[main 2021-07-12T02:48:15.630Z] SharedProcess: on vscode:createSharedProcessMessageChannel
[main 2021-07-12T02:48:15.631Z] IPC Object URL: Registered new channel vscode:b9553521-4bfe-438f-8231-fbc9993e505a.
[main 2021-07-12T02:48:15.718Z] menubarService#updateMenubar 1
[main 2021-07-12T02:48:15.756Z] menubarService#updateMenubar 1
[18861:0712/104816.183993:INFO:CONSOLE(627)] "%cTRACE color: #888 [File Watcher (node.js)] [ADDED] /home/userdir/.config/VSCodium/logs/20210712T104811/output_1_20210712T104815", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[main 2021-07-12T02:48:16.189Z] menubarService#updateMenubar 1
[main 2021-07-12T02:48:16.197Z] menubarService#updateMenubar 1
[main 2021-07-12T02:48:16.198Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[18861:0712/104816.338648:INFO:CONSOLE(627)] "%cTRACE color: #888 [File Watcher (node.js)] >> normalized [ADDED] /home/userdir/.config/VSCodium/logs/20210712T104811/output_1_20210712T104815", source: vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[main 2021-07-12T02:48:16.404Z] menubarService#updateMenubar 1
[main 2021-07-12T02:48:16.661Z] RequestService#request https://vscodium.now.sh/api/update/linux-x64/stable/2d23c42a936db1c7b3b06f918cde29561cc47cd6
[main 2021-07-12T02:48:16.662Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/codium/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/usr/share/codium/resources/app/out/vs/loader.js:4:698)
    at bindings (/usr/share/codium/resources/app/node_modules.asar/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/codium/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/codium/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/share/codium/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:4:1722)
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:3:10249)
    at l (/usr/share/codium/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/codium/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/codium/resources/app/out/vs/loader.js:3:10613)
    at /usr/share/codium/resources/app/out/vs/loader.js:3:10319
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:4:1739)
    at r.load (/usr/share/codium/resources/app/out/vs/loader.js:3:10249)
    at l (/usr/share/codium/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/codium/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/codium/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/codium/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/codium/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/codium/resources/app/out/vs/loader.js:5:9420)
    at D.P (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:4497)
    at new Promise (<anonymous>)
    at D (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:4477)
    at n._createSpdLogLogger (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:5457)
    at new n (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:32:5273)
    at /usr/share/codium/resources/app/out/vs/code/electron-main/main.js:61:2090
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async se.startup (/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:61:1899) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}


```

**Comment by GitMensch** [comment] 2021-07-29 08:52
Seems like a duplicate of #644, as far as I know this issue both originated in "Microsoft's Visual Studio Code" (see the links in the and wasn't solved there yet.
@rhizene are you sure that your first mark "Doesn't happen [on this system] if you use Microsoft's Visual Studio Code" is correct?

**Comment by GitMensch** [comment] 2021-07-29 08:57
Hm, what about this likely fix?
https://github.com/microsoft/vscode/pull/129360

**Comment by daiyam** [comment] 2021-07-29 10:26
@GitMensch yes, it will likely be fixed by that PR.

**Comment by rhizene** [comment] 2021-07-29 11:16
Hi everyone, thanks for replying. I've decided to do the PPA 

@daiyam  yes, I was missing that version (command output today at bottom is up to 3.4.21, before applying PPA)
@GitMensch  yes, I am able to run VSCode.




```
~ $ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Closed** 2021-07-29 11:17 UTC
Labels: bug
