### ISSUE TITLE
MAC address retrieval on startup

### ISSUE THREAD

**Issue by msdobrescu** [VSCodium/vscodium#292] opened 2019-11-22 18:26 UTC
**Describe the bug**
The following message appears in console at running the AppImage file:

[uncaught exception in main]: Unable to retrieve mac address (Error: Command failed: /sbin/ifconfig -a || /sbin/ip link
/bin/sh: /sbin/ifconfig: No such file or directory
/bin/sh: /sbin/ip: No such file or directory
)

It probably needs Internet connection to install languages and tools, but why looking for the MAC address, ifconfig  and ip?

The resources are not available, but some more might be found and not logged.

Desktop:
 - OS: Linux Sabayon
 - Architecture: x64
 - Up to date - it's rolling release

**Comment by stripedpajamas** [comment] 2019-11-22 18:28
That looks pretty weird. The hope is that since we replace the telemetry IPs with 0.0.0.0 that even if the telemetry settings aren't honored it wouldn't go anywhere. I will try to reproduce this locally to see if I can find out where in the code this is happening.

**Comment by stripedpajamas** [comment] 2019-11-22 18:29
@tyu1996 do you get this with the AppImage as well?

**Comment by msdobrescu** [comment] 2019-11-22 19:36
Hope? A nice intention... but we need certainty! I appreciate the effort, guys!

**Comment by stripedpajamas** [comment] 2019-11-24 21:48
Yes, after some digging through the code, it does appear VSCode tries to get the MAC address to use as a machine id for telemetry purposes. The places that use the machine id (as far as I can tell) honor the setting ('enable telemetry') which VSCodium has disabled by default. 

If you (or anyone) does find any outbound requests happening from VSCodium that are suspected telemetry, please let us know so we can figure out how they're happening and disable them.

As is, I don't think there's any action for us to take here -- let me know if you think otherwise.

Some refs (not exhaustive):
-  [mac address retrieval](https://github.com/microsoft/vscode/blob/master/src/vs/base/node/macAddress.ts#L44)
- [id module using mac address for machine id](https://github.com/microsoft/vscode/blob/master/src/vs/base/node/id.ts#L83)
- [main app getting machine id](https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-main/app.ts#L361)
- [one example use of machine id](https://github.com/microsoft/vscode/blob/d6cd08ba605f52df412cf072440558a13eb5af91/src/vs/code/electron-main/app.ts#L483-L485)

**Comment by msdobrescu** [comment] 2019-11-24 21:58
Hi, I have a question: do you have the environment variable for meterig set as below?
`DOTNET_CLI_TELEMETRY_OPTOUT=1`
I couldn't find it mentioned on VSCodium site.
Seemingly, VSCodium and .net core obey to it.
In my tests, the MAC retrieval was not attempted with this variable set as above.

**Comment by stripedpajamas** [comment] 2019-11-24 22:00
I do not have this environment variable set.

**Comment by msdobrescu** [comment] 2019-11-24 22:00
As for the action I think you should take, IMHO, look for the metering entry point and disable it (or replace it by some no-op function) in order to do what you intend, i.e. avoid metering.

**Comment by msdobrescu** [comment] 2019-11-24 22:02
Well, to me, it makes the difference if DOTNET_CLI_TELEMETRY_OPTOUT=1 is set or not, at least when using the AppImage.

**Comment by stripedpajamas** [comment] 2019-11-24 22:05
We have disabled telemetry in VSCodium; have you found evidence to the contrary? Code that is trying to get the MAC address is not evidence of telemetry; if you have found that the machine ID is being sent to MS, this would be evidence of telemetry and something we would want to resolve.

**Comment by msdobrescu** [comment] 2019-11-24 22:14
Can't be sure. I see different behaviour according to the telemetry variable setting.

**Comment by stripedpajamas** [comment] 2019-11-24 22:23
The variable you mention is not in code or issues in `vscode` ([ref](https://github.com/microsoft/vscode/search?q=DOTNET_CLI_TELEMETRY_OPTOUT&unscoped_q=DOTNET_CLI_TELEMETRY_OPTOUT)). I also searched installed node_modules of `vscode`'s source. I can't imagine how this variable would affect Code or Codium.

Regardless, in your testing it only affected retrieval of the mac address. I still am not seeing any evidence that the mac address is being sent to MS in any telemetry as long as telemetry is disabled (which it is in VSCodium). I will close this issue. Please, if you find that VSCodium is making unauthorized connections to MS servers, open an issue with steps to reproduce and we will resolve it.

**Closed by stripedpajamas** 2019-11-24 22:23 UTC
