### ISSUE TITLE
cannot launch  vscodium appimage

### ISSUE THREAD

**Issue by newyorkthink** [VSCodium/vscodium#919] opened 2021-11-13 07:26 UTC
![image](https://user-images.githubusercontent.com/87791643/141610096-e9fc585f-d1f4-4b7d-897f-f0800b96f718.png)

**Comment by buster-blue** [comment] 2021-11-15 19:41
Are you using Fedora 35? I'm having the same issue after updating from Fedora 34, where the appimage worked correctly.

**Comment by th4tkh13m** [comment] 2021-11-26 07:12
I'm getting the same issue on Void Linux

**Comment by daiyam** [comment] 2021-11-26 08:28
The issue is due to the new `glib2 2.70` and not limited to VSCodium...
I wasn't successful with the workaround: https://bbs.archlinux.org/viewtopic.php?pid=1994258#p1994258

**Comment by daiyam** [comment] 2021-12-17 22:14
Can you try [VSCodium-1.63.2-1639774037.glibc2.17-x86_64.AppImage.zip](https://app.box.com/s/lgmxi73qebmsiwv7liy6thwlh0105r8h)?
I've been able to make it run under Arch and Fedora 34/35 while being built on Ubuntu 18.04.
The changes I've made can be found at #944.

**Comment by eightfiftytwo** [comment] 2021-12-29 07:08
> Can you try [VSCodium-1.63.2-1639774037.glibc2.17-x86_64.AppImage.zip](https://app.box.com/s/lgmxi73qebmsiwv7liy6thwlh0105r8h)? I've been able to make it run under Arch and Fedora 34/35 while being built on Ubuntu 18.04. The changes I've made can be found at #944.

Works on Fedora 35

**Comment by Mu-00** [comment] 2021-12-30 16:51
> Can you try [VSCodium-1.63.2-1639774037.glibc2.17-x86_64.AppImage.zip](https://app.box.com/s/lgmxi73qebmsiwv7liy6thwlh0105r8h)? I've been able to make it run under Arch and Fedora 34/35 while being built on Ubuntu 18.04. The changes I've made can be found at #944.

Works on Gentoo

**Comment by daiyam** [comment] 2021-12-30 17:22
Before pushing the PR, I'm waiting for more feedback from the AppImage team. I've isolated the issue is due to the libraries `libgmodule-2.0.so` and `libsqlite3.so`.
In any case, I will push it for the next release.

**Comment by daiyam** [comment] 2021-12-31 02:58
Closing in favor of #854 (same issue, first report)

**Closed by daiyam** 2021-12-31 02:58 UTC
Labels: bug
