### ISSUE TITLE
python extension - interpreter selector not showing on status bar

### ISSUE THREAD

**Issue by juliuswz** [VSCodium/vscodium#535] opened 2020-10-14 02:56 UTC
**Describe the bug**
Interpreter selector don't show when open a python file.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1.  Open a Python file and wait for the extension to activate. Notice the interpreter not showing on the status bar.

**Screenshots**

**Expected behavior**
![InterpreterSelectionZoom](https://user-images.githubusercontent.com/36483985/95936298-c08ab900-0dc4-11eb-9227-1774424500f3.gif)

**Actual behaviour**
![Screenshot_20201013_231159](https://user-images.githubusercontent.com/36483985/95936629-94bc0300-0dc5-11eb-805c-c8903a578a68.png)

The extension is activated (it even activates my virtual environment when I create a new terminal) and working normally, I just can't see the interpreter on the status bar.

**Desktop (please complete the following information):**
 - OS: [ Arch Linux ]
 - Architecture [ x64 ]
 - Version [ 1.50.0 ]

**Additional context**

**Logs:**
Output for Python in the Output panel:
```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
> conda --version
> pyenv root
> python3.7 ~/.vscode-oss/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-oss/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-oss/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-oss/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-oss/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~/venv/python3.8/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2020-10-13 23:38:25: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): '/home/julius/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/julius/.config/Code/User/settings.json')
	at _handleError (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:725:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (/home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:1:498547)
	at async p.doesFileNeedToBeFixed (/home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:56:961593)
	at async /home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:56:960720
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:56:960666)
	at async p.updateTestSettings (/home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:56:960293)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
> ~/venv/python3.8/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/venv/python3.8/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.9.112786/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
Starting Jedi Python language engine.
Python interpreter path: /home/julius/venv/python3.8/bin/python
Error 2020-10-13 23:38:26: Python Extension: interpreterManager.refresh [Error: [ms-python.python]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-python.python
	at a (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:99)
	at Object.t.checkProposedApiEnabled (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:567)
	at Object.get activeNotebookEditor [as activeNotebookEditor] (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1003:116)
	at u.get activeNotebookEditor [as activeNotebookEditor] (/home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:54:383170)
	at u.get hidden [as hidden] (/home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:56:642106)
	at /home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:56:844423
	at Array.every (<anonymous>)
	at g.updateVisibility (/home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:56:844411)
	at g.updateDisplay (/home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:56:844284)
	at async g.refresh (/home/julius/.vscode-oss/extensions/ms-python.python-2020.9.112786/out/client/extension.js:56:843237)]
```

**Comment by vvatelot** [comment] 2020-10-19 08:39
Exact same error here

**Comment by Razique** [comment] 2020-10-20 03:09
I confirm the issue  on MacOS
```

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T11:18:43.323Z (4 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by Baldomo** [comment] 2020-10-30 13:30
Same here, using the command line option make it work as intended though
```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T11:13:06.921Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.1-arch1-2-g14
```

**Comment by elmaghallawy** [comment] 2020-11-09 10:23
same error here
```
Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-06T10:57:27.345Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.18-300.fc33.x86_64
```

**Comment by alexdesiqueira** [comment] 2020-11-22 19:42
Same issue. Running Debian Testing:
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-12T00:31:42.540Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.0-2-amd64
```

**Comment by cleversonahum** [comment] 2020-12-01 19:10
Same issue:
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-12T10:54:25.653Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.80-2-MANJARO

**Comment by elmaghallawy** [comment] 2020-12-12 07:08
Hi there, the issue is fixed for me now on 
```
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-12T00:37:51.866Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.13-200.fc33.x86_64
```
![Screenshot from 2020-12-12 09-07-13](https://user-images.githubusercontent.com/52883485/101977881-7e151980-3c59-11eb-968f-562ce6e67dcc.png)

**Comment by alexdesiqueira** [comment] 2020-12-12 17:17
Working for me on `1.52` as well:
```
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-12T00:37:51.866Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.0-4-amd64
```
Thank you everyone!

**Comment by lxwulf** [comment] 2021-06-16 17:46
I have exactly this problem now, what should I do? Waiting for the next update?...

**Comment by alexdesiqueira** [comment] 2021-06-16 18:09
@lxwulf what version are you using? Please check on `Help > About` and post it back :slightly_smiling_face:

**Comment by FeGeyer** [comment] 2021-06-17 07:54
I have the same problem now. This is my version:
```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-13T03:13:30.581Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-74-generic
```

**Comment by daiyam** [comment] 2021-06-17 09:58
With which python extension are you getting the issue?

**Comment by daiyam** [comment] 2021-06-17 10:24
Yep, I'm getting the issue when using the version `2020.10.332292344` (the latest on open-vsx).
But when using the latest version from the VS Code Marketplace, I don't have the issue

[Here how to switch of marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace)

**Comment by FeGeyer** [comment] 2021-06-17 10:41
Thanks for the hint, I can confirm that this fixes the issue.

**Comment by lxwulf** [comment] 2021-06-17 15:13
> @lxwulf what version are you using? Please check on `Help > About` and post it back

At first, sorry when i sound like being angry or mean - doesnt wanted that way .🙏

I have the problem on one windows machine and linux.

On my linux machine which is more imported i have this version installed:

```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-13T03:13:30.581Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.12.10-300.fc34.x86_64
```

I would try if it makes any different when i install the python extension from the official microsoft extension store.

Greets LxWulf

**Comment by daiyam** [comment] 2021-06-28 17:30
Was this fixed for everyone when using a 2021 version of the extension?

**Comment by Razique** [comment] 2021-06-28 18:27
Yeah I confirm that the 2021 version from the official marketplace solves the issue

**Comment by daiyam** [comment] 2021-06-28 20:10
For the time being, I will close the issue since it seems related to a not up-to-date extension.

**Closed by daiyam** 2021-06-28 20:10 UTC
Labels: bug

**Comment by jazz-it** [comment] 2022-02-07 20:49
I just bumped into this issue on my vscodium v1.64.0 and ms-python v2022.0.1786462952 (5.10.96-1-MANJARO).
I tried to re-install ms-python extension, but it didn't resolve the issue. What logs could I share to help you see what's going on here?
