### ISSUE TITLE
[Discussion] New logo for the project - Final vote, last post

### ISSUE THREAD

**Issue by estatra** [VSCodium/vscodium#313] opened 2020-01-03 02:22 UTC
Hello!

I fell in love with **VSCodium** and what the community is doing with it!

But I think the icon could use some improvement.

I wanted to explore the good metaphor work that @jaredreich did for the current logo and expand it a bit. Keeping to the theme of _Codium tomentosum_, the algae, and the color voted at the time on #4 . Also maybe it could use some more expanded branding, like a logotype. Make the whole thing a tad bit more modern.

Sorry I don't know how to change or add a proper label, I'm not sure I have permission?

**Sources**
```
Reference images for inspiration: Google and Wikipedia
Font: Open Sans Family - Apache License 2.0
```
**Proposal**

![VV1](https://user-images.githubusercontent.com/57003922/71703712-de96a800-2db4-11ea-975b-2d47fea9e809.png)

![VV2](https://user-images.githubusercontent.com/57003922/71703715-e5251f80-2db4-11ea-8f3a-636eeecdc649.png)

![VV1-2](https://user-images.githubusercontent.com/57003922/71703720-e9513d00-2db4-11ea-9615-c10977bf0891.png)

![w10fcubaredesktophero](https://user-images.githubusercontent.com/57003922/71703725-ef471e00-2db4-11ea-9eda-2a859169de00.png)

**Reference**

![Codium_tomentosum](https://user-images.githubusercontent.com/57003922/71703727-f3733b80-2db4-11ea-954b-a618ee4525f7.jpg)

![dead-mans-fingers](https://user-images.githubusercontent.com/57003922/71703731-f9691c80-2db4-11ea-8f83-00fd907963b4.jpg)

**Comment by jaredreich** [comment] 2020-01-04 17:32
This was already exhausted in https://github.com/VSCodium/vscodium/issues/4#issuecomment-427070331

**Comment by Antoine-Derouin** [comment] 2020-01-08 15:52
Since the May 2019 update, the VScode logos are frameless gradient shapes :
![vscode](https://code.visualstudio.com/assets/updates/1_35/logo-stable.png) ![insider](https://code.visualstudio.com/assets/updates/1_35/logo-insiders.png)

It's a shame to enclose the algae in a circle, it would be more in the current trend was alone, and highlighted by a slight gradient.

What do you think?

**Comment by cristianovitorino** [comment] 2020-01-08 17:41
> It's a shame to enclose the algae in a circle, it would be more in the current trend was alone, and highlighted by a slight gradient.
> 
> What do you think?

Good point. Something along these lines?

Atlassian relatively recent rebranding came to mind, quite inspiring. But I'm not fully happy with this hushed thing, just testing what you've suggested, see where it takes us.

![VV1-2](https://user-images.githubusercontent.com/57003922/72001489-584eeb80-3224-11ea-8beb-087d5134d15f.png)

**Comment by Antoine-Derouin** [comment] 2020-01-09 10:24
I liked the shape of your proposal [last night](https://user-images.githubusercontent.com/57003922/72004840-06f62a80-322b-11ea-8ec2-9498e7e9f012.png).

I recognize less coral in this new shape, but I love the shadow folding effect that refers directly to the vscode logo!

**Comment by cristianovitorino** [comment] 2020-01-09 12:00
> I liked the shape of your proposal [last night](https://user-images.githubusercontent.com/57003922/72004840-06f62a80-322b-11ea-8ec2-9498e7e9f012.png).
> 

Oh I removed it, was a bit ashamed of the hushed work haha.

> I recognize less coral in this new shape, but I love the shadow folding effect that refers directly to the vscode logo!

Yeah, me too, less coral, also reminds me of a shell maybe? Still ocean related, but then again, VSCode one reminds me of a fish. And it is still somewhat the shape of the Codium algae, with the added connection with the VSCode logo.

**Comment by Antoine-Derouin** [comment] 2020-01-09 13:21
If you have other ideas for shapes with the same style of shadow folding, don't hesitate!

Now we have to see if the dev & community likes it...

**Comment by cristianovitorino** [comment] 2020-01-10 09:36
> If you have other ideas for shapes with the same style of shadow folding, don't hesitate!

Perhaps this? I'm out of ideas for now. Best to wait for feedback indeed.

![VV1-3](https://user-images.githubusercontent.com/57003922/72142446-76773180-3373-11ea-9f3c-2eb746a906d5.png)

**Comment by Antoine-Derouin** [comment] 2020-01-10 09:58
I like it !
<img width="164" alt="Screenshot 2020-01-10 at 10 56 56" src="https://user-images.githubusercontent.com/1497894/72144013-0fb83f00-3398-11ea-8e97-da9373468c27.png">

**Comment by stripedpajamas** [comment] 2020-02-09 22:35
Hi @cristianovitorino and everyone on this thread 👋 

Thanks so much for the fresh looks. I am open to changes; I am fond of the current logo but I'm all for seeing other options as well. There isn't really a way to get everyone using VSCodium to come vote, but I can leave this issue open for a while to see what kind of reactions we get. I recommend putting ideas in a single comment and asking for votes with emojis as was done with the previous icon thread. We can leave it open for maybe a month or so and see the results. 

💙

**Comment by cristianovitorino** [comment] 2020-02-09 23:53
Hey @stripedpajamas, sounds good to me!

Vote for the style, color can be decided on a second round of votes.

:thumbsup: = 1
:heart: = 2
:smile: = 3
:rocket: = 4

![Proposals](https://user-images.githubusercontent.com/57003922/74112667-4fcc3680-4b7d-11ea-8e65-954df7fd4648.png)

**Comment by JohnRyanAudio** [comment] 2020-02-19 16:42
I'm pretty fond of the current icon. Maybe just removing the current icon from it's circle would be a satisfactory change for me.

**Comment by JonnieCache** [comment] 2020-03-19 10:11
I don't really like the current icon, I agree that the biggest problem is the circle.

Aside from aesthetics, the current logo is mostly white space, with the blue having insufficient contrast against it. This results in it blending into general screen-clutter as compared to other app icons in the dock or in the cmd-tab switcher.

I really like the green and blue options presented above, and I prefer the ones with a bit of depth-shading to them, despite what current trends in flatness (is that over yet?) might tell us.

**Comment by cristianovitorino** [comment] 2020-03-19 10:27
> I really like the green and blue options presented above, and I prefer the ones with a bit of depth-shading to them, despite what current trends in flatness (is that over yet?) might tell us.

Flat is still standard, but "neumorphism" is trending amongst the design community right now, which I find it horrifying... but to each their own. Personally I love flat when well done, but I like to use it as a base to improve upon when we're talking logos and branding, it can benefit from extra "muscle" to give it more unique personalities, pure flat is OK and sufficient for small Icons and some logos, certain cases, etc, but I love a bit of shading and perspective in the correct places and in the right ammount, applied properly and subtly.

If approved, I already know how to improve/tweak a lil bit the proposed redesigns above and make their color iterations for the final choice voting.

**Comment by cristianovitorino** [comment] 2020-04-25 11:45
Hello again @stripedpajamas.

> [...] We can leave it open for maybe a month or so and see the results.

It has been almost 3 months. How should we proceed with this? Are the current amount of votes enough? There is 26 total at the time I'm writing this. Should we leave it a bit longer? Should I proceed further? Or should I close the issue?

**Comment by JohnRyanAudio** [comment] 2020-04-27 15:08
I would say move on. Doesn't seem the conversation is really going to pick up.

**Comment by stripedpajamas** [comment] 2020-04-27 17:49
Hi @cristianovitorino -- so sorry for the long wait time on this PR. It looks like #1 wins! Can you do another quick round for color choice?

**Comment by cristianovitorino** [comment] 2020-04-27 17:53
> Hi @cristianovitorino -- so sorry for the long wait time on this issue. It looks like # 1 wins! Can you do another quick round for color choice?

For sure. I'll get to it soon.

**Comment by cristianovitorino** [comment] 2020-04-27 19:54
Color choice round. Please keep in mind the metaphor for the logo when choosing, Codium is an algae.

Click on the image for full view.

1 = :+1: 
2 = :-1: 
3 = :smile: 
4 = :tada: 
5 = :confused:
6 = :heart:
7 = :rocket:
8 = :eyes:

![VSCodium](https://user-images.githubusercontent.com/57003922/80414518-8aee2400-88a7-11ea-8684-21eb5d91d58e.png)

**Comment by rejedai** [comment] 2020-05-04 07:04
Well, i really think this is perfect.

![image](https://user-images.githubusercontent.com/60342258/80942192-dc893800-8dec-11ea-8726-aa59d7d743d9.png)

**Comment by Antoine-Derouin** [comment] 2020-05-05 00:06
It does indeed look good.
The only detail that bothers me a little is that the aspect ratios (height/width) make it visually small compared to the others.

**Comment by cristianovitorino** [comment] 2020-05-05 01:34
> It does indeed look good.
> The only detail that bothers me a little is that the aspect ratios (height/width) make it visually small compared to the others.

Other than constructing a completely new metaphor and style, or staying with the curretion aspect ration, perhaps something like this could suffice?

### VSCode for reference
![vscode](https://user-images.githubusercontent.com/57003922/81028349-55bd7500-8e57-11ea-9bab-d23b73eee05b.png)

### Outer shell
![variation-1](https://user-images.githubusercontent.com/57003922/81028251-f19ab100-8e56-11ea-8d90-7a63d25a957a.png)

### Outer shell with a symmetric logo inside
![variation-2](https://user-images.githubusercontent.com/57003922/81028259-f6f7fb80-8e56-11ea-985d-f54af41c45da.png)

**Comment by rejedai** [comment] 2020-05-05 17:11
No no, this circle is bad. Just look at this.

![image](https://user-images.githubusercontent.com/60342258/81094730-9e833580-8f0c-11ea-99de-f4a62311ed6c.png)

**Comment by Antoine-Derouin** [comment] 2020-05-05 17:27
Indeed the circle is a regression on the reflection we have led.

I was just imagining a path closer to in ratio 1:1.

I'm thinking something like this :
![codium](https://user-images.githubusercontent.com/1497894/81096288-709af280-8f06-11ea-92bf-184c664c6abf.png)
(I did a stretch, hence the dirty look.)

**Comment by rejedai** [comment] 2020-05-05 17:32
Unfortunately, 1:1 is not always achievable.

**Comment by cristianovitorino** [comment] 2020-05-07 15:39
> No no, this circle is bad. Just look at that.

Calm down, it was a **SUGGESTION**. BTW destructive ego boosted criticism is unnecessary and a waste of everybody's time, this was free and unwarranted. I don't remember displaying disrespect towards you. Adopt proper conversation etiquette or I'm not interested in interacting with you further. "No no" and "this circle is bad" is a useless feedback. "Just look at that" is plain insult at my attempt of collaboration.

Aside from that I agree that different ratios can be an alternative, although I discourage mimicking the Microsoft VSCode logo to every single pixel and ratios.

> [...] I think good idea make bottom darker.

I Disagree. Again I think this is getting too much from the VSCode logo, decreasing the proposal personality.

> I was just imagining a path closer to in ratio 1:1.

Tried that. Looks odd. Still thinking about a possible solution.

> Unfortunately, 1:1 is not always achievable. [...]

True.

**Comment by rejedai** [comment] 2020-05-07 15:56
> "No no" and "this circle is bad" is a useless feedback. "Just look at that" is plain insult at my attempt of collaboration.

Forgive me, I don’t know English well enough, and I don’t yet know what language constructs are disrespectful or insulting. I translated from Russian, and before the translation it did not sound rude or not respectful. _And I really liked your concept of the icon, and also tried to offer something._

**Comment by cristianovitorino** [comment] 2020-05-07 16:09
> > "No no" and "this circle is bad" is a useless feedback. "Just look at that" is plain insult at my attempt of collaboration.
> 
> Forgive me, I don’t know English well enough, and I don’t yet know what language constructs are disrespectful or insulting. I translated from Russian, and before the translation it did not sound rude or not respectful. _And I really liked your concept of the icon, and also tried to offer something._

I see. I understand now, it was a miscommunication error, lost in translation. All is good then.

Let's proceed. I'm iterating and trying new solutions based on the above feedback.

**Comment by cristianovitorino** [comment] 2020-05-07 16:51
@Antoine-Derouin This is a perfect construction of the current proposed VSCodium logo design side-by-side with the Opera and Affinity Designer logos for reference. The proportion is 1:1 horizontally for the VSCodium logo.

Does it still bothers you?

![iteration-1](https://user-images.githubusercontent.com/57003922/81321179-a48e2900-9068-11ea-8c69-eaa74c9dc665.png)


In this suggestion, in an attempt to achieve a 1:1 proportion both horizontally and vertically, I introduced the metaphor of an Isopod, a sea creature, on top of the Codium algae metaphor.

![iteration-2](https://user-images.githubusercontent.com/57003922/81321382-e7e89780-9068-11ea-84b2-ec6670346c29.png)

**Comment by Antoine-Derouin** [comment] 2020-05-08 21:14
Quand je parlais de ratio, c’était pour la forme global et non pour la taille du ruban.

![codium-ratio](https://user-images.githubusercontent.com/1497894/81449881-8bc56680-9181-11ea-8e25-28eaf0a3784e.png)
La vrai question est: est-ce que je suis le seul que ça perturbe ? :joy:

**Comment by cristianovitorino** [comment] 2020-05-08 21:19
@Antoine-Derouin Well I don't speak French, but since we both speak a romance languages (I speak Portuguese) and I have a bit of help from Google Translator, I think I got what you said.

I see what you mean. I'll try to do a less stretched version but try to keep the 1:1 that you seek so much :joy:

**Comment by Antoine-Derouin** [comment] 2020-05-08 21:24
> @Antoine-Derouin Well I don't speak French, but since we both speak romance languages (my mother language is Portuguese) and I have a bit of help from Google Translator, I think I got what you said.

Sorry, a moment of tiredness and haste, I forgot to translate...

Thank you for your patience, it's never easy when it comes to graphic design and community stories.

**Comment by cristianovitorino** [comment] 2020-05-08 21:27
> Sorry, a moment of tiredness and haste, I forgot to translate...
> 
> Thank you for your patience, it's never easy when it comes to graphic design and community stories.

No problem, it's fun to me, I'm used to the iteration process. And I pretty much understood what you said the first time, we share a common ancestor language : )

**Comment by cristianovitorino** [comment] 2020-05-08 23:51
@Antoine-Derouin How about this? 3 different versions, reworked from your idea.

![d83hd](https://user-images.githubusercontent.com/57003922/81457606-26677a80-916d-11ea-85ac-242c4a360789.png)

![fd934js](https://user-images.githubusercontent.com/57003922/81457689-865e2100-916d-11ea-9570-ec2eb1ebdd7e.png)

![c8945hf](https://user-images.githubusercontent.com/57003922/81457694-8b22d500-916d-11ea-9eda-34615c89c27f.png)

**Comment by Antoine-Derouin** [comment] 2020-05-09 00:05
@cristianovitorino I have a preference for the last two.

The second one gives the impression that the folding comes first, it's very nice too!
But it looks a bit like a mouth sticking out its tongue, doesn't it?


I like less the first one with its thinner ribbon.

**Comment by cristianovitorino** [comment] 2020-05-09 00:09
> @cristianovitorino I have a preference for the last two.

So we have at least a way forward :smile: But are you happy with it? Or not 100% yet? Need more iterations?

**Comment by Antoine-Derouin** [comment] 2020-05-09 00:12
For the size ratio and the sensational aspect of the icon's size compared to the others, all three are very good!
Thank you!

I have a preference for the second, but I think we can take a vote, no?

**Comment by cristianovitorino** [comment] 2020-05-09 00:16
> @cgimenes For the size ratio and the sensational aspect of the icon's size compared to the others, all three are very good!
> Thank you!

No problem : )

> I have a preference for the second, but I think we can take a vote, no?

But you said you had a preference for the third, I'm confused. But sure, let's put it to a vote, let me know which one you prefer also so I have an idea what you're looking for. I'll number the candidates this time.

**Comment by cristianovitorino** [comment] 2020-05-09 00:21
@Antoine-Derouin There we go : )

1 = :heart:  
2 = :+1:
3 = :rocket: 

![1](https://user-images.githubusercontent.com/57003922/81458655-d939d780-9171-11ea-9140-f35afdb42259.png)

![2](https://user-images.githubusercontent.com/57003922/81458658-ddfe8b80-9171-11ea-8f40-122fe21a2c69.png)

![3](https://user-images.githubusercontent.com/57003922/81458660-e0f97c00-9171-11ea-8392-c8bb48566055.png)

**Comment by aral** [comment] 2020-05-28 08:58
@cristianovitorino First off, thank you for your hard work and initiative on this.

Quick, blunt initial reactions from someone seeing it for the first time: looks very suggestive (open mouth, tongue). I would avoid.

Skimming through the thread, I far prefer the tree-like logo idea in https://github.com/VSCodium/vscodium/issues/313#issuecomment-583909540

As a third alternative: how about riffing off of the idea that “codium” sounds like a drug (perhaps to fix what’s wrong with VSCode?) Perhaps we can veer away from a literal reinterpretation to an homage with a bit of unique character?

Quick sketch:

![vscodium-pill-logo-idea-sketch](https://user-images.githubusercontent.com/41798/83120878-85b00f00-a0c9-11ea-864b-61de2d68c9c9.png)

- Use of colour to pay homage to its origins but with contrasting green (from your logo) to portray difference
- Pun on the name sounding like a drug (codium / opium)
- Could also be stylised differently (this is more about the idea)

Thoughts? (I’m not married to anything about it; please feel free to shoot it down, etc. Just wanted to share it as I thought it was fun.) :)

<3

**Comment by rejedai** [comment] 2020-05-28 09:00
Please give without drugs.

**Comment by cristianovitorino** [comment] 2020-05-28 12:35
@aral Hey thanks for contributing, it's an open thread, decisions are up to the project author and the community.

The tongue thing is up for interpretation, as I never saw that that way myself, until someone pointed it out of one of the proposed designs. It's purely psychological, for anyone in doubt or interested look up _Rorschach Test_.

That doesn't mean that the design can't be challenged or iterated further if it has significant issues. But we need to be careful not to do this ad infinitum, looking at every look and cranny for defects with each new iteration and keep iterating forever. Ponderation of the overall design needs do be done, and it's currently on vote.

My intent is to keep to the marine theme, both representing the overall shape of the Codium algae and of a Clam Shell.

I disagree with the drug interpretation, I don't endorse any kind of drug, licit or illicit unless your health is at risk and you need real medication for real healthy problems, I don't think the metaphor serves a purpose on this project, as it's not related to the either the pharmaceutical industry nor any health organization.

**Comment by aral** [comment] 2020-05-28 14:26
Not my circus; not my horses ;) Feel free to use, not use, iterate on, abandon, set on fire, as you wish ;)

**Comment by cristianovitorino** [comment] 2020-05-28 17:29
@Antoine-Derouin Is this a relevant issue? Should I add, perhaps, this, in a  new round with the current winner?

![asdj55](https://user-images.githubusercontent.com/57003922/83173539-822f7e80-a0ef-11ea-8769-98681062e063.png)

![dfjk5](https://user-images.githubusercontent.com/57003922/83173605-865b9c00-a0ef-11ea-915c-bf8464d768cf.png)

**Comment by rejedai** [comment] 2020-05-28 17:32
I think a more rounded version is better.

> @Antoine-Derouin Is this a relevant issue? Should I add, perhaps, this, in a new round with the current winner?
> 
> ![asdj55](https://user-images.githubusercontent.com/57003922/83173539-822f7e80-a0ef-11ea-8769-98681062e063.png)
> 
> ![dfjk5](https://user-images.githubusercontent.com/57003922/83173605-865b9c00-a0ef-11ea-915c-bf8464d768cf.png)

I think a more rounded version is better.

**Comment by Antoine-Derouin** [comment] 2020-05-28 17:39
I have nothing against this, but as @rejedai said, the logo with roundish were warmer.

Just a thought, it could be nice to have a "moebius ribbon" variation, couldn't it?

**Comment by cristianovitorino** [comment] 2020-05-28 18:09
> I have nothing against this, but as @rejedai said, the logo with roundish were warmer.
> 
> Just a thought, it could be nice to have a "Möbius strip" variation, couldn't it?

#### Current winner, improved, polished

![sdfklg](https://user-images.githubusercontent.com/57003922/83177196-033d4480-a0f5-11ea-9b77-3682bfedd5fd.png)

![54uqsdf](https://user-images.githubusercontent.com/57003922/83177217-09cbbc00-a0f5-11ea-9890-e2cec9cec919.png)

#### A "Möbius Strip" version

![qsdjif45](https://user-images.githubusercontent.com/57003922/83177253-1cde8c00-a0f5-11ea-8618-f5ff3261a053.png)

![asjgg](https://user-images.githubusercontent.com/57003922/83177267-22d46d00-a0f5-11ea-91d2-f34511a8036b.png)

**Comment by rejedai** [comment] 2020-05-28 18:13
> > I have nothing against this, but as @rejedai said, the logo with roundish were warmer.
> > Just a thought, it could be nice to have a "Möbius strip" variation, couldn't it?
> 
> #### Current winner, improved, polished
> ![sdfklg](https://user-images.githubusercontent.com/57003922/83177196-033d4480-a0f5-11ea-9b77-3682bfedd5fd.png)
> 
> ![54uqsdf](https://user-images.githubusercontent.com/57003922/83177217-09cbbc00-a0f5-11ea-9890-e2cec9cec919.png)
> 
> #### A "Möbius Strip" version
> ![qsdjif45](https://user-images.githubusercontent.com/57003922/83177253-1cde8c00-a0f5-11ea-8618-f5ff3261a053.png)
> 
> ![asjgg](https://user-images.githubusercontent.com/57003922/83177267-22d46d00-a0f5-11ea-91d2-f34511a8036b.png)

first perfect, imho

**Comment by cristianovitorino** [comment] 2020-05-28 18:13
I need to tweak the Möbius one, It's not accurate.

**Comment by cristianovitorino** [comment] 2020-05-28 18:45
Correct Möbius version.

![asdf745](https://user-images.githubusercontent.com/57003922/83180714-3930f780-a0fa-11ea-81e1-c545dfef8380.png)

![asfg856](https://user-images.githubusercontent.com/57003922/83180724-3c2be800-a0fa-11ea-95d7-620a251df22b.png)

**Comment by cristianovitorino** [comment] 2020-05-28 18:48
@Antoine-Derouin What do you think? How should we proceed?

**Comment by rejedai** [comment] 2020-05-28 18:48
it seems not bad, but at the same time there is a feeling that something is missing.  possibly due to the fact that there are fewer dark areas.

**Comment by stripedpajamas** [comment] 2020-05-28 19:00
I do love the direction the moebius version is going (the asymmetry is appealing); the "Current winner, improved, polished" is also still looking fine to me.

**Comment by Rowisi** [comment] 2020-05-28 19:24
are we allowed to make the same official VScode logo but with different color?

**Comment by cristianovitorino** [comment] 2020-05-28 19:26
> are we allowed to make the same official VScode logo but with different color?

If you can get a written permission for their legal team, yes. Otherwise, no.

**Comment by cristianovitorino** [comment] 2020-05-28 19:32
@Antoine-Derouin This an "inverted" accented shadow of the Möbius version. Do you have any more suggestions or ideas? If you're happy with the latest iterations, should we put this to a final vote?

![asd35asdf](https://user-images.githubusercontent.com/57003922/83185019-b8292e80-a100-11ea-9f36-9ec63f840863.png)

![asdf895](https://user-images.githubusercontent.com/57003922/83185027-bbbcb580-a100-11ea-99db-512502283f2b.png)

**Comment by Antoine-Derouin** [comment] 2020-05-28 19:33
@cristianovitorino I had a preference for the visual contrast of the verse with two folds.
The last proposal is a bit "geolocation", isn't it?
Anyway I really like what you've done with the Möbius idea!

**Comment by cristianovitorino** [comment] 2020-05-28 19:37
> @cristianovitorino I had a preference for the visual contrast of the verse with two folds.
> The last proposal is a bit "geolocation", isn't it?
> Anyway I really like what you've done with the Möbius idea!

@Antoine-Derouin But the "double fold" version is not a real Möbius, just letting you know. Only the last two corrected versions are.

How should we proceed? Final Vote? Thoughts? New ideas?

**Comment by Antoine-Derouin** [comment] 2020-05-28 19:41
It's true.
Can you test with a larger area of shadow, please?
It's the gradient color I find visually pleasing.

Or maybe place the fold somewhere else?

**Comment by cristianovitorino** [comment] 2020-05-28 19:47
> It's true.
> Can you test with a larger area of shadow, please?
> It's the gradient color I find visually pleasing.
> 
> Or maybe place the fold somewhere else?

Something like this?

![asdfkij45](https://user-images.githubusercontent.com/57003922/83186413-dee86480-a102-11ea-9003-4013bca1ea3b.png)

**Comment by cristianovitorino** [comment] 2020-05-28 19:51
@Antoine-Derouin Perhaps darker, longer shadows is what you mean?

![asdf845](https://user-images.githubusercontent.com/57003922/83186830-81084c80-a103-11ea-8c54-8b6732a048f7.png)

**Comment by Antoine-Derouin** [comment] 2020-05-28 19:55
@cristianovitorino That's very good! I'll let the others have their say.

**Comment by cristianovitorino** [comment] 2020-05-28 21:15
# Last revision. Final vote. Please choose wisely.

Any further work from me will be just polish if needed.

1 = :heart: 
2 = :+1: 
3 = :rocket: 
4 = :tada: 
5 = :smile: 

![1](https://user-images.githubusercontent.com/57003922/83193971-43f58780-a10e-11ea-913b-eeafc09a69e8.png)
![2](https://user-images.githubusercontent.com/57003922/83193972-4657e180-a10e-11ea-84bc-3dfa609a7dca.png)
![3](https://user-images.githubusercontent.com/57003922/83193979-4821a500-a10e-11ea-903a-0c6d75531b00.png)
![4](https://user-images.githubusercontent.com/57003922/83193986-4a83ff00-a10e-11ea-8283-c19674196778.png)
![5](https://user-images.githubusercontent.com/57003922/83193993-4c4dc280-a10e-11ea-81cf-688fc0a8d1f1.png)

**Comment by stripedpajamas** [comment] 2020-06-08 16:17
It looks like 2 is the winner 👍 

PRs welcome to transition over to the new icon -- there are a couple variations that would need to be created (I think they are all in https://github.com/VSCodium/vscodium/tree/master/src).

Thanks everyone for sticking with this thread!

**Comment by cristianovitorino** [comment] 2020-06-08 16:24
@stripedpajamas Gonna work on that as soon as possible.

**Comment by cristianovitorino** [comment] 2020-06-09 01:08
@stripedpajamas [The PR is ready for review](https://github.com/VSCodium/vscodium/pull/413).

**Comment by SimonBrazell** [comment] 2020-07-15 02:17
I know I'm far too late on this, but I only just discovered VSCodium... anyway although I like the new icon design that was chosen I must say it doesn't look at all like a codium algae anymore, if that was the idea behind it I really think it's missed the mark. Just my 2 cents... 🙂

**Comment by stripedpajamas** [comment] 2020-07-28 23:40
#413 merged; closing this issue. Thanks again @estatra

**Closed by stripedpajamas** 2020-07-28 23:40 UTC

**Comment by rdewolff** [comment] 2020-08-15 09:34
What a shock to see that new logo. I know colors and styles are very personal, but that's 180 degrees turn 🙄

**Comment by sdaitzman** [comment] 2020-08-18 01:53
Any openness to revising this?

**Comment by estatra** [comment] 2020-08-18 05:20
> What a shock to see that new logo. I know colors and styles are very personal, but that's 180 degrees turn :roll_eyes: 

---

> Any openness to revising this?

The proposal was up for 8 months with votes open and a large number of iterations.

Any thought, answer, comment or decision on your questions is up to the project owner. 

I don't particularly see any problem in suggesting a better design or improvement on the current one, but that window is unfortunately gone now after 8 months of iterations and discussion, as the process is finished and a new VSCodium version with the new logo is already released, currently in the process of minor bug fixing on the main icon paddings.

**Comment by SimonBrazell** [comment] 2020-08-18 05:33
@estatra I think the new logo is a definite improvement over the old one, and I appreciate your effort on this. 

If I was around to vote on this I would have gone for the runner up (4) in [this comment](https://github.com/VSCodium/vscodium/issues/313#issuecomment-583909540), as it looks much more like a codium while still in keeping with the vscode logo design. But that's just me and as I said, I know I'm too late on this. 

Anyway I think it's a great addition to the project. Cheers!

**Comment by estatra** [comment] 2020-08-18 06:23
> If I was around to vote on this I would have gone for the runner up (4) in [this comment] [...]

Yeah a few people really liked that one, I'm a bit ashamed of it as I think a did a poor job, if it went through to later phases I would have polished it a lot more.

I appreciate the feedback, thanks : )

**Comment by SimonBrazell** [comment] 2020-08-18 06:31
> I'm a bit ashamed of it as I think a did a poor job

We are often our own worst critic 🙂  I think it looks cool as is, like an abstract representation of algae!

Hard to get feedback on something like this, other than an issue like this there is no other channel, and obviously people will only come looking for it once it's already changed...

**Comment by CyberDuck79** [comment] 2020-08-20 08:24
Yep it's clear that people will go here once it's already changed as we look at issues when we have... issues. It's good sign that people don't look at it ^^.
I don't understand what was the problem with the older icon (that's why I didn't look here) but I find the new one a little weird, it feel like it is not proportional (in height) in comparison with my other icons on Mac OS, but maybe I will get accustomed.
The style is OK, it is difficult to satisfy everyone anyway ^^' good job !.

**Comment by piotrekzurek** [comment] 2020-08-20 14:06
:) I liked the previous icon better. The new one isn't bad either and I will just get used to it. But it could use some slight improvement - if I may suggest please give it just a bit more contour so it's stands out from the background (especially when on a grayish one, please compare how easier on the eyes is that Element's icon in the picture, also greenish).
<img width="74" alt="Zrzut ekranu 2020-08-20 o 16 05 12" src="https://user-images.githubusercontent.com/43188116/90781579-f482ba00-e2fe-11ea-9653-aaad46032ae2.png">
All in all a good icon.

**Comment by estatra** [comment] 2020-08-20 21:20
@CyberDuck79

> Maybe change it directly by a temporary "prototype icon" (the first proposal was not horrible) could have pushed more people to get there before working 8 months with a very small number of people.

Not a very small number of people. The issue was displayed on the first page for months. Perhaps you mean interest? As people stumbling upon this when trying to solve bugs is not the same behavior as seeing the proposal on the front page for months and choosing not to participate, or not caring, that's an issue on the interest in the subject. Requests for a complete revamp or new proposals after 8 months is not doable, but as I said before, I don't mind new proposals at all, It's just that I felt the VSCodium could use some more modernization on the icon and did a formal proposal, was discussed, accepted and voted upon, it's just not up to me at this point as the process is finished on my part.

And the title was changed several times to reflect the development cycle of the new icon. It started as a normal and formal proposal, was well received and evolved from there.

> I just find the new one a little weird, it feel like it is not proportional (in height) in comparison with my other icons on Mac OS, but maybe it's me as it look like you already work on that subject.

It's a bug that is already being working on. As I don't use macOS myself, I'm waiting for the project owner to give me some help when he's available to apply the fix.

**Comment by estatra** [comment] 2020-08-20 22:06
@piotrekzurek 

> :) I liked the previous icon better. The new one isn't bad either and I will just get used to it. 

Humans always get grumpy with changes, me included haha. Give it time and it will grow on you : ) I remember when Instagram last changed their logo, oh the horrors on the internet haha I doubt anyone today even remembers that that was even a thing.

> But it could use some slight improvement - if I may suggest please give it just a bit more contour so it's stands out from the background (especially when on a grayish one, please compare how easier on the eyes is that Element's icon in the picture, also greenish).
> <img alt="Zrzut ekranu 2020-08-20 o 16 05 12" width="74" src="https://user-images.githubusercontent.com/43188116/90781579-f482ba00-e2fe-11ea-9653-aaad46032ae2.png">

Element's (Riot's ) new redesign is actually flat. You might be using a custom, third party icon theme?

![element-icon](https://user-images.githubusercontent.com/57003922/90830454-15a3d480-e318-11ea-98d3-3e5580b06950.png)

> All in all a good icon.

Thanks!

**Comment by CyberDuck79** [comment] 2020-08-20 22:11
Oh sorry first page of what ? 😮
That's not lack of interest it's ignorance.
There nothing on my startup page.
The change logs ? I was thinking it was the same as vs code.
But if you mean GitHub this is what I talk about, a very few people (I mean users) look at it and participate if they don't have issues about the code mainly.
I just predict that there will be more people on that subject now the that the icon is effectively changed and the subject is closed 😅 so it's pity but maybe I'm wrong.

**Comment by estatra** [comment] 2020-08-20 22:29
> Oh sorry first page of what ? 

GitHub Issues page for this project.

> That's not lack of interest it's ignorance.

Not at all. There is no discussion forum for this project, the issue was up and visible for months.

> There nothing on my startup page.

Of course not, it was a 8 month process, it wouldn't last forever on the first page.

> The change logs ? I was thinking it was the same as vs code.

Nothing to do with logs.

> But if you mean GitHub this is what I talk about, a very few people (I mean users) look at it and participate if they don't have issues about the code mainly.

As I said, there is no community forum for VSCodium. Issues and changes are discussed here, and it was visible for months on the first page, it's not ignorance, it's interest.

> I just predict that there will be more people on that subject now the that the icon is effectively changed and the subject is closed  so it's pity but maybe I'm wrong.

I think you're indeed are mistaken. Of course people will take notice now that the new icon is up, completely normal, it's not a project part of a business with a marketing campaign to spam people "Hey, we're discussing changing the logo". Or to spam people's emails.

All issues are discussed on the project's GitHub issue section.

Again, as I said before, it was a long process, parts interested chipped in, it evolved and got to a conclusion, it's up to the project owner and the community to do whetever it is necessary from now on, my contribution is done. 

And I'm still helping out solving the issues relating to the new icon, people don't need to worry about that, on PR is up and done, and another is in the making.
