### ISSUE TITLE
Branding options

### ISSUE THREAD

**Issue by Eviepayne** [VSCodium/vscodium#659] opened 2021-03-02 13:48 UTC
I was in favor of the switch to the green mobius icon. It was far cleaner and easier to identify in contrast to other icons.
I get that changing branding a lot is annoying, could it be possible to make it an optional thing?

**Comment by tobiashuttinger** [comment] 2021-03-28 16:02
I agree with @Eviepayne. The old logo was clean, aesthetically pleasing and easy to identify. 
The new one - not so much. The form is too complex for small display sizes and combined with the blue color (at least in the mac os version) the icon completely disappears between other icons.

**Comment by daiyam** [comment] 2021-03-28 18:03
Closing as duplicate of #636.
Please read the comment @stripedpajamas in https://github.com/VSCodium/vscodium/issues/636#issuecomment-775294497

**Closed by daiyam** 2021-03-28 18:03 UTC
Labels: bug

**Comment by Eviepayne** [comment] 2021-03-28 18:26
> Closing as duplicate of #636.
> Please read the comment of @stripedpajamas in [#636 (comment)](https://github.com/VSCodium/vscodium/issues/636#issuecomment-775294497)

This is not a duplicate

> Could it be possible to make it an optional thing?

I'm not proposing we change it back. I'm proposing we make it optional.

**Comment by daiyam** [comment] 2021-03-28 19:43
@Eviepayne Making it optional is next to impossible.

You can build the app with any icon you want or change directly the icon in the exe.
- Windows: https://www.howtogeek.com/75983/stupid-geek-tricks-how-to-modify-the-icon-of-an-.exe-file/
- macOS: https://appleinsider.com/articles/21/01/06/how-to-change-app-icons-on-macos
- Linux: https://www.maketecheasier.com/change-application-icon-from-terminal-linux/

In any case, any update can revert to the official icon.
