### ISSUE TITLE
Codium from Snap still exhibits issues with Fonts showing up as rectangles!

### ISSUE THREAD

**Issue by tomit4** [VSCodium/vscodium#767] opened 2021-07-19 08:26 UTC
I've had VS Codium from Snap for a while.  Issues persist with Codium from flatpack and others, while snap works just fine except for the fact that when I try and save or open from the GUI file manager system, it comes up as a bunch of unreadable rectangles.  I've tried to troubleshoot this issue from past posts about the same issue a few months ago, but have come up short.  I've already tried emptying the snap font cache as well as the local font cache to no avail.  Any help regarding this issue would be appreciated, as it seems certain Linux Distributions and package managers present problems that are unique to Codium that do not occur with VS Code.  I run on Manjaro XFCE btw.

**Comment by daiyam** [comment] 2021-07-19 08:37
@tomit4 Which version of Manjaro?

**Comment by bkis** [comment] 2021-07-24 10:09
Maybe #426 is of interest, here.

**Comment by daiyam** [comment] 2021-07-24 10:50
I'm closing it since it's a duplicate of #426

**Closed by daiyam** 2021-07-24 10:50 UTC

**Comment by tomit4** [comment] 2021-08-09 03:14
@daiyam Sorry for the late reply, I have since simply gone with the VSCode binaries from the AUR, but I am running XFCE VSCode.  I have determined that this is probably an issue with Snap rather than your official repositories, but if you anyone has contact with the Snap team, you may want to make them aware of this issue on Manjaro XFCE, that's what I'm running and it doesn't play well with the default fonts for some reason even though it shows as having those fonts in my system...I'm not sure exactly why but I found some forums from about 8 months ago that complain of the same issues...sorry I've forgotten where those are now, but it might be something worth looking into.....
