### ISSUE TITLE
VSIX-installed extensions all install as "EditorConfig for VS Code"

### ISSUE THREAD

**Issue by badocelot** [VSCodium/vscodium#434] opened 2020-06-21 18:16 UTC
**Describe the bug**

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install an extension from VSIX, either through the GUI or command-line tool
2. Restart the software
3. Go to list of installed extensions; notice that the extension you just installed is not listed, but 'EditorConfig for VS Code' is
4. Select 'EditorConfig for VS Code'; notice that the description is for the extension you installed.

**Expected behavior**
Once installed, an extension will appear in the list of installed extensions and remain useful after closing and reopening the software.

**Desktop (please complete the following information):**
 - OS: Ubuntu MATE 20.04
 - Architecture: x64
 - Version: 1.46.1

**Additional context**
If multiple extensions are installed through VSIX, only one will be preserved, presumably because it thinks they are all 'EditorConfig for VS Code' and thus the others are superfluous. This apprears to favor the extension whose folder name in ~/.vscode-oss/extensions sorts first alphabetically; all other extensions will be deleted.

I found this bug after compiling and installing the [Firefox Theme](https://github.com/firefox-theme/visual-studio-code), [Hg](https://github.com/mrcrowl/vscode-hg), and [Ignore files](https://github.com/ldez/vscode-language-ignore) extensions, which are not available in Open VSX. Upon restarting, only the Firefox Theme extension was still available, and was listed as 'EditorConfig for VS Code'. I checked the ~/.vscode-oss/extensions directory and found the others had been deleted.

I've tried installing from the official VSIX files, downloaded from the Visual Studio Marketplace website, but the same thing happened. The only workaround I've found is to copy the extension folders into the builtin extensions folder, so that they at least can't be deleted automatically.

I have tried the same thing installing from a freshly-built VS Code (that is, Code OSS - Dev) 1.46.1 and it worked as expected, so this seems to be unique to VSCodium.

**Comment by Peter-FB** [comment] 2020-06-22 07:01
I have the exact same problem on Windows 8.1, VSCodium version 1.46.1 x64.

**Comment by TensorTom** [comment] 2020-06-22 21:44
This happens to me on Linux but rather than the extension I intended to install, EditorConfig has its own description:

> 
This plugin attempts to override user/workspace settings with settings found in .editorconfig files. No additional or vscode-specific files are required. As with any EditorConfig plugin, if root=true is not specified, EditorConfig will continue to look for an .editorconfig file outside of the project.

I don't believe the intended extension was installed at all. I attempted:

`code --install-extension openfl.lime-vscode-extension-1.4.0.vsix`

**Comment by Moxie1776** [comment] 2020-06-24 14:10
same problem here. I am installing it from arch linux.

**Comment by theArianit** [comment] 2020-06-26 20:38
same problem here, linux mint 19.3

**Comment by mpaunovic** [comment] 2020-06-28 10:00
Same here, LM 19.3.

**Comment by gasinvein** [comment] 2020-06-29 16:16
Seems like a different VS Code OSS build with Open VSX gallery is having the same issue. I guess it's caused by `__metadata` being added to `package.json` of installed extension, which is invalid for Open VSX gallery.

**Comment by br3ndonland** [comment] 2020-07-01 17:11
Same issue here, macOS Catalina 10.15.5 and VSCodium 1.46.1.

In my case, I installed [shell-format](https://github.com/foxundermoon/vs-shell-format) from VSIX, because it is not available on open-vsx.org. The extension installs successfully. After a restart of VSCodium, I see the correct version number and details page from the extension I installed, but the title and description show up as EditorConfig for VS Code `editorconfig.editorconfig` and "EditorConfig Support for Visual Studio Code".

**Comment by TobiasDev** [comment] 2020-07-02 09:36
Not sure if anyone else has seen this as well, but since the latest release of Codium (does not happen in VS Code), I also can't search for new extensions, anything that has been updated recently or a new release doesn't show up.

I noticed this as I released my own extension and that can't be found in Codium, but in Code without any problems.

**Comment by br3ndonland** [comment] 2020-07-02 13:58
> UPDATE: I noticed in the last release that it seems to have changed the extensions store to this one: https://open-vsx.org/, does that mean that support for original VS Code extensions is no longer supported?

@TobiasDev see the [docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) and VSCodium/vscodium#404.

**Comment by TobiasDev** [comment] 2020-07-02 14:22
Yeah, just saw that. Added my created theme to that one for that reason. :)

It will take some time working without some of the extensions I use daily but I do prefer this solution to handle the license issues. :)

**Comment by notpushkin** [comment] 2020-07-03 13:40
I've hacked together a [small script](https://gist.github.com/notpushkin/7fba4e2035f2c25bb04dfb9fb51a30c5) that reuploads an extension from VS Marketplace to Open VSC, which can then be installed correctly in Codium. I'm not sure if it's (((ethical))) to do so (and please don't upload proprietary extensions this way, it's probably illegal) but otherwise it's a working solution.

**Comment by HitLuca** [comment] 2020-07-07 08:26
Having the same issue here

MacOs 10.15.5
Vscodium 1.46.1

I tried to install [importmagic](https://marketplace.visualstudio.com/items?itemName=brainfit.vscode-importmagic#overview) and it works as expected, but on the extensions page it shows as editorconfig and it asks me to update to a different version. Upon updating, the extension is replaced with editorconfig

**Comment by spoenemann** [comment] 2020-07-15 10:13
The cause of this problem was [openvsx](https://github.com/eclipse/openvsx) not respecting the "ExtensionName" filter that is used by VS Code to query the metadata of extensions installed via VSIX. This is fixed now, please verify.

**Comment by HitLuca** [comment] 2020-07-15 11:52
I can confirm that after reinstalling my local copy of the importmagic extension, it is correctly recognized and no wrong updates are found for it.
Could be related, but I am unable to find certain extensions in vscodium anymore (can find them in vscode), see [edit csv](https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv) and [importmagic](https://marketplace.visualstudio.com/items?itemName=brainfit.vscode-importmagic) for two examples

**Comment by spoenemann** [comment] 2020-07-15 12:17
> I am unable to find certain extensions in vscodium anymore

See https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

**Comment by HitLuca** [comment] 2020-07-15 12:19
Perfect, thank you very much, issue solved for me then

**Comment by br3ndonland** [comment] 2020-07-15 15:06
@spoenemann fixed for me, thank you!

**Comment by badocelot** [comment] 2020-07-17 15:39
Seems to be fixed.

**Closed** 2020-07-22 18:12 UTC
Labels: bug
