### ISSUE TITLE
VSCodium wayland

### ISSUE THREAD

**Issue by RosGtHub** [VSCodium/vscodium#1593] opened 2023-08-06 01:37 UTC
**Describe the bug**
When i maximize the application it doesn't fully cover the screen
**Screenshots**
![Screenshot from 2023-08-06 03-25-20](https://github.com/VSCodium/vscodium/assets/89165766/bd3d348e-bf7f-4062-9e90-dd9e338d1ef6)

**Desktop (please complete the following information):**
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.4.7-arch1-3
Desktop:         GNOME
Display Server:  wayland
Sandboxed: no
App Manager: aur

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600G with Radeon Graphics
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.4 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.4.7-arch1-3)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.4
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.4
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.4
Vulkan Version:  1.3.255
Vulkan Drivers:  AMD Radeon RX 6700 XT (RADV NAVI22) (1.3.246)

**Comment by Lime-Parallelogram** [comment] 2023-08-06 08:34
I think I might be having a related issue. I'm using the Flatpak version (I know its not officially supported so I'm reluctant to open a separate issue here) but in the latest release (released on 4th August on Flathub)  my window decorations have disappeared. You cannot resize or move the window with the mouse.

I'm using Fedora 38 with a Gnome 44.3. Have rolled back to the previous version and everything is working perfectly.

![Screenshot from 2023-08-06 10-26-41](https://github.com/VSCodium/vscodium/assets/26200360/fb268e03-2110-4b62-b96c-cf27789138fb)

**Comment by Fxsch** [comment] 2023-09-06 05:37
An issue was opened there but they just gave a workaround (running it through the terminal and adding `--enable-features=WaylandWindowDecorations`) and closed it. The issue wasn't actually fixed. But since that workaround is an argument given to VSCodium itself, it might have to be fixed here.

**Comment by wanesty** [comment] 2023-10-26 23:54
arch kde wayland, `vscodium-bin-marketplace` from the aur:

crashed when maximizing the wayland window, issue is not present with the xwayland .desktop

> running it through the terminal and adding `--enable-features=WaylandWindowDecorations`

does fix the wayland .desktop !

---
said .desktop files for reference:

<details>
  <summary><code>codium.desktop</code></summary>

```properties
[Desktop Entry]
Name=VSCodium
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/bin/codium --unity-launch %F
Icon=vscodium
Type=Application
StartupNotify=false
StartupWMClass=VSCodium
Categories=Utility;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/bin/codium --new-window %F
Icon=vscodium
```
</details>
<details>
  <summary><code>codium-wayland.desktop</code></summary>

```properties
[Desktop Entry]
Name=VSCodium - Wayland
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/bin/codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland --unity-launch %F
Icon=vscodium
Type=Application
StartupNotify=false
StartupWMClass=codium-url-handler
Categories=Utility;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/bin/codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland --new-window %F
Icon=vscodium
```
- so adding `--enable-features=WaylandWindowDecorations` as an argument to the exec line does fix it.  
</details>

**Comment by noonsleeper** [comment] 2023-10-28 13:31
@wanesty you need these two parameters only 

```bash
codium --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
```

Force platform (`--ozone-platform=wayland`) doesn't work well, I mean platform autodetection either works well, but at least is more stable.

**Comment by wanesty** [comment] 2023-10-28 17:32
> Force platform (`--ozone-platform=wayland`) doesn't work well, I mean platform autodetection either works well, but at least is more stable.

does make it use wayland but it's not fixing the crashes on fullscreen :/
ty tho :heart: :3

**Comment by daiyam** [comment] 2023-10-30 14:53
Feel free to make any PR to facilitate the integration of Wayland!

**Comment by noonsleeper** [comment] 2024-02-22 22:13
> does make it use wayland but it's not fixing the crashes on fullscreen :/ ty tho ❤️ :3

Are you using an nvidia card? If is that the case, the latest version of flatpak disable gpu accel for nvidia under wayland.
Can you try that?

**Comment by wanesty** [comment] 2024-02-23 16:20
> Are you using an nvidia card?

nope, amd RX6700 with mesa drivers, **it's now fixed** for me when reproducing the thing that was causing issue (fullscreen on some files with nu highlighter with wayland).

**Comment by RosGtHub** [comment] 2024-03-29 18:05
It was fixed!

**Closed** 2024-03-29 18:04 UTC
Labels: bug

**Comment by WECLEYArtz** [comment] 2024-04-02 19:53
> It was fixed!

well not for me.
![image](https://github.com/VSCodium/vscodium/assets/80406334/a7f87163-cd93-4915-8633-0ddce9974a0d)

Debian 12 
Plasma 5.27.5

**Comment by WECLEYArtz** [comment] 2024-04-02 20:04
> > It was fixed!
> 
> well not for me. ![image](https://private-user-images.githubusercontent.com/80406334/318942813-a7f87163-cd93-4915-8633-0ddce9974a0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwODc5MDIsIm5iZiI6MTcxMjA4NzYwMiwicGF0aCI6Ii84MDQwNjMzNC8zMTg5NDI4MTMtYTdmODcxNjMtY2Q5My00OTE1LTg2MzMtMGRkY2U5OTc0YTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE5NTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhOGIwOGE5ZjE4YWEwMjVlN2I1NDRjYmYwZGIyY2RjNDBjODg4YmJkYWU4NTVlNjYzZTRmMDg2MDI5ZDk0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vweSNkKqv8t6h6vqmWuIAY4H1nz2Ey4uIC0sgZFsDx4)
> 
> Debian 12 Plasma 5.27.5

weirdly it got fixed after i installed an extension and restarted it.
