### ISSUE TITLE
CentOS Linux release 7.8.2003  - /lib64/libstdc++.so.6: version CXXABI_1.3.9 not found - codium v 1.49.2

### ISSUE THREAD

**Issue by gianricod** [VSCodium/vscodium#521] opened 2020-09-28 09:19 UTC
Hello
After upgrading to 1.49.2 i run into the issue below:

`The terminal process failed to launch: A native exception occurred during launch (/lib64/libstdc++.so.6: version CXXABI_1.3.9 not found`

Downgraded to 1.49.1 to have a working version.

Is this solvable or my OS version is not supported anymore?

**Comment by GitMensch** [comment] 2020-09-29 05:44
Same here. Some extensions seem to not work correctly any more and terminal is broken.

The reason is "obviously" that this VSCodium version was built against libstdc++ 6 while `yum info libstdc++` shows

~~~
Installed Packages
Name        : libstdc++
Arch        : x86_64
Version     : 4.8.5
Release     : 39.el7
Size        : 1.0 M
Repo        : installed
From repo   : base
~~~

I _guess_ you're using the rpm option provided by paulcarroty, I _think_ this is related to his build environment, see https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/44

**Comment by calvellido** [comment] 2020-09-30 07:41
Uhmm, it also happened to me in a Linux Mint OS (`1.49.1` working great):

```
> cat /etc/os-release
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial
```

```
> apt version libstdc++6
5.4.0-6ubuntu1~16.04.125.4.0-6ubuntu1~16.04.12
```

**Comment by calvellido** [comment] 2020-10-07 11:13
What I did in my Ubuntu based system to stay up to date with VSCodium  is to update my `libstdc++` version and related libraries through the Ubuntu Toolchain repo and packages:

https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

**Comment by GitMensch** [comment] 2020-10-07 12:25
The issue is solved for me with 1.49.3 and `yum update`. @gianricod I guess it is the same for you and we can close this issue?

**Comment by eakst7** [comment] 2020-10-07 12:48
I still have the same problem with 1.49.3 on RHEL 7.8.

![Selection_128](https://user-images.githubusercontent.com/16217243/95332708-cee34d00-0879-11eb-9f0c-e24dfcc5d143.png)

**Comment by gianricod** [comment] 2020-10-07 13:21
Same issue for me too

FYI:
[gianrico@gianrico-dev~]$ strings /lib64/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1

I do not know where to find an official  libstdc++ with CXXABI_1.3.9  for centos 7 and i do not want to mess things up with the packages from unsupported repositories

**Comment by GitMensch** [comment] 2020-10-07 14:52
... nice to see some updates ... so yes, didn't looked well enough it is still happening here, too :-(

**Comment by P-N-L** [comment] 2020-10-08 12:07
Alternatively (and forgive me if I misunderstand how AppImages are typically used), could whichever version of libstdc++ gets used to build be packaged into the AppImage itself? My understanding is that as long as the kernel understands the calls made from the image, all dependencies can (and should) be included for maximum portability.

**Comment by dimkr** [comment] 2020-10-09 07:05
I think it's because CI/CD moved to GitHub. The official builds used to run on Ubuntu 14.04, but now they run on latest, which forces the Codium user to have an up to date distro:

```
jobs:
  linux:
    runs-on: ubuntu-latest
```

**Comment by stripedpajamas** [comment] 2020-10-09 14:08
I've just recently switched to containers in the latest build, which is using ubuntu 14.04. So once I get 1.50.0 releases out you all can see if it's fixed.

**Comment by stripedpajamas** [comment] 2020-10-09 18:15
Releases are available; can you all try it out? Snap release might be delayed a bit, as that is maintained separately. And also this release doesn't include an AppImage yet (#532).

**Comment by eakst7** [comment] 2020-10-09 18:21
1.50.0 works for me.  Thanks for the fix!

**Comment by gianricod** [comment] 2020-10-10 07:02
thank you 
1.50 OK

**Closed** 2020-10-10 07:03 UTC

**Comment by dimkr** [comment] 2020-10-10 07:16
@stripedpajamas The problem was fixed for x64, but ARM builds are done on Debian Buster (2019?) now, instead of Ubuntu 14.04. Microsoft chose to ignore old distros on ARM, and Codium can win extra market share if it's more compatible. (Although the exclusive feature of ARM builds for the latest version, is no longer exclusive :confused: ).

**Comment by GitMensch** [comment] 2021-08-23 20:16
Does Codium 1.59.1 now work on ARM 32-bit and old CentOS now?

Note: for 1.60 vscode switched compilation including bundling a static built libcxx with https://github.com/microsoft/vscode/pull/129360/commits, do we need any adjustments for those commits?
