### ISSUE TITLE
AppImage Crashes on open dialog

### ISSUE THREAD

**Issue by rpangrazio** [VSCodium/vscodium#330] opened 2020-02-14 13:09 UTC
When using the AppImage, VSCromium opens fine, but then once i go to open a folder it crashes. Here is the console output

libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: vmwgfx
Warning: 'sandbox' is not in the list of known options, but still passed to Elec
tron/Chromium.
[main 2020-02-14T13:04:52.617Z] update#setState idle
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Error creating proxy: Unknown or unsupported transport “disabled” for address “d
isabled:” (g-io-error-quark, 13)

(codium:106554): Gtk-WARNING **: 07:04:57.477: Could not find the icon 'user-hom
e-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(codium:106554): Gtk-WARNING **: 07:04:57.481: Could not load a pixbuf from /org
/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertio
n failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/imag
e-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)

OS Information:
Ubuntu 18.04 server inside VMWare VM
uname -a:
Linux bionic 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Other things to note:
I run CDE as a desktop UI.

I have tried both 1.42.0 and 1.42.1

**Comment by srevinsaju** [comment] 2020-09-22 11:36
Reproducible on Arch Linux

**Comment by lvarin** [comment] 2020-10-07 06:18
Similar, if not the same:

```
[main 2020-10-07T06:15:32.521Z] update#checkForUpdates, state =  idle
[main 2020-10-07T06:15:32.521Z] update#setState checking for updates
[main 2020-10-07T06:15:32.523Z] update#setState idle
[main 2020-10-07T06:15:53.866Z] menubarService#updateMenubar 1
[main 2020-10-07T06:15:54.818Z] menubarService#updateMenubar 1
[main 2020-10-07T06:15:57.011Z] menubar#runActionInRenderer { type: 'commandId', commandId: 'workbench.action.files.openFolder' }
[22805:1007/091557.019728:INFO:CONSOLE(1705)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.files.openFolder", source: file:///var/lib/snapd/snap/codium/83/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js (1705)
(codium:22805): Gtk-WARNING **: 09:15:57.064: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
http://: Invalid host name.
Unexpected crash report id length
Failed to get crash dump id.
Report Id:
```

OS Information:
Centos 7
Using the codium snap

**Comment by GitMensch** [comment] 2021-03-02 20:55
@probonopd Do you have some insights / ideas as the author of https://github.com/AppImage/pkg2appimage/blob/master/recipes/VSCodium.yml?

**Comment by probonopd** [comment] 2021-03-04 18:01
Sorry I don't have the time to look deeper into this at the moment but maybe https://github.com/AppImage/AppImageKit/issues/906#issuecomment-453840777 can provide some helpful hints. It's just a guess.

Please retest with https://github.com/AppImage/pkg2appimage/blob/master/recipes/VSCodium.yml on Ubuntu xenial and let me know whether it is working there. Thanks!

**Comment by Moltkex** [comment] 2021-04-03 02:31
This bug is still present in latest VSCodium-1.55.0-1617289089.glibc2.16-x86_64.AppImage. Tested in Debian Testing/Bullseye.

**Comment by Moltkex** [comment] 2021-04-09 23:03
I tried VSCodium Appimage in openSUSE Leap 15.2 and this problem doesn't occur there. I was able to open a file and a folder as well without it crashing like it did in Bullseye. 

Here's the appimage info:

**Versión:** 1.55.0
**CheckSum:** c185983a683d14c396952dd432459097bc7f757f
**Date**: 2021-04-01T14:57:53.176Z
**Electron**: 11.3.0
**Chrome**: 87.0.4280.141
**Node.js**: 12.18.3
**V8**: 8.7.220.31-electron.0
**OS**: Linux x64 5.3.18-lp152.19-default

**Comment by pushqrdx** [comment] 2021-05-31 19:14
happens with latest on Debian for me too...

**Comment by daiyam** [comment] 2021-05-31 23:25
I don't have the issue on Ubuntu 19.10 but I do get the issue on Arch Linux.

**Comment by daiyam** [comment] 2021-05-31 23:48
@Moltkex @pushqrdx Have you tried https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/159?

**Comment by Moltkex** [comment] 2021-06-01 12:46
> @Moltkex @pushqrdx Have you tried https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/159?

 Did you mean this ``` 
`sudo update-mime-database /usr/share/mime```? Thanks for the tip, but I just did and didn't work. Got the same error message using **VSCodium-1.56.2-1620951495.glibc2.16-x86_64.AppImage**

**Comment by GitMensch** [comment] 2021-06-01 13:01
Yes, that together with

> sudo `gdk-pixbuf-query-loaders --update-cache` (you'd have to check where exactly this resides)

**Comment by Moltkex** [comment] 2021-06-01 16:15
> Yes, that together with
> 
> > sudo `gdk-pixbuf-query-loaders --update-cache` (you'd have to check where exactly this resides)

Just tried and got  **sudo: gdk-pixbuf-query-loaders: command not found** How do I check where it resides?

**Comment by daiyam** [comment] 2021-06-01 16:33
@Moltkex Me too, I'm still getting the error :(
I've asked you because I'm testing on a custom Arch Linux with AwesomeWM (no KDE or Gnome...), so I was wondering if there was a problem with my setup...

**Comment by Moltkex** [comment] 2021-06-01 16:53
> @Moltkex Me too, I'm still getting the error :(
> I've asked you because I'm testing on a custom Arch Linux with AwesomeWM (no KDE or Gnome...), so I was wondering if there was a problem with my setup...

Well, Awesome can be tricky, it's been a while since I last used it and don't have any VM running Arch at the moment, so I've no clue as to what might be the problem in your case, but I installed the **.deb** file in Bullseye, and it works without crashing. Also, like I said in a previous comment, Appimage version 1.55 works fine in openSUSE Leap 15.2 as well as in Tumbleweed, though haven't tried 1.56 there, yet. That being said, the problem seems to be in Bullseye only so far. Will try later in Buster and Neon to do more checking.

**Comment by daiyam** [comment] 2021-06-01 17:18
I don't have the issue with the **.tar.gz**.

**Comment by Moltkex** [comment] 2021-06-03 03:49
VSCodium-1.56.2-1620951495.glibc2.16-x86_64.AppImage works fine in Debian Buster and KDE Neon(Testing). I could open a directory as well as a file without it crashing.

**Comment by daiyam** [comment] 2021-06-04 07:00
@Moltkex Can you test if [VSCodium-1.56.2-1622750561.glibc2.30-x86_64.zip](https://app.box.com/s/ew4qxfvofvpv6a4omn80ryaa7f47xvvt) is working on your systems? It's working on my Arch Linux and on Bullseye.

**Comment by Moltkex** [comment] 2021-06-04 12:22
> @Moltkex Can you test if [VSCodium-1.56.2-1622750561.glibc2.30-x86_64.zip](https://app.box.com/s/ew4qxfvofvpv6a4omn80ryaa7f47xvvt) is working on your systems? It's working on my Arch Linux and on Bullseye.

Yeah, no problem. I will and report back my findings.

**Comment by Moltkex** [comment] 2021-06-04 13:52
@daiyam Just tried VSCodium-1.56.2-1622750561.glibc2.30-x86_64 and opening a file and folder works in KDE Neon(Testing), but it doesn't in Buster. VSCodium froze and got these messages in terminal:
```bash
[main 2021-06-04T13:15:38.735Z] [uncaught exception in main]: Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node)
[main 2021-06-04T13:15:38.741Z] Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:4:694)
    at Object.<anonymous> (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/node_modules.asar/vscode-sqlite3/lib/sqlite3.js:1:77)
    at Module.u._compile (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:4:1311)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:101)
    at r.load (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:4:1719)
    at r.load (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:3:10262)
    at l (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:3:10626)
    at /tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:3:10332
    at r.load (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:4:1736)
    at r.load (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:3:10262)
    at l (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:6831)
    at n (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:9420)
    at /tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:21:31694
    at new Promise (<anonymous>)
    at /tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:21:31674
    at new Promise (<anonymous>)
    at v.doConnect (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:21:31654)
    at v.connect (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:21:31100)
    at new v (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:21:28440)
    at w.doCreate (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:51:9829)
    at /tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:51:8715
    at w.init (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:51:9057)
    at /tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:51:12529
[main 2021-06-04T13:15:44.771Z] update#setState checking for updates
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:4:694)
    at bindings (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/node_modules.asar/bindings/bindings.js:112:48)
    at Object.<anonymous> (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:4:1311)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:101)
    at r.load (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:4:1719)
    at r.load (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:3:10262)
    at l (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:3:10626)
    at /tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:3:10332
    at r.load (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:4:1736)
    at r.load (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:3:10262)
    at l (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:6831)
    at n (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/loader.js:5:9420)
    at L.E (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:30:4530)
    at new Promise (<anonymous>)
    at L (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:30:4510)
    at r._createSpdLogLogger (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:30:5443)
    at new r (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:30:5259)
    at /tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:59:2010
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Z.startup (/tmp/.mount_VSCodie84kGw/usr/share/codium/resources/app/out/vs/code/electron-main/main.js:59:1821) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
```
Looks like some module(s)/dependency(ies) is(are) missing. Have yet to try in openSUSE and Bullseye, will do later and let you know how it went. :smiley:

**Comment by daiyam** [comment] 2021-06-04 15:22
Here the [branch](https://github.com/daiyam/vscodium/tree/fix-appimage) with the changes I've made (it's using the latest version of pkg2appimage).
I've compiled the project under Bullseye since it wasn't working under it. I will recompile it under Ubuntu 18.04 (it's the version used by the github action) and test it on Bullseye...

**Comment by Moltkex** [comment] 2021-06-04 16:13
Just tried VSCodium-1.56.2-1622750561.glibc2.30-x86_64 in Bullseye, and it worked too without crashing. I did see these messages in terminal thought:

```bash
codium: /tmp/.mount_VSCodi1JQfku/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)
codium: /tmp/.mount_VSCodi1JQfku/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libmount.so.1)
/tmp/.mount_VSCodi1JQfku/usr/share/codium/codium: /tmp/.mount_VSCodi1JQfku/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)
/tmp/.mount_VSCodi1JQfku/usr/share/codium/codium: /tmp/.mount_VSCodi1JQfku/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)
/tmp/.mount_VSCodi1JQfku/usr/share/codium/codium: /tmp/.mount_VSCodi1JQfku/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libmount.so.1)
/tmp/.mount_VSCodi1JQfku/usr/share/codium/codium: /tmp/.mount_VSCodi1JQfku/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libmount.so.1)
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
[main 2021-06-04T20:01:12.506Z] update#setState idle
[main 2021-06-04T20:01:26.015Z] file: Refused to load resource /tmp/.mount_VSCodiWkU7QV/usr/share/codium/resources/app/extensions/theme-seti/icons/seti.woff from file: protocol (original URL: file:///tmp/.mount_VSCodiWkU7QV/usr/share/codium/resources/app/extensions/theme-seti/icons/seti.woff)
[main 2021-06-04T20:01:42.586Z] update#setState checking for updates
[main 2021-06-04T20:01:56.972Z] update#setState idle
```

But it worked; was able to open a dir and a file, no crashing.

**Comment by daiyam** [comment] 2021-06-04 22:02
[VSCodium-1.56.2-bionic.zip](https://app.box.com/s/mmk99vut5wad3ehm4acsa0a8bckmqo6q) has been compile under Ubuntu 18.04. It's working with that version, Debian Bullseye and my Arch Linux.

**Comment by daiyam** [comment] 2021-06-13 06:14
The issue should be fixed with the version 1.57.0

**Comment by Moltkex** [comment] 2021-06-15 18:39
> The issue should be fixed with the version 1.57.0

I tried 1.57.0 in Buster, Bullseye, KDE Neon and openSUSE Leap/Tumbleweed. VSCodium didn't crash, though in Buster I got this: 

```bash
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap
```


had to use 


```--no-sandbox``` 

Also, a pop-up window with a "vscodium stop working" or some similar message kept showing up over and over, clicked "wait" to close it and the app eventually started responding again.

**Comment by daiyam** [comment] 2021-06-15 20:03
@Moltkex great!

For the issue on Debian Buster, can you open a new issue since it seems to be different from the current issue. Thx

**Comment by Moltkex** [comment] 2021-06-15 22:19
> @Moltkex great!
> 
> For the issue on Debian Buster, can you open a new issue since it seems to be different from the current issue. Thx

For the **--no-sandbox** issue I think it has to do with the kernel version, I remember reading something about that Kernel 4.19 might cause this, however, VSCodium-1.56.2-1622750561.glibc2.30-x86_64 worked without the **--no-sandbox**, so I don't know. The pop-up window happened in all the systems, should've mentioned that before, sorry about that.

**Comment by daiyam** [comment] 2021-06-16 05:28
For `setuid sandbox`, it seems to be caused by Chromium with solutions like removing the `nosuid` option in the `/etc/fstab` or running with the arguments `--no-sandbox --disable-setuid-sandbox`. It's not specific to VSCodium. [ref1](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/linux/suid_sandbox.md) [ref2](https://authmane512.medium.com/solve-the-suid-sandbox-helper-binary-was-found-but-is-not-configured-correctly-3-solutions-4f1425a9a76c)

I don't think the `vscodium stop working` message should happen. Have you tried without AppImage?

**Comment by Moltkex** [comment] 2021-06-16 14:24
@daiyam 
>I don't think the vscodium stop working message should happen. Have you tried without AppImage?

Actually, I just tried again in Tumbleweed(Gnome in wayland) and worked just fine. This message did show up though

```bash
 Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
``` 


By the way, don't know if relevant, but Leap(awesome-wm) and Buster(Q4OS with TDE) are both VMs running in QEMU. KDE Neon is the testing branch and runs on wayland, it is installed in my machine(bare metal) and so are both Tumbleweed and Bullseye(KDE in X11). I launched VSCodium using portable mode. I will try again later in those to see if the error(s) appear again.

**Comment by daiyam** [comment] 2021-06-16 15:19
@Moltkex I appreciate your tests. Don't worry about VMs, all my Linux and Windows are in a VM... :stuck_out_tongue_winking_eye:

I will close this issue since the original error was fixed.
But by any means, you should open new issues with your findings.

For the `libva` error, you can check out https://github.com/intel/libva/issues/278
For `setuid sandbox`, I will try to test it but I'm busy at the moment.

**Closed by daiyam** 2021-06-16 15:19 UTC
Labels: bug
