### ISSUE TITLE
Can't Install GitHub Pull Request Extension

### ISSUE THREAD

**Issue by MohamedAlFahim** [VSCodium/vscodium#443] opened 2020-07-11 02:46 UTC
**Describe the bug**
When I try to install the [GitHub Pull Request](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) VSIX, it is confused for the Red Hat Java language support extension.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Download and attempt to install the "GitHub Pull Requests and Issues" VSIX file.
2. Quit VSCodium then open VSCodium.
3. See list of installed extensions.
4. See Red Hat extension installed rather than GitHub Pull Request extension.

**Expected behavior**
The GitHub Pull Request extension should be installed rather than the Red Hat extension.

**Screenshots**
<img width="1141" alt="Not The GitHub Extension" src="https://user-images.githubusercontent.com/31521089/87214924-e3995e80-c2e5-11ea-93c2-ba433f05df5f.png">

**Desktop (please complete the following information):**
 - **OS:** Mac OS
 - **Architecture:** x64
 - **Version:** 1.46.1

**Additional context**
I originally mentioned the issue at https://github.com/microsoft/vscode-pull-request-github/issues/1985, but later discovered that this strange issue was unique to VSCodium and didn't occur in VS Code. I also mentioned more VSCodium-specific issues there.

**Comment by dondanhill** [comment] 2020-07-11 06:10
Same happens for me on Windows:

Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-19T10:29:35.942Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by pfeerick** [comment] 2020-07-12 09:27
Perhaps related to using OpenVsx instead of the VSCode Marketplace as the extension gallery?

https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace

**Comment by Rondom** [comment] 2020-07-14 08:46
I am also encountering this. Maybe this bug is a duplicate of or at least related to #434?

**Comment by d4rkf0x** [comment] 2020-07-14 10:27
I am additionally encountering this.

**Comment by spoenemann** [comment] 2020-07-16 09:00
Yes, this is probably a duplicate of #434. It should work now, please verify.

**Comment by MohamedAlFahim** [comment] 2020-07-16 19:52
@spoenemann I updated VSCodium to 1.47.1, installed the Org Mode VSIX file, then reloaded VSCodium, and it worked! (I couldn't install the GitHub Pull Request VSIX because it was not compatible with version 1.47.1)

**Closed** 2020-07-16 19:54 UTC
Labels: bug
