### ISSUE TITLE
VSCodium is set to default application for opening folders on system after fresh Installation

### ISSUE THREAD

**Issue by Carla-Sim** [VSCodium/vscodium#800] opened 2021-08-19 15:40 UTC
**Describe the bug**
After the new installation of VSCodium on Ubuntu all folder are being opened with codium.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [ x ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install new Version of Codium on Ubuntu 20.04 or 18.04
2. All Folder are being opened with codium instead of your default Browser
Example:
3. $ grep inode /usr/share/applications/mimeinfo.cache 
inode/directory=**codium.desktop**;org.gnome.Nautilus.desktop;org.gnome.baobab.desktop;

**Expected behavior**
Codium should not be automatically set to default for opening folders after fresh installation

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu 18.04, 20.04

**Comment by daiyam** [comment] 2021-08-19 16:36
Can you run the command `xdg-mime query default inode/directory`?
From which source have you installed VSCodium?

**Comment by pedroqueiroga** [comment] 2021-08-20 23:09
Two weeks ago I installed microsofts VSCode and the same thing happened. Are you sure this does not happen in VSCode?

**Comment by daiyam** [comment] 2021-08-20 23:24
In `mimeinfo.cache`, `inode/directory=codium.desktop` is just indicating that codium can open a directory. This is fine.
`xdg-mime query default inode/directory` is the command to check which is the default app for opening a directory.

I'm far from an expert on Linux DE so any input are welcome.

**Comment by Carla-Sim** [comment] 2021-08-25 08:21
Thank you for your responses.
Output of xdg-mime, but VSCodium still opens all folders on system.
 **xdg-mime query default inode/directory
 nautilus-folder-handler.desktop**

**Comment by emorozov** [comment] 2021-09-24 10:27
This is because VSCodium.desktop assigns VSCodium as handler for inode/directory.

On ArchLinux I solved this with a pacman hook:
```
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = vscodium*
[Action]
Depends = coreutils
When = PostTransaction
Exec = /usr/bin/sh -c '/usr/bin/sed -i "s/inode\/directory;//" /usr/share/applications/VSCodium.desktop && /usr/bin/update-desktop-database'
```

But I must say this behaviour of default VSCodium is brain damaged and **extremely** annoying. This bug must have higher priority.

**Comment by fsociety3765** [comment] 2021-11-18 04:30
Any update on this being solved with a proper fix?

**Comment by daiyam** [comment] 2022-01-24 17:54
Closing, since this is a duplicate of #409

**Closed by daiyam** 2022-01-24 17:54 UTC
Labels: bug
