### ISSUE TITLE
Can't explore in the open VSX marketplace

### ISSUE THREAD

**Issue by dragonDScript** [VSCodium/vscodium#786] opened 2021-08-04 21:49 UTC
**Describe the bug**
When I try to search an extension, this message appears:
![image](https://user-images.githubusercontent.com/46191980/128259360-3c6c4d55-37a2-4b83-a414-6109f50f36fb.png)
However, if I go to open vsx website, download a .vsix and install it with ctrl+shift+p, it works.

**Note: I saw https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace, will it work with open vsx instead of microsoft's marketplace?**

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Download codium using the appimage
2. Search for any extension or theme
3. See error

**Expected behavior**
Extensions from OpenVSX are visible. I think that OpenVSX should be the default and that microsoft marketplace should be optional.

**Screenshots**
Already included in the top of this issue. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Architecture x64
 - Version 1.58.2

**Comment by daiyam** [comment] 2021-08-04 22:22
Hi, it's a duplicate of #746.

**Closed by daiyam** 2021-08-04 22:22 UTC
Labels: bug

**Comment by dragonDScript** [comment] 2021-08-05 12:01
Oh, I'm sorry.
