### ISSUE TITLE
Shield stats in extensions not showing correctly

### ISSUE THREAD

**Issue by Golotvinov** [VSCodium/vscodium#144] opened 2019-05-03 20:03 UTC
**Describe the bug**
Some image stats / buttons don't show up (load) properly in VSCodium, in the extension page / details to be exact. I believe it's the [Shields.io](https://shields.io/) library.

**Please confirm that this problem is VSCodium-specific**
- [ ✓ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium. - YES. It doesn't happen in MS VS Code.

**Please confirm that the issue/resolution isn't already documented**
- [ ✓ ] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open any extension that includes the stats buttons

**Expected behavior**
They should load correctly, but instead they only appear as plain text.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/39648288/57162430-8440e400-6dee-11e9-9f88-492c3ae6de9a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Architecture: 64-bit
 - Version 1.33

**Additional context**
This is (for example) what should appear.
![Screenshot_2](https://user-images.githubusercontent.com/39648288/57162553-e568b780-6dee-11e9-9fc9-9682a55114c2.png)

Tried reinstalling and it didn't help. Also appears on my other computer.

**Comment by stripedpajamas** [comment] 2019-05-03 20:26
Thanks for the heads up, @Golotvinov 👍 

I believe this is due to some of the telemetry stripping out that we do pre-build, but I haven't confirmed yet.

I also think this is a duplicate of #125 so I will close this out, and you can subscribe to #125 for updates on progress as we sort through it.

**Closed by stripedpajamas** 2019-05-03 20:26 UTC
Labels: bug
