### ISSUE TITLE
What's the status of apple M1/arm64 support?

### ISSUE THREAD

**Issue by spencerkohan** [VSCodium/vscodium#597] opened 2020-12-23 14:32 UTC
Is there a plan to do a release of VSCodium which is native to M1, or else a universal binary?  It looks like VSCode is already supporting this, is it on the roadmap for VSCodium?

**Comment by stripedpajamas** [comment] 2020-12-30 00:20
Since VSCode is already supporting it, it's on the roadmap for VSCodium. If GH Actions has support for Darwin+arm, it should be really simple. Haven't had a chance to look into it yet.

**Comment by heracek** [comment] 2021-01-12 07:52
There is no support in GitHub Actions yet 😢: https://github.com/actions/virtual-environments/issues/2187

**Comment by stripedpajamas** [comment] 2021-01-13 00:26
Yeah we will need to wait for GH Actions support; suggest :+1:-ing the linked issue.

**Comment by djthread** [comment] 2021-03-08 17:38
VSCode 1.54+ has M1 support now! Super looking forward to the VSCodium update :)

**Comment by jiserra** [comment] 2021-03-15 03:42
I downloaded 1.54.2 and the Architecture still says "Intel"… what I'm missing?

> Edit: Yay I'm on 1.54.2 now \o/

**Comment by daiyam** [comment] 2021-03-15 09:19
@jiserra M1 is not available on github actions. Microsoft must be using a mac mini to build its project.

**Comment by ayan-iiitd** [comment] 2021-03-15 12:04
Can someone please clarify if the latest build is on arm or not? confused by the two comments - 

> VSCode 1.54+ has M1 support now! Super looking forward to the VSCodium update :)
> 
> Edit: Yay I'm on 1.54.2 now \o/





> I downloaded 1.54.2 and the Architecture still says "Intel"… what I'm missing?

**Comment by daiyam** [comment] 2021-03-15 14:26
VSCodium is built with GitHub actions which don't support M1 yet.
VSCode is built on their own servers. There must be using mac mini to build the M1 version.

**Comment by leonardodino** [comment] 2021-03-15 23:16
A [related project](https://ungoogled-software.github.io) is using GitHub actions to compile Chromium from source to `arm64-macos`.

The builds takes [more than a day](https://github.com/kramred/ungoogled-chromium-macos/actions/runs/650095821) tho 👀 Hopefully vscodium is using a pre-built electron as base? 🤔

**Comment by djthread** [comment] 2021-03-25 01:27
oh snap, indeed, i spoke too soon - sorry.

**Comment by gytisrepecka** [comment] 2021-03-25 14:23
> The builds takes [more than a day](https://github.com/kramred/ungoogled-chromium-macos/actions/runs/650095821) tho 👀 Hopefully vscodium is using a pre-built electron as base? 🤔

Does Electron already support M1 (aarch64)?

**Comment by togethereveryday** [comment] 2021-04-18 09:15
Let´s say I have a M1 machine, what would be necessary to build VS Codium? My status: I have a machine, I have basic programming skills in front end web development. Is it difficult if one has never done it?

**Comment by LukeChannings** [comment] 2021-04-18 09:32
@togethereveryday 

Have a read of the GitHub Actions workflow for your OS - [here](https://github.com/VSCodium/vscodium/tree/master/.github/workflows). That's where I'd start.

**Comment by daiyam** [comment] 2021-04-18 10:18
@theotheroracle If you want to build VSCodium manually, you can run the script `build/build_macos.sh`. You might have to edit it to change targeted architecture.

**Comment by theotheroracle** [comment] 2021-04-23 03:22
i'm a  bit confused as to why i was pinged

**Comment by daiyam** [comment] 2021-04-23 08:10
@theotheroracle Sorry, it's my mistake. Bad autocomplete and I haven't rechecked...

**Comment by theotheroracle** [comment] 2021-04-23 12:33
Oh ok, no worries

**Comment by rolimans** [comment] 2021-05-26 01:11
Was able to build for the M1 on my machine. Changed the environment variable `VSCODE_ARCH` to `arm64` and installed `jq` using `brew install jq` then ran `./build/build_macos.sh`. ;)

**Comment by jiserra** [comment] 2021-05-27 00:24
I had to modify a couple of packages on `package.json`, but I finally could build it!

**Comment by tibeer** [comment] 2021-06-04 08:18
If anybody is lazy, you can use the binary from my fork: https://github.com/tibeer/vscodium
This is compiled on my M1 Mac. I try to keep it updated.

**Comment by Tarnyko** [comment] 2021-06-08 19:57
> If anybody is lazy, you can use the binary from my fork: https://github.com/tibeer/vscodium
> This is compiled on my M1 Mac. I try to keep it updated.

Thanks @tibeer , this is definitely appreciated!

**Comment by im-AMS** [comment] 2021-06-12 05:18
> If anybody is lazy, you can use the binary from my fork: https://github.com/tibeer/vscodium
> This is compiled on my M1 Mac. I try to keep it updated.

I actually tried running, and it says `“VSCodium.app” is damaged and can’t be opened. You should move it to the Bin.`

**Comment by melgu** [comment] 2021-06-12 15:03
> I actually tried running, and it says `“VSCodium.app” is damaged and can’t be opened. You should move it to the Bin.`

This is because of Gatekeeper restrictions as the app isn't signed. You can execute the following to remove the quarantine attribute.
```
sudo xattr -r -d com.apple.quarantine /Applications/VSCodium.app
```

**Comment by tortuetorche** [comment] 2021-06-29 16:36
> If anybody is lazy, you can use the binary from my fork: https://github.com/tibeer/vscodium
> This is compiled on my M1 Mac. I try to keep it updated.

Hi @tibeer,

Thank you for these M1 ARM64 builds 👍
Just one question, why your builds since VSCodium 1.57.0 are way more bigger than the classic Darwin x64 builds (~105 MB VS ~260 MB)?
Can you manage to shrink them a bit, please?

Have a good day,
Tortue Torche

**Comment by tibeer** [comment] 2021-07-01 04:36
> > If anybody is lazy, you can use the binary from my fork: https://github.com/tibeer/vscodium
> > This is compiled on my M1 Mac. I try to keep it updated.
> 
> Hi @tibeer,
> 
> Thank you for these M1 ARM64 builds 👍
> Just one question, why your builds since VSCodium 1.57.0 are way more bigger than the classic Darwin x64 builds (~105 MB VS ~260 MB)?
> Can you manage to shrink them a bit, please?
> 
> Have a good day,
> Tortue Torche

@tortuetorche interesting, I never noticed. Further discussion/resolving should be done here: https://github.com/tibeer/vscodium/issues/2

**Comment by MohamedElashri** [comment] 2021-09-17 13:41
I think this can be added to official project as now Big sur is available on github actions. See [here](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md).

**Comment by daiyam** [comment] 2021-09-17 13:57
@MohamedElashri Thx for the info. I will take a look.

**Comment by MohamedElashri** [comment] 2021-09-17 21:19
I think it is just a trivial change now in `macos.yml` action config. Just change `VSCODE_ARCH: "x64"` to `VSCODE_ARCH: "arm64"` and build will go fine.

**Comment by daiyam** [comment] 2021-09-18 10:18
The `arm64` binary has been released. I can't test it. Can you test if it's working and is really a `arm64` binary?

**Comment by im-AMS** [comment] 2021-09-18 12:06
@daiyam I tried running on my M1 Air, It opens but high CPU usage and the beach ball of death!

**Comment by LukeChannings** [comment] 2021-09-18 12:14
Can confirm, it crashes for me too.

**Comment by daiyam** [comment] 2021-09-18 12:20
Can you try `/Applications/VSCodium.app/Contents/Resources/app/bin/codium --verbose`?

**Comment by LukeChannings** [comment] 2021-09-18 12:21
> dlopen(/Users/luke/Downloads/VSCodium.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/sqlite.node, 0x0001): tried: '/Users/luke/Downloads/VSCodium.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/sqlite.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/sqlite.node' (no such file), '/usr/lib/sqlite.node' (no such file)

**Comment by MohamedElashri** [comment] 2021-09-18 13:35
I think the problem is that we are using the same `NodeJs` version 14 like intel arch, but we will need to pass different version. `NodeJS v15` to be specific. Node 14 does not support calling correct arm nodes. One solution might be adding a new workflow for mac-arm and install [NVM](https://github.com/nvm-sh/nvm#installing-and-updating) if needed.

**Comment by daiyam** [comment] 2021-09-20 07:13
@MohamedElashri VSCode is built with node v14 so it isn't the issue.
In the log, you can see that the dependencies have the wrong architecture.

Since I can't test it, I'm removing the binaries to avoid confusion.
If you can can test it, please make PR with a working workflow. Thx

**Comment by tibeer** [comment] 2021-09-20 07:19
Strange behavior. I'm building my version by this:
```sh
SHOULD_BUILD=yes CI_BUILD=no OS_NAME=osx VSCODE_ARCH=arm64 . build.sh
```
My CPU usage is normal.

**Comment by daiyam** [comment] 2021-09-20 07:22
Yes, I know that why I went ahead with the test.

In VSCode, they are switch XCode version and maybe other stuffs. Since I can't test it, I don't want to re-try on the official build.

That's why, any tested PR are welcome.

**Comment by daiyam** [comment] 2021-09-20 22:31
For mac users out there (with a recent macOS), is it normal that VSCodium asks for this kind of permissions: https://imgur.com/a/o3LiErm

**Comment by MohamedElashri** [comment] 2021-09-20 22:53
No It does not ask for these on Big Sur. I still did not update to Monterey yet but will try later tonight.   

Note: I'm using a locally built binary on MBP m1 if that makes difference for your question.

**Comment by daiyam** [comment] 2021-09-20 23:06
It's from an user on reddit after I've redirected him to @tibeer's builds...
https://www.reddit.com/r/MacOS/comments/pr7bsg/homebrew_problem_with_m1_mac/hdkk68k?utm_source=share&utm_medium=web2x&context=3

**Comment by MohamedElashri** [comment] 2021-09-20 23:14
I tried @tibeer 's build now, and it does not prompt these permission requests.

**Comment by melgu** [comment] 2021-09-21 06:53
> For mac users out there (with a recent macOS), is it normal that VSCodium asks for this kind of permissions: https://imgur.com/a/o3LiErm 

It seems, the user opened the whole drive in VSCodium. In that case, all of those prompts would be shown. Perfectly normal.

**Comment by gearj** [comment] 2021-09-21 08:19
At https://github.com/microsoft/vscode/wiki/How-to-Contribute I saw they mention the following:

> when cross-compiling for ARM, set `npm_config_arch` to `arm`

Not sure if it'll help with the build issues.

**Comment by Demoxing** [comment] 2021-09-22 02:43
> I tried @tibeer 's build now, and it does not prompt these permission requests.

> It's from an user on reddit after I've redirected him to @tibeer's builds...
https://www.reddit.com/r/MacOS/comments/pr7bsg/homebrew_problem_with_m1_mac/hdkk68k?utm_source=share&utm_medium=web2x&context=3


I am the Reddit guy who shares the permission screenshot above. I used the @tibeer's build, and it was asking me for those permissions.

Document, Download, Calendar, Reminders, Contacts, Photos, etc. It sounds fishy to me. That's why I asked it on Reddit. I am using a m1 mac and macOS v11.6.

**Comment by lwears** [comment] 2021-12-04 15:23
Hey @rolimans I tried what you said but when i open the app after build it immediately crashes. Any idea what this could be? Could it be something to do with extensions that I have installed on my original VSCodium? If so im not sure how to disable the extensions on the new build.

**Comment by holmesmr** [comment] 2021-12-09 11:04
@Demoxing:
> What do you mean by opening the whole drive?

If you accidentally open `/` or your whole user folder (`/Users/<username>`), VSCode/codium will search through all the directories, which will trigger these permission prompts.

**Comment by Alitejawi** [comment] 2021-12-23 14:46
No news on a supported version of arm arch through the default VSCodium project?

**Comment by MohamedElashri** [comment] 2021-12-31 09:02
> 

Unless Github add mac m1 VMs to Github action, nothing will change.
 
But you don't need that anyway, clone the repo and build VSCodium on your machine and everything will work following this [comment](https://github.com/VSCodium/vscodium/issues/597#issuecomment-848383243).

**Comment by 1LIA5** [comment] 2022-01-06 12:51
build it your self. Here is a guide: https://ilias.sh/posts/build-vscodium-on-darwin-arm64/

**Comment by macserv** [comment] 2022-01-13 19:39
> Unless Github add mac m1 VMs to Github action, nothing will change.

@1LIA5, if you have a moment, could you please explain why this is the case?  It seems like other Xcode and Electron projects are able to build on Intel-based Macs/VMs and produce a "Universal" application which can run natively on either architecture.

Thanks!

**Comment by daiyam** [comment] 2022-01-13 21:11
@macserv Yes, it seems to be possible but we need somebody to be able make a working PR. Since I can't test it, I won't make it... But anybody is free to make :wink:

**Comment by arixmkii** [comment] 2022-01-27 11:24
> It seems like other Xcode and Electron projects are able to build on Intel-based Macs/VMs and produce a "Universal" application which can run natively on either architecture.

For VSCodium situation is a bit different, because you need to build it the same way the upstream is built. And looks like they first build archives on different platforms and after this combine into universal app:
https://github.com/microsoft/vscode/blob/bc71f7a3438fae0edced4ed91bc9429a72cdb416/build/azure-pipelines/darwin/product-build-darwin.yml#L150

I tried to do it on M1 Mac (building for both architectures on that host) and this didn't work. I will try do build x64 on Intel Mac later and then compose universal on M1 some time later.

So, to get fully functional universal app, not only the build targets will have to be adjusted, but the whole CI workflow should include additional steps (fetching intermediate artifacts from different build agents).

**Comment by berkaybakacak** [comment] 2022-02-14 10:01
Changed the environment variable VSCODE_ARCH to arm64, installed all dependencies then ran ./build/build_macos.sh. And it gave me error: ./build/build_macos.sh: line 8: arm64: command not found

**Comment by codeluggage** [comment] 2022-03-10 06:56
@berkaybakacak

> Changed the environment variable VSCODE_ARCH to arm64, installed all dependencies then ran ./build/build_macos.sh. And it gave me error: ./build/build_macos.sh: line 8: arm64: command not found

It built ok for me on `macOS 12.2.1` after changing to `arm64` like this: 

```bash
SHOULD_BUILD=yes CI_BUILD=no OS_NAME=osx VSCODE_ARCH=arm64 . build.sh
```

on https://github.com/VSCodium/vscodium/blob/master/build/build_macos.sh#L8

and then running the build as `VSCODE_ARCH=arm64 ./build/build_macos.sh`

**Comment by ferben** [comment] 2022-03-31 14:27
Is there official release date VSCodium prebuilt binaries for Apple Silicon?

**Comment by ferben** [comment] 2022-03-31 18:00
You can build arm64 binary on x86_64 too. You need only Xcode 12.5 or 13. 
Only for testing you need Apple Silicon hardware.

**Comment by y-mx-b** [comment] 2022-03-31 18:35
You could just build a universal binary too, couldn't you? Not really much of a reason to split the releases by architecture if a universal binary build works.

**Comment by daiyam** [comment] 2022-03-31 19:46
I already tried to make to make an arm64 binary by using macOS 11 but the dependencies were still x86. Since I can't test, it's kinda hard for me to find the issue, if it's possible...
With M1 vm, I would somewhat more sure that the binary would be more successful.
But I would welcome any PR that would build the arm64 binary on the existing vm of GitHub!

**Comment by JakeHL** [comment] 2022-04-14 18:49
I'm free to test M1 binaries by the way. I've just built the latest version of code this morning. I'm also putting together a brew script that will build and install locally.

**Comment by berkaybakacak** [comment] 2022-04-15 14:28
https://drive.google.com/file/d/12dvGL8rbV7wP880Gc_cuvlwjiDTHw4P_/view?usp=sharing

Here. I built arm64 version on my M1 Air, macOS 12.2.1

**Comment by matthewess** [comment] 2022-04-20 21:32
> @berkaybakacak
> 
> > Changed the environment variable VSCODE_ARCH to arm64, installed all dependencies then ran ./build/build_macos.sh. And it gave me error: ./build/build_macos.sh: line 8: arm64: command not found
> 
> It built ok for me on `macOS 12.2.1` after changing to `arm64` like this:
> 
> ```shell
> SHOULD_BUILD=yes CI_BUILD=no OS_NAME=osx VSCODE_ARCH=arm64 . build.sh
> ```
> 
> on https://github.com/VSCodium/vscodium/blob/master/build/build_macos.sh#L8
> 
> and then running the build as `VSCODE_ARCH=arm64 ./build/build_macos.sh`

This works for me on my M1 Pro, macOS 12.3.1. What can I do to contribute to getting these binaries hosted with the other releases? I'd really love to make the M1 build available on Nixpkgs.

**Comment by daiyam** [comment] 2022-04-27 16:23
Hi all, the macOS arm64 binary is finally available. Please provide any feedback if it's working or not. Thx
Do the universal version needed? Since we are dev, we know which arch we are using.

**Comment by MohamedElashri** [comment] 2022-04-28 16:27
> Hi all, the macOS arm64 binary is finally available. Please provide any feedback if it's working or not. Thx
> Do the universal version needed? Since we are dev, we know which arch we are using.

I have replaced my built arm64 version by the selfhosted generated version on the repo and so far it is working without any problems.

**Comment by tibeer** [comment] 2022-04-29 04:37
@daiyam for completeness: Can you post the link to the binary which should be tested? It's neither here: https://github.com/VSCodium/vscodium/releases nor here: https://github.com/VSCodium/vscodium/tags

**Comment by daiyam** [comment] 2022-04-29 04:59
It's in: https://github.com/VSCodium/vscodium/releases/tag/1.66.2
- https://github.com/VSCodium/vscodium/releases/download/1.66.2/VSCodium-darwin-arm64-1.66.2.zip
- https://github.com/VSCodium/vscodium/releases/download/1.66.2/VSCodium.arm64.1.66.2.dmg

**Comment by tibeer** [comment] 2022-04-29 05:08
Sorry, my fault. Thought this was outdated since Github flags this as "released this 16 days ago". Besides the issue that the app is still blocked by default (can be fixed `sudo xattr -r -d com.apple.quarantine /Applications/VSCodium.app`), it works fine:
<img width="1022" alt="Bildschirmfoto 2022-04-29 um 07 06 17" src="https://user-images.githubusercontent.com/39375770/165888016-831d73f1-9549-4193-9f6b-d6918410f2f2.png">

**Comment by daiyam** [comment] 2022-04-29 06:27
@tibeer For the quarantine, yep, I'm in the process to update the README and the website.

**Comment by AwlsomeAlex** [comment] 2022-05-06 20:21
If you want to learn more about why you need to clear the quarantine flag on Apple Silicon builds, take a look at this [Apple Platform Security Document](https://support.apple.com/guide/security/rosetta-2-on-a-mac-with-apple-silicon-secebb113be1/).

Specially under **Unsigned x86_64 code**:
> A Mac with Apple silicon doesn’t permit native arm64 code to execute unless a valid signature is attached.

>For binary compatibility, translated x86_64 code is permitted to execute through Rosetta with no signature information at all.

**Closed** 2022-06-17 10:51 UTC
