### ISSUE TITLE
Latex Workshop

### ISSUE THREAD

**Issue by Eolien55** [VSCodium/vscodium#839] opened 2021-09-12 19:35 UTC
**Describe the bug**
Latex Workshop doen't work in VSCodium. It doesn't show the TeX icon, neither can I compile TeX projects. It even throws an exception : 
`Yu.latex-workshop' failed: Cannot find module '/home/eolien55/.vscode-oss/extensions/james-yu.latex-workshop-8.20.2/out/src/main.js'
Require stack:
- /usr/share/vscodium/resources/app/out/vs/loader.js
- /usr/share/vscodium/resources/app/out/bootstrap-amd.js
- /usr/share/vscodium/resources/app/out/bootstrap-fork.js`

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium. I tried and TeX workshop does work

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Install TeX workshop
2. Observe
3. Open developer tools, and see thrown exception

**Expected behavior**
Having TeX working like it does in MS VSCode

**Screenshots**
None needed

**Desktop (please complete the following information):**
 - OS: Garuda Linux (arch-based)
 - Architecture x64
 - Version 1.60.0

**Additional context**
[Mentioned extension's repo](https://github.com/James-Yu/LaTeX-Workshop)

**Comment by daiyam** [comment] 2021-09-12 19:44
Hi, it's a duplicate of #486

> This is an issue of OpenVSX which has publish a broken version. (I've checked, files are missing). I would encourage you to encourage the author of the extension to publish directly the extension.
> In the meantimes, you can download the vsix from https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop and install it manually.

I've opened an issue: https://github.com/James-Yu/LaTeX-Workshop/issues/2865

**Closed by daiyam** 2021-09-12 19:44 UTC
Labels: bug

**Comment by Eolien55** [comment] 2021-09-12 19:46
Oh thanks, really nice of you
