### ISSUE TITLE
Markdown preview broken in 1.78.1

### ISSUE THREAD

**Issue by completementgaga** [VSCodium/vscodium#1503] opened 2023-05-10 08:40 UTC
**Markdown preview broken  in 1.78.1**
After a nightly update, I am currently running version 1.78.1 of VScodium. As a result the markdown preview is not working anymore.

**Please confirm that this problem is VSCodium-specific**
- I do not wish to install VS Code on my laptop.

**Please confirm that the issue/resolution isn't already documented**
- [ X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. open a .md document
2. Click on 'open preview' (or hit ctrl+maj+V on ubuntu)
4. See error : The preview window is just a black screen

**Expected behavior**
The expected behaviour is the one of the pre-update version : display of the preview in the preview window

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2
 - Architecture : x64
 - App Manager: Snap
 - Sandboxed: Snap

**edit: Graphics Card**
TigerLake-LP GT2 [Iris Xe Graphics] by Intel

**edit: other possibly related bugs**
 ipynb notebooks windows and extensions' description windows not displaying anything either

**Comment by dharmann** [comment] 2023-05-10 08:55
I've the same problem in a very similar environment. Just a difference: I'm using a DEB version of VSCodium, not the snap one.

**Comment by dharmann** [comment] 2023-05-10 09:09
> I've the same problem in a very similar environment. Just a difference: I'm using a DEB version of VSCodium, not the snap one.

Just more details: I think that this problem is VSCodium-specific, because installing VS Code, the problem does not exists. A proof of that is also showing the "details tab" of an extension of your choice or the VSCodium changelog too. I'm falled in this problem trying to use the "Git Graph" extension, that hasn't shown anything.

![Screenshot_20230510_110817](https://github.com/VSCodium/vscodium/assets/6182373/e5f91546-1cad-4ec4-beba-79cca76ad801)

**Comment by Kimmmey** [comment] 2023-05-10 09:22
Same for me:

OS: Windows 11
Architecture : x64
Setup: System Setup

**Comment by dirkolbrich** [comment] 2023-05-10 10:20
Same for me: Markdown Preview does not display anything, details page of extensions is empty

OS: macOS Ventura 13.3.1 (a)
Architecture: Apple M1 Max, arm64
installed via Homebrew casks: `brew install --cask vscodium`

**Comment by NunonuN** [comment] 2023-05-10 16:08
Not only do I have the same problem, but I can't view **PDF**s when editing $\LaTeX$ files.

- OS: Manjaro Linux
- Architecture: x86_64
- App Manager: AUR
- Package: `vscodium-bin`
- Release: 178.1.23130-1

**Comment by dr-br** [comment] 2023-05-10 16:37
I can't view **pdf** nor **md** previews on one PC, but on the other. The only difference (as far as I'm aware of) between both PCs is the GPU:
**Not working** on *NVIDIA Geforce RTX 3050*  
**Working** on *AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT*

OS: Manjaro Linux x86_64
Kernel: 6.3.1-3-MANJARO
Resolution: 3840x2160
DE: GNOME 44.1 
CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz

```
yay -Qi visual-studio-code-bin 
Name                     : visual-studio-code-bin
Version                  : 1.78.1-1
``

**Comment by mtacnet** [comment] 2023-05-10 21:22
Hi 👋🏻 Same here

Configuration:

```sh
$> lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 11 (bullseye)
Release: 11
Codename: bullseye
```

```sh
$> cat /etc/debian_version
11.7
```

```sh
$> uname -a
Linux debian 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
```

Thank you in advance for your correction 🙏🏻

**Comment by cyclopticnerve** [comment] 2023-05-10 22:02
Also broken on :
EVERYTHING

**Comment by fcgreg** [comment] 2023-05-11 01:55
Can confirm same problem exists on Windows 10:

Version: 1.78.1
Release: 23130
Commit: 748cf23d39091308b3b0d65ac43f0d784709fdcc
Date: 2023-05-10T01:38:10.529Z
Electron: 22.3.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by redactedscribe** [comment] 2023-05-11 09:35
Confirmed with all extensions disabled.

```
Version: 1.78.1
Release: 23130
Commit: 748cf23d39091308b3b0d65ac43f0d784709fdcc
Date: 2023-05-10T01:38:10.529Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) VSCodium/1.78.1 Chrome/108.0.5359.215 Electron/22.3.5 Safari/537.36
```

**Comment by tuupola** [comment] 2023-05-11 12:52
Same problem with Fedora 36.

```
$ cat /etc/fedora-release  a
Fedora release 36 (Thirty Six)

$ dnf info codium  
Last metadata expiration check: 0:00:07 ago on 2023-05-11T15:48:51 EEST.
Installed Packages
Name         : codium
Version      : 1.78.1.23130
Release      : el7
Architecture : x86_64
Size         : 313 M
Source       : codium-1.78.1.23130-el7.src.rpm
Repository   : @System
From repo    : gitlab.com_paulcarroty_vscodium_repo
```

**Comment by redactedscribe** [comment] 2023-05-11 16:09
It appears to still be broken on Windows after updating.

```
Version: 1.78.1
Release: 23131
Commit: abdfa343d7fcd6ee2fd896e746a586e990db1e33
Date: 2023-05-11T15:09:14.581Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) VSCodium/1.78.1 Chrome/108.0.5359.215 Electron/22.3.5 Safari/537.36
```

**Comment by ftimurs** [comment] 2023-05-11 16:13
Same, still broken
`Version: 1.78.1 (user setup)
Release: 23131
Commit: abdfa343d7fcd6ee2fd896e746a586e990db1e33
Date: 2023-05-11T15:09:14.581Z
Electron: 22.3.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No`

**Comment by WMarks-Enertech** [comment] 2023-05-11 16:26
Same error on my installation, also updated.

**Comment by tc2290** [comment] 2023-05-11 16:39
Also on Windows and still seeing the same issue. Time to downgrade again I guess...

Windows 10 Pro
x64

**Comment by daiyam** [comment] 2023-05-11 16:55
Closing in favor of #1515. Please follow the updates there.

**Closed by daiyam** 2023-05-11 16:55 UTC
Labels: bug
