### ISSUE TITLE
unable to open ipynb (notebooks) in 1.78.1

### ISSUE THREAD

**Issue by moon91210** [VSCodium/vscodium#1507] opened 2023-05-10 11:23 UTC
i'm unable to open any jupyter notebooks in the last update, it just shows the loading bar at the top forever but it doesn't actually do anything

os: win7
version: 1.78.1

**Comment by salym** [comment] 2023-05-10 20:26
Duplicate of #1508

**Comment by daiyam** [comment] 2023-05-11 16:56
Closing in favor of #1515. Please follow the updates there.

**Closed by daiyam** 2023-05-11 16:56 UTC
