### ISSUE TITLE
VSCodium AppImage will not run after latest update

### ISSUE THREAD

**Issue by iSmashButtons** [VSCodium/vscodium#854] opened 2021-09-28 22:01 UTC
**Describe the bug**
VSCodium AppImage conflicts with packages on Manjaro and will not run. Trying to execute AppImage from GUI results in no action. Executing AppImage from terminal reveal error:

`codium: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full`

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
Tested this by installing Code-OSS from Arch community repository
Also set up new Manjaro installation on another computer and tried running the AppImage there. Had the same result.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Run Manjaro VM
2. Update packages to latest version
3. Execute VSCodium AppImage

**Expected behavior**
Application should run

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Architecture: x86_64
 - Version: n/a

**Additional context**
After updating my system packages yesterday, trying to execute the AppImage as normal (from GUI/rofi) resulted in no action. Executing AppImage from the terminal produced this error:

`codium: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full`

Found [this Arch forum post with a similar problem for a different AppImage](https://bbs.archlinux.org/viewtopic.php?id=269838) 

Patched VSCodium AppImage with glib2 version 2.68.4.

When executing the patched AppImage a similar error occurs, but now it is a different library/package:

`codium: symbol lookup error: /usr/lib/libtracker-sparql-3.0.so.0: undefined symbol: sqlite3_expanded_sql`

**Comment by daiyam** [comment] 2021-12-17 22:14
Can you try [VSCodium-1.63.2-1639774037.glibc2.17-x86_64.AppImage.zip](https://app.box.com/s/lgmxi73qebmsiwv7liy6thwlh0105r8h)?
I've been able to make it run under Arch and Fedora 34/35 while being built on Ubuntu 18.04.
The changes I've made can be found at #944.

**Comment by pkve** [comment] 2021-12-19 10:54
> Can you try VSCodium-1.63.2-1639774037.glibc2.17-x86_64.AppImage.zip?

It also works on my OpenSUSE Tumbleweed. Thanks!

**Comment by TheAssassin** [comment] 2021-12-31 00:38
See https://github.com/AppImage/AppImageKit/issues/1162. Looks like something that needs to be fixed over at AppImageKit. Rebuilding the AppImage then should fix the issue.

**Comment by daiyam** [comment] 2021-12-31 02:55
The issue is due to the libraries `libgmodule-2.0.so` and `libsqlite3.so`. (https://github.com/AppImage/pkg2appimage/issues/494#issuecomment-997781907)

**Comment by nuno-silva** [comment] 2022-02-02 13:42
I'm having this issue using `VSCodium-1.63.2-1639700424.glibc2.17-x86_64.AppImage`.

> /tmp/.mount_codeeXHAOK/usr/share/codium/codium --unity-launch: symbol lookup error: /usr/lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full

Using Gentoo Linux amd64 with glib-2.70.2.

Worked around it by downgrading to glib-2.68.4.

**Comment by daiyam** [comment] 2022-02-02 14:03
@nuno-silva Have you tried :
> Can you try [VSCodium-1.63.2-1639774037.glibc2.17-x86_64.AppImage.zip](https://app.box.com/s/lgmxi73qebmsiwv7liy6thwlh0105r8h)?

**Comment by nuno-silva** [comment] 2022-02-02 14:39
@daiyam sorry mate, I can only run official releases from this repo. I see your PR #944 was already merged, so I'll wait until the next release :) thank you for your work.

**Comment by daiyam** [comment] 2022-02-04 06:49
The AppImage for `1.64` is working. Can you confirm? Thx

**Comment by nuno-silva** [comment] 2022-02-05 23:54
Just confirmed `VSCodium-1.64.0-1643956064.glibc2.17-x86_64.AppImage` is working for me with both glib-2.68.4 and glib-2.70.2. Thank you

**Comment by eightfiftytwo** [comment] 2022-03-04 11:10
Seems like it's happening again with `VSCodium-1.65.0-1646384533.glibc2.17-x86_64.AppImage` on Fedora Workstation 35.
`sed: /tmp/.mount_VSCodiEfUYOJ/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by sed)
codium: /tmp/.mount_VSCodiEfUYOJ/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib64/libgio-2.0.so.0)
codium: /tmp/.mount_VSCodiEfUYOJ/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib64/libmount.so.1)
codium: /tmp/.mount_VSCodiEfUYOJ/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib64/libkrb5support.so.0)
codium: symbol lookup error: /lib64/libgobject-2.0.so.0: undefined symbol: g_date_copy`

**Comment by daiyam** [comment] 2022-03-04 11:58
Yep! I have the same error...

**Comment by daiyam** [comment] 2022-03-04 14:10
I'm regenerating the AppImage with the fix.

**Comment by eightfiftytwo** [comment] 2022-03-04 17:18
It's working! Thanks.

**Closed** 2022-03-05 09:35 UTC
Labels: bug
