### ISSUE TITLE
macOS - Unnotarized Developer ID

### ISSUE THREAD

**Issue by motionbug** [VSCodium/vscodium#1277] opened 2022-10-06 10:00 UTC
**Describe the bug**
Error verifying /Volumes/VSCodium/VSCodium.app error:
/Volumes/VSCodium/VSCodium.app: rejected
source=Unnotarized Developer ID
origin=Developer ID Application: Peter Squicciarini (C7S3ZQ2B8V)

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Download App and open App with like [Apparency](https://www.mothersruin.com/software/Apparency/use.html)

**Expected behavior**
The app has been signed before.. what happened 
**Screenshots**
<img width="1405" alt="CleanShot 2022-10-06 at 11 57 22@2x" src="https://user-images.githubusercontent.com/36737/194284347-91fd2b55-5a95-400c-b58e-7ccb66b58be2.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Architecture [arm64]
 - Version [1.71.2]
 - App Manager [dmg or Homebrew or [Installomator](https://github.com/Installomator/Installomator)]

**Additional context**

**Comment by daiyam** [comment] 2022-10-06 10:32
As far I'm aware the VSCode has never been notarized.
It is signed so that the update are working but nothing has been paid to Apple (or Microsoft) to notarized the VSCode.

**Comment by Hacksore** [comment] 2022-10-20 13:16
VSCode has been notarized probably for years 😬.

![image](https://user-images.githubusercontent.com/996134/196958889-1f58eaf8-45f2-4160-9b3d-5b24171abb6d.png)
![image](https://user-images.githubusercontent.com/996134/196958908-db1de09c-aa72-468e-88b6-b68ba5a9117f.png)

**Comment by daiyam** [comment] 2022-10-20 14:05
Oops, I meant VSCodium...

**Comment by GitMensch** [comment] 2023-02-27 11:08
duplicate of #643

**Comment by GitMensch** [comment] 2023-02-27 11:10
duplicate of #643

**Closed by GitMensch** 2023-02-27 11:10 UTC
Labels: bug
