### ISSUE TITLE
Visual Studio Codium turns blank when alt-tabbing to other maximised windows.

### ISSUE THREAD

**Issue by ghost** [VSCodium/vscodium#312] opened 2020-01-02 15:38 UTC
**Describe the bug**
VSCodium randomly goes blank when I switch to Discord, Chrome or any other window that is maximised. Have to open a new instance to get a display again.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**Screenshots**
![Screenshot](https://imgur.com/a/4lP4efp)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Architecture: x64
 - Version: 1.41.1

**Additional context**
I'm still able to click buttons but I can not see them.

**Comment by stripedpajamas** [comment] 2020-01-02 16:42
Potentially a duplicate of https://github.com/VSCodium/vscodium/issues/296 ?

**Comment by Hydr43301** [comment] 2020-01-02 17:21
> Potentially a duplicate of #296 ?

I provided a lot more information, plus it isn't related to the amount of windows open on my desktop but instead the fact I'm switching between windows that are maximised. Haven't tested with windowed applications.

**Comment by theianrey** [comment] 2020-01-05 09:24
Same here. Currently experiencing this issue with the same specs. I need to re-open codium just to make it work again. But still, after re-opening, the issue persist after some time it was being open.

**Comment by Hydr43301** [comment] 2020-01-05 21:08
I'm still awaiting an update on the status of the issue. I don't truly recognise what is happening in the code so I can't make a fork and make a hotfix. I'll try to work on it but not sure how much progress I'll make.

**Comment by theianrey** [comment] 2020-01-06 03:00
> I'm still awaiting an update on the status of the issue. I don't truly recognise what is happening in the code so I can't make a fork and make a hotfix. I'll try to work on it but not sure how much progress I'll make.

just fire some updates whenever you have any findings.
thanks. 
😄

**Closed** 2021-09-06 18:46 UTC
Labels: bug
