### ISSUE TITLE
"Out of Range" error when starting codium.

### ISSUE THREAD

**Issue by KBassford** [VSCodium/vscodium#368] opened 2020-03-24 15:26 UTC
**Describe the bug**
Every time I attempt to start codium, I recieve the following error (see screenshot below).  Cannot use program.

**Please confirm that this problem is VSCodium-specific**
- [ ] Unknown

**Please confirm that the issue/resolution isn't already documented**
- [ ] I checked using Google, no matching issues found.

**To Reproduce**
1. type 'codium' in a terminal window.
![codium-error](https://user-images.githubusercontent.com/31860128/77442809-0a786700-6dc1-11ea-8a5c-19a8fe464c26.png)

**Expected behavior**
Codium should start.

**Screenshots**
(see highlighted portion of screenshot included above)
![codium-error](https://user-images.githubusercontent.com/31860128/77442602-e74db780-6dc0-11ea-897e-5d82537ec7bd.png)

**Desktop (please complete the following information):**
 - OS: Devuan ascii
 - Architecture x64
 - Version ascii

**Additional context**
I presume there is some undisclosed dependency that I am missing (Devuan is a minimal Debian distro).  I have seen where other applications have thrown similar errors, but none of the fixes were applicable.  I already updated my node.js to the latest version with no effect.  I've used Codium in many other environments without problem.
EDIT: I've been trying to fix this issue and after updating nodejs (now 13.11.0) I found that "npm -v' also causes the same error!  Complete uninstall and reinstall of nodejs did nothing.

**Comment by stripedpajamas** [comment] 2020-04-19 20:07
Hi @KBassford -- if this is same thing is happening with `npm`, I think we will not have much luck getting to the bottom of it from a VSCodium perspective. My guess is that the the text encoding in Devuan ascii is unsupported/unexpected to Node, and VSCode/VSCodium are simply using Node to run (bundled). 

I will close this issue as the problem is deeper than this project can go :(

**Closed by stripedpajamas** 2020-04-19 20:07 UTC
Labels: bug
