### ISSUE TITLE
Cannot resize window

### ISSUE THREAD

**Issue by fusionneur** [VSCodium/vscodium#1061] opened 2022-04-26 08:25 UTC
i cannot resize window by dragging the side of it. The mouse will just slide across the border without resizing

v 1.66.2
Windows 11 x64

**Comment by fusionneur** [comment] 2022-04-26 08:26
dragging by the corner however works. the window can be resized.

**Comment by brxken128** [comment] 2022-04-27 09:42
do you have this issue when using vscode too, or just this fork? many of these bugs seem to be upstream, and not down to vscodium itself. after all, vscodium is just a telemetry-free vscode

**Comment by fusionneur** [comment] 2022-04-27 09:53
Unfortunatelly I do not have vscode installed. If anoyone test in both would be great. Thanks

**Comment by jonberenguer** [comment] 2022-04-28 05:29
I have both vscode and vscodium installed. I am able to resize vscode from the borders and bottom right corner, but when resizing vscodium I can only use bottom right corner. When resizing from boarders with vscodium my mouse cursor freeze at the borders. 

I'm running Windows 11 OS build 22000.652

**Comment by brxken128** [comment] 2022-04-28 16:33
Just tested myself with VSCodium on Windows, it indeed does not resize from:

- Top Border
- Right Border
- Top-Right Corner
- Left Border
- Bottom Border
- Bottom-Left Corner

The only things it is resizable with are the top left corner, and the bottom-right one.

VSC 1.66.2, Windows 11.

I have not tested VSCode yet.

**Comment by VincyZed** [comment] 2022-04-28 19:33
I'm running on the latest version (1.66.2) and can confirm that I also have this issue. Windows 11 22000.613.

**Comment by gdrbyKo1** [comment] 2022-05-05 09:27
Same issue as https://github.com/VSCodium/vscodium/issues/1032
Upstream issue: https://github.com/microsoft/vscode/issues/146060

**Comment by daiyam** [comment] 2022-05-07 15:56
The issue is fixed in `v1.67`.

**Closed by daiyam** 2022-05-07 15:56 UTC
Labels: bug
