### ISSUE TITLE
Can't launch in wayland now.

### ISSUE THREAD

**Issue by red5h4d0w** [VSCodium/vscodium#1035] opened 2022-04-05 19:27 UTC
**Describe the bug**
VSCodium doesn't launch in wayland mode since a week ago.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
0. Use a Wayland DE
1. Open terminal
2. Run codium --enable-features=UseOzonePlatform --ozone-platform=wayland

**Expected behavior**
VSCodium should open.

**Desktop (please complete the following information):**
 - OS: Endeavour OS (Gnome DE mutter-wayland)
 - Architecture x64
 - Version  1.66.0

**Comment by red5h4d0w** [comment] 2022-04-05 19:50
Here is the verbose output with the appimage
Command:
`./VSCodium-1.66.0-1648720116.glibc2.17-x86_64.AppImage --enable-features=UseOzonePlatform --ozone-platform=wayland`
Result:
`[6565:0405/154725.965355:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is 
[6565:0405/154725.991679:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Avertissement : 'enable-features' n'est pas dans la liste des options connues, mais est quand même transféré à Electron/Chromium.
Avertissement : 'ozone-platform' n'est pas dans la liste des options connues, mais est quand même transféré à Electron/Chromium.
[main 2022-04-05T19:47:26.109Z] [File Watcher (node.js)] Request to start watching: /home/ismael/.config/VSCodium/User (excludes: <none>),/home/ismael/.config/VSCodium/User/settings.json (excludes: <none>)
[main 2022-04-05T19:47:26.160Z] Starting VS Code
[main 2022-04-05T19:47:26.160Z] from: /tmp/.mount_VSCodimTWxwW/usr/share/codium/resources/app
[main 2022-04-05T19:47:26.160Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': true,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  logsPath: '/home/ismael/.config/VSCodium/logs/20220405T154726'
}
[main 2022-04-05T19:47:26.162Z] Resolving machine identifier...
[main 2022-04-05T19:47:26.162Z] Resolved machine identifier: a1f2bc4c141ac5ffdb39627904b415188979423382fb99189c059f848dcfc5fa
[main 2022-04-05T19:47:26.163Z] Main->SharedProcess#connect
[main 2022-04-05T19:47:26.165Z] [File Watcher (node.js)] Started watching: '/home/ismael/.config/VSCodium/User'
[main 2022-04-05T19:47:26.168Z] [File Watcher (node.js)] Started watching: '/home/ismael/.config/VSCodium/User/settings.json'
[main 2022-04-05T19:47:26.176Z] StorageMainService: creating global storage
[main 2022-04-05T19:47:26.182Z] lifecycle (main): phase changed (value: 2)
[main 2022-04-05T19:47:26.183Z] windowsManager#open
[main 2022-04-05T19:47:26.183Z] windowsManager#open pathsToOpen [
  {
    backupPath: '/home/ismael/.config/VSCodium/Backups/1649186241087',
    remoteAuthority: undefined
  }
]
[main 2022-04-05T19:47:26.184Z] windowsManager#doOpenEmpty {
  restore: true,
  remoteAuthority: undefined,
  filesToOpen: undefined,
  forceNewWindow: true
}
[main 2022-04-05T19:47:26.185Z] IPC Object URL: Registered new channel vscode:faf5a858-f04b-4ceb-99d1-2186bd342854.
[main 2022-04-05T19:47:26.185Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 0, y: 0, width: 902, height: 752 }
[main 2022-04-05T19:47:26.185Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1128, height: 752 }
[main 2022-04-05T19:47:26.185Z] window#ctor: using window state { mode: 1, x: 0, y: 0, width: 902, height: 752 }
[6513:0405/154726.203201:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
Erreur de segmentation (core dumped)`

**Comment by red5h4d0w** [comment] 2022-04-05 19:52
I also confirmed that this is not a bug in 1.65.2

**Comment by multun** [comment] 2022-04-06 16:32
@red5h4d0w it's an upstream bug: https://github.com/microsoft/vscode/issues/146890
which is caused by an electron bug: https://github.com/electron/electron/pull/33355 (fixed in 17 by https://github.com/electron/electron/pull/33499)

**Comment by Evpok** [comment] 2022-04-07 08:04
@multun The issue you linked is not linked to the Electron bug I think (but **this** issue seems to be!).

**Comment by smasher164** [comment] 2022-04-18 05:21
Also mentioned in this comment in an upstream issue https://github.com/microsoft/vscode/issues/146349#issuecomment-1097824414, this is apparently fixed in vscode insiders, which is using electron 17.4.0.

**Comment by daiyam** [comment] 2022-05-07 15:57
`v1.67` is out. Can you try with this version?

**Comment by paulcarroty** [comment] 2022-05-07 17:41
Sadly, nope - works in XWayland only.

**Comment by sebastian-de** [comment] 2022-05-08 14:59
`codium --enable-features=UseOzonePlatform --ozone-platform=wayland` works again for me. I use KDE Plasma on Fedora 36.

**Comment by paulcarroty** [comment] 2022-05-08 15:02
@sebastian-de without XWayland process?

**Comment by sebastian-de** [comment] 2022-05-08 16:13
Plasma starts XWayland in the background anyway, no matter if an application needs it or not (I don't know if this can be disabled for testing).
But applications under [XWayland have blurry fonts on a HiDPI display](https://github.com/electron/electron/issues/29367), so I can easily see if an application uses XWayland.
v1.66 didn't even start with the ozone options enabled. v1.67 starts and has sharp fonts, so it is on native Wayland.

**Comment by sebastian-de** [comment] 2022-05-08 16:19
If I run codium without options, `xlsclients -l` gives
```
Window 0x1200001:
  Machine:  dosa
  Name:  codium
  Icon Name:  codium
  Command:  codium
  Instance/Class:  codium/Codium
```
If I run it with ozone options, xlsclients doesn't return anything, so codium realy is running on Wayland natively.

**Closed** 2022-05-09 15:15 UTC
Labels: bug

**Comment by zzzsyyy** [comment] 2022-05-10 12:26
Feeling weird but this problem is reproduced on my machine

output of `codium --version`
```
1.67.0
57fd6d0195bb9b9d1b49f6da5db789060795de47
x64
```
and output of `codium --enable-features=UseOzonePlatform --ozone-platform=wayland --verbose`
```
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
[4053:0510/201625.457676:WARNING:wayland_object.cc(94)] Binding to zwp_linux_dmabuf_v1 version 3 but version 4 is available.
[4053:0510/201625.457805:WARNING:wayland_object.cc(94)] Binding to zwp_pointer_gestures_v1 version 1 but version 3 is available.
[4053:0510/201625.457816:WARNING:wayland_object.cc(94)] Binding to wl_output version 2 but version 4 is available.
[4053:0510/201625.458099:WARNING:wayland_drm.cc(96)] Failed to get drm magic
[4053:0510/201625.612078:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[4093:0510/201625.653548:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is
[4093:0510/201625.658698:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2022-05-10T12:16:25.713Z] [File Watcher (node.js)] Request to start watching: /home/zzzsy/.config/VSCodium/User (excludes: <none>, includes: <all>),/home/zzzsy/.config/VSCodium/User/settings.json (excludes: <none>, includes: <all>)
[main 2022-05-10T12:16:25.740Z] Starting VS Code
[main 2022-05-10T12:16:25.740Z] from: /opt/vscodium-bin/resources/app
[main 2022-05-10T12:16:25.740Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': true,
  telemetry: false,
  debugRenderer: false,
  'enable-smoke-test-driver': false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  logsPath: '/home/zzzsy/.config/VSCodium/logs/20220510T201625'
}
[main 2022-05-10T12:16:25.743Z] Resolving machine identifier...
[main 2022-05-10T12:16:25.743Z] Resolved machine identifier: 05ca8174e03cb9b40c840355f03d71328ce2ad59456d201f809011bd9f8f3d7f
[main 2022-05-10T12:16:25.744Z] Main->SharedProcess#connect
[main 2022-05-10T12:16:25.745Z] [File Watcher (node.js)] Started watching: '/home/zzzsy/.config/VSCodium/User'
[main 2022-05-10T12:16:25.748Z] [File Watcher (node.js)] Started watching: '/home/zzzsy/.config/VSCodium/User/settings.json'
[main 2022-05-10T12:16:25.763Z] StorageMainService: creating global storage
[main 2022-05-10T12:16:25.770Z] lifecycle (main): phase changed (value:2)
[main 2022-05-10T12:16:25.771Z] windowsManager#open
[main 2022-05-10T12:16:25.772Z] windowsManager#open pathsToOpen [
  {
    workspace: { id: 'c014c64fa9822620eff01d7b7e952150', uri: [h] },
    type: 2,
    exists: true
  }
]
[main 2022-05-10T12:16:25.773Z] windowsManager#doOpenFolderOrWorkspace {
  folderOrWorkspace: {
    workspace: { id: 'c014c64fa9822620eff01d7b7e952150', uri: [h] },
    type: 2,
    exists: true
  },
  filesToOpen: undefined
}
[main 2022-05-10T12:16:25.774Z] IPC Object URL: Registered new channel vscode:039d4bac-d772-47b4-a243-698cb4c90ef9.
[main 2022-05-10T12:16:25.774Z] window#validateWindowState: validating window state on 1 display(s) { mode: 0, x: 481, y: 202, width: 156, height: 188 }
[main 2022-05-10T12:16:25.774Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1280, height: 800 }
[main 2022-05-10T12:16:25.775Z] window#ctor: using window state { mode:0, x: 481, y: 202, width: 156, height: 188 }
[4053:0510/201625.775586:WARNING:wayland_surface.cc(118)] Server doesn't support zcr_alpha_compositing_v1.
[4053:0510/201625.775615:WARNING:wayland_surface.cc(129)] Server doesn't support overlay_prioritizer.
[4053:0510/201625.775622:WARNING:wayland_surface.cc(139)] Server doesn't support surface_augmenter.
[4053:0510/201625.776232:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
[main 2022-05-10T12:16:25.819Z] window#load: attempt to load window (id: 1)
[main 2022-05-10T12:16:25.828Z] StorageMainService: creating workspace storage (c014c64fa9822620eff01d7b7e952150)
[main 2022-05-10T12:16:25.829Z] windowsManager#open used window count 1(workspacesToOpen: 0, foldersToOpen: 1, emptyToRestore: 0, emptyToOpen:0)
[main 2022-05-10T12:16:25.829Z] lifecycle (main): phase changed (value:3)
[main 2022-05-10T12:16:25.831Z] update#setState idle
[main 2022-05-10T12:16:25.853Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2022-05-10T12:16:25.894Z] ExtensionHostStarterWorker created
[main 2022-05-10T12:16:25.999Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[4053:0510/201626.002269:WARNING:wayland_event_watcher.cc(31)] libwayland: xdg_surface@39: error 3: xdg_surface has never been configured

[4053:0510/201626.002360:ERROR:wayland_event_watcher.cc(301)] Fatal Wayland communication error Broken pipe.
[main 2022-05-10T12:16:26.010Z] IPC Object URL: Removed channel vscode:039d4bac-d772-47b4-a243-698cb4c90ef9.
[main 2022-05-10T12:16:26.011Z] Lifecycle#window.on('closed') - window ID 1
[main 2022-05-10T12:16:26.011Z] Lifecycle#onWillShutdown.fire()
[main 2022-05-10T12:16:26.014Z] storageMainService#onWillShutdown()
[main 2022-05-10T12:16:26.015Z] Lifecycle#app.on(window-all-closed)
[main 2022-05-10T12:16:26.015Z] Lifecycle#app.on(before-quit)
[main 2022-05-10T12:16:26.015Z] Lifecycle#onBeforeShutdown.fire()
[main 2022-05-10T12:16:26.015Z] [WindowsStateHandler] onBeforeShutdown {
  lastActiveWindow: undefined,
  lastPluginDevelopmentHostWindow: {
    workspaceIdentifier: undefined,
    folder: 'file:///home/zzzsy/Documents/Code/ll-kaze',
    backupPath: undefined,
    remoteAuthority: undefined,
    uiState: { mode: 0, x: 0, y: 0, width: 1026, height: 490 }
  },
  openedWindows: []
}
[main 2022-05-10T12:16:26.016Z] Lifecycle#app.on(will-quit)
```

Arch Linux: 5.17.5-zen1-1-zen
WM: sway 1.8
