### ISSUE TITLE
Crash on Linux when attempting to open "File" menu

### ISSUE THREAD

**Issue by Svankle1** [VSCodium/vscodium#2082] opened 2024-11-02 18:50 UTC
(First time writing one of these, so sorry if I've fail to provide good information)
**Describe the bug**
After a recent update, trying to use the File menu/dropdown results in a crash after about a second of the program freezing.

**Please confirm that this problem is VSCodium-specific**
- [X] I temporarily installed Visual Studio Code via the Linux 64 deb package on code.visualstudio.com. The crash does not occur there.
- [X] The crash also does not occur on VSCodium's flatpak option it seems. Only the deb package.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/docs/index.md) and [the Troubleshooting page](https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md) and was unable to find my issue mentioned there.

**To Reproduce**
1. Update VSCodium to 1.95.1.24307
2. Open VSCodium
3. Hover over "File" in top right and click.
4. Encounter crash after 1 or 2 seconds.
Its notable that all the other drop downs such as Edit and Terminal seem to render without issue.
**Expected behavior**
The File dropdown to render and allow options to be selected.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3 MATE Edition
 - Architecture amd64 (I believe)
 - Version 1.95.1.24307
 - App Manager apt / mintUpdate
 - Sandboxed Flatpack and Snap are both enabled, but not being relevant to this bug.

**Additional context**
This bug did not happen on version 1.94.2.24286

**Comment by lichenaut** [comment] 2024-11-02 19:22
This is happening to me too. Reinstalling and clearing cached/local data did not fix it.

**Comment by orangecoloured** [comment] 2024-11-02 19:56
Same here. Fedora 40.

**Comment by lincolnjpg** [comment] 2024-11-02 20:30
It's happening here as well. Debian 12

**Comment by mattaroni** [comment] 2024-11-02 20:50
Also happening here. Using Linux Mint 22 Cinnamon.

**Comment by schwartzenheimer** [comment] 2024-11-02 21:43
Same issue, Manjaro KDE 6.1.5

**Comment by Redsskull** [comment] 2024-11-02 22:13
Linux Mint 21. I actually thought it was my settings or product.json after the update today, but the crash logs show it dumping a core and having issues itself.

**Comment by cocoanaut** [comment] 2024-11-02 23:49
Same issue on Debian 12.7. dmesg shows this error:
```
traps: codium[9145] trap int3 ip:55cf909cc46c sp:7fffa5030a70 error:0 in codium[55cf8ca40000+8972000]
```

**Comment by zero-stacks** [comment] 2024-11-03 00:20
same on fedora 41

**Comment by g5ostXa** [comment] 2024-11-03 00:52
same on arch

**Comment by xgrind** [comment] 2024-11-03 01:21
same on Mageia 9

**Comment by g5ostXa** [comment] 2024-11-03 01:24
same on arch

**Comment by hyprmann** [comment] 2024-11-03 06:00
crash on arch, hyprland too

**Comment by kxxt** [comment] 2024-11-03 09:26
Some Links:

- https://gitlab.archlinux.org/archlinux/packaging/packages/code/-/issues/5
- https://github.com/microsoft/vscode/issues/232873
- https://github.com/riscv-forks/electron/issues/5
- https://github.com/microsoft/vscode/issues/204561

I suspect this issue is fixed in microsoft's distribution of electron but not the upstream ones.

**Comment by daiyam** [comment] 2024-11-03 09:36
@kxxt Thx for the update. So it's not VSCodium specific.

I'm testing/building on my VM, I will try to play around with the Electron version.

**Comment by daiyam** [comment] 2024-11-03 10:43
Here the related issues: #230604 and #232723

Based on the comments in #232723, Visual Studio Code has shipped with a custom Electron with the fix.
And by using the setting `"window.titleBarStyle": "custom"`, it does fix the issue (It stops to use the system menu...)

I've tested it and it's working.
You can do it with `Ctrl+,` then search `titleBarStyle` and select `custom`.

**Comment by zero-stacks** [comment] 2024-11-03 12:30
codium-insiders is working fine and im using it meanwhile

**Comment by daiyam** [comment] 2024-11-03 13:16
@zero-stacks Which version are you using?

**Comment by kyberdrb** [comment] 2024-11-03 13:29
@daiyam 
`code-insiders-bin`: latest version 1.96.0 is working stable.
`vscodium-insiders-bin` : latest version 1.95.0 crashes.
Arch Linux with latest updates up to Nov 3rd.

So I guess 1.96 has the bug fixed. We just need to wait until the VSCode upstream gets merged into VSCodium release branch.

**Comment by xgrind** [comment] 2024-11-03 13:30
> Here the related issues: [microsoft/vscode#230604](https://github.com/microsoft/vscode/issues/230604) and [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723)
> 
> Based on the comments in [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723), Visual Studio Code has shipped with a custom Electron with the fix. And by using the setting `"window.titleBarStyle": "custom"`, it does fix the issue (It stops to use the system menu...)
> 
> I've tested it and it's working. You can do it with `Ctrl+,` then search `titleBarStyle` and select `custom`.

This solution was perfect and even makes the look better. It could come custom by default.

**Comment by kyberdrb** [comment] 2024-11-03 13:44
@xgrind

I can confirm that the setting adjustment has cosmetic effect on VSCode 1.96.0-insiders

![image](https://github.com/user-attachments/assets/5733ae39-1d72-4965-94b8-836658474434)

and fixes the _File_ menu crash for 1.95.0-insiders

![image](https://github.com/user-attachments/assets/3cf648d0-fbc0-4880-8daf-960f5a73fc2e)

![image](https://github.com/user-attachments/assets/06808a24-48bb-4de9-9e8c-7c6a270f7183)

Still an interesting bug. But I like the "custom" menu bar design better. I'm almost glad it broke :)

**Comment by daiyam** [comment] 2024-11-03 14:05
I agree with you that the custom menu is better ;)

> code-insiders-bin: latest version 1.96.0 is working stable.

Yes, `code-insiders-bin` is using the binary from MS (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=code-insiders-bin#n16)

**Comment by imgustavo** [comment] 2024-11-03 21:24
same here since today, using LMDE6

**Comment by jon-nfc** [comment] 2024-11-03 21:55
same issue too. v1.95.1. can confirm setting the title bar to custom does address the issue

**Comment by negativeExponent** [comment] 2024-11-04 00:25
thanks for custom

**Comment by daniel-ambriz** [comment] 2024-11-04 02:02
Same crash issue for me on ZorinOS 17.2

**Comment by fr0st-iwnl** [comment] 2024-11-04 05:01
> I've tested it and it's working. You can do it with `Ctrl+,` then search `titleBarStyle` and select `custom`.

I tried it out too and it works setting **titleBarStyle** to custom using `Ctrl+,` fixed the issue for me. Still the native title bar crashes for me but honestly i’m liking the custom one better anyway. Thanks for the tip!

**Comment by mtovmassian** [comment] 2024-11-04 08:50
Ubuntu 22.04 same behavior and using the[ custom Title Bar Style](https://github.com/VSCodium/vscodium/issues/2082#issuecomment-2453379818) is good workaround.

**Comment by sjsepan3** [comment] 2024-11-04 12:19
Linux Mint 22 Wilma
Codium 1.95.1

The titlebar setting `"window.titleBarStyle": "custom"` works, but I'm looking forward to 1.96 to get my titlebar / borders back...

**Comment by varunbit** [comment] 2024-11-04 15:02
It is happening to me to on Linux Mint 21.1 Cinnamon after updating Codium to version 1.95.1

**Comment by SoftwareType** [comment] 2024-11-04 22:25
I've just tried the insiders version 1.96.0.24309-1, but in contrary of some cases here, I still got the error

**Comment by KapiKane** [comment] 2024-11-05 04:11
Same here for Insiders edition on Endevour OS idk wut else is needed but uhm:
Version: 1.95.0-insider Release: 24303
Commit: 2bae731aa46e62b1f828e4edf4fa3db621f83b2e Date: 2024-10-29T09:14:53.844Z
Electron: 32.2.1 ElectronBuildId: undefined
Chromium: 128.0.6613.186 Node.js: 20.18.0
V8: 12.8.374.38-electron.0 OS: Linux x64 6.11.3-arch1-1

**Comment by ValentinMATHIEU** [comment] 2024-11-05 09:08
> Crash on arch, hyprland too, v1.95.1.24307-1
> 
> I've made a note on to downgrade the package if anyone wants to downgrade it.
> 
> ```shell
> # Downgrade AUR packages
> 
> # Method 1: CLI
> 
> # Clone the AUR repository
> # git clone https://aur.archlinux.org/aur_package.git
> ...
> 
> 
> 
> # Method 2: GUI
> 
> # Visit the AUR page
> https://aur.archlinux.org/
> 
> # Find the AUR package
> # Search the AUR package name using the "Package Search" box on the right side
> https://aur.archlinux.org/packages/vscodium-bin
> 
> # View the changelog of the AUR package
> # Click "View Changes" on "Package Actions" box located on the right side
> ....
> ```

Now I have the method and i will abuse it !

Perfect ! Thank you !

**Comment by Mr-Anmar** [comment] 2024-11-05 14:56
I just updated the app to latest version using SOFTWARE-GNOME under Fedora 41. After installing the update once start the app and press File menu the app freeze for couple of seconds and shouts down. other menus works fine. I did face the same issue when i installed VSCodium through RPM couple of days back, then i remove it and installed it through Software-GNOME

Version: 1.95.1
Release: 24307
Commit: 8798508b6fcf62248291cdf7a7e870bd84f7257d
Date: 2024-11-02T15:11:51.261Z
Electron: 32.2.1
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.11.5-300.fc41.x86_64

**Comment by maxkratz** [comment] 2024-11-05 15:53
I can also confirm this bug on Pop!_OS 22.04 x64.

**Comment by zero-stacks** [comment] 2024-11-05 16:55
> I just updated the app to latest version using SOFTWARE-GNOME under Fedora 41. After installing the update once start the app and press File menu the app freeze for couple of seconds and shouts down. other menus works fine. I did face the same issue when i installed VSCodium through RPM couple of days back, then i remove it and installed it through Software-GNOME.
> 
> **Notes**
> 
>     1. When i go to Setting-GNOME and click apps and select VSCodium > App Details it send me back to Software-GNOME and shows me the VSCodium-Insiders page?
> 
>     2. in Report it says app killed by SIGTRAP
> 
> 
> Im kind of new to Linux world also to VSCodium i hope this information helps
> 
> **ANy Idea how to revert back to previuse version?**
> 
> Version: 1.95.1 Release: 24307 Commit: 8798508b6fcf62248291cdf7a7e870bd84f7257d Date: 2024-11-02T15:11:51.261Z Electron: 32.2.1 ElectronBuildId: undefined Chromium: 128.0.6613.186 Node.js: 20.18.0 V8: 12.8.374.38-electron.0 OS: Linux x64 6.11.5-300.fc41.x86_64

To fix it you can use the solution as mentioned above: 
![image](https://github.com/user-attachments/assets/3ce95cec-3d57-4381-b288-f9b7d14766e3)
change the title bar style to "custom", this will work as a temporary solution and honestly the custom bar looks way better...

**Comment by svgaming234** [comment] 2024-11-05 20:53
Can confirm this issue on both Arch installed from the AUR (`vscodium-bin`) and a fresh VM install of Linux Mint 22 (.deb file from the latest release)

**Comment by ArashiJF** [comment] 2024-11-05 23:27
glad I found this thread, I updated last week and now is when I tried to open something in the editor.
The custom setting works as a workaround, deb version.

Very weird because all the other tabs worked, but file is the one that failed, what a weird issue

**Comment by BlastBlaster17** [comment] 2024-11-06 02:01
I second this issue. Or should I say, I _thirty_-second it, because we all have this problem. I seem to have it on the noble version of Ubuntu.

**Comment by JThomasKern** [comment] 2024-11-06 02:20
oh oh me too! Debian GNU 12 (bookworm) x86_64  with Gnome.

**Comment by Xmetalfanx** [comment] 2024-11-06 04:24
Linux Mint 22 Cinnamon here ... decided to role back to 1.94.x for now .. tried doing the fix on 1.95.x but i was getting nowhere

**Comment by high1** [comment] 2024-11-06 08:54
The second workaround can be found here - https://github.com/microsoft/vscode/issues/232723 - update the shortcut for New File option in the menu not to include `Super` accelerator in it - it's Ctrl+Alt+Super+N by default. Ctrl+K followed by Ctlr+S to open shortcuts config.

**Comment by LeSasse** [comment] 2024-11-06 09:52
> codium-insiders is working fine and im using it meanwhile

using `codium-insiders` and for me it does also not work, same as `vscodium` and `vscodium-bin`
with `Kernel: 6.6.54-2-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 14.2.1` and KDE plasma

**Comment by daiyam** [comment] 2024-11-06 10:43
@LeSasse Here are the steps for a fix:
- https://github.com/electron/electron/pull/44341 needs to be backported to Electron 32 (which MS has already done for their internal build)
- Electron releases a new version of the 32 with the fix
- VSCodium uses the newer Electron 32

**Comment by xgorex** [comment] 2024-11-06 15:06
> > Here the related issues: [microsoft/vscode#230604](https://github.com/microsoft/vscode/issues/230604) and [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723)
> > Based on the comments in [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723), Visual Studio Code has shipped with a custom Electron with the fix. And by using the setting `"window.titleBarStyle": "custom"`, it does fix the issue (It stops to use the system menu...)
> > I've tested it and it's working. You can do it with `Ctrl+,` then search `titleBarStyle` and select `custom`.
> 
> This solution was perfect and even makes the look better. It could come custom by default.

This WA works well on Debian 12. THX.

**Comment by RobertPHeller** [comment] 2024-11-06 15:59
It also crashes under Debian 12 on a RPi 5 (ARM64).  Version 1.95.1.24307 from Paul Carroty repo.

**Comment by C0fyC0de** [comment] 2024-11-06 20:25
same

**Comment by Liga86** [comment] 2024-11-06 21:26
same on Fedora 41 gnome

**Comment by Liga86** [comment] 2024-11-06 21:33
> > I just updated the app to latest version using SOFTWARE-GNOME under Fedora 41. After installing the update once start the app and press File menu the app freeze for couple of seconds and shouts down. other menus works fine. I did face the same issue when i installed VSCodium through RPM couple of days back, then i remove it and installed it through Software-GNOME.
> > **Notes**
> > ```
> > 1. When i go to Setting-GNOME and click apps and select VSCodium > App Details it send me back to Software-GNOME and shows me the VSCodium-Insiders page?
> > 
> > 2. in Report it says app killed by SIGTRAP
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Im kind of new to Linux world also to VSCodium i hope this information helps
> > **ANy Idea how to revert back to previuse version?**
> > Version: 1.95.1 Release: 24307 Commit: 8798508b6fcf62248291cdf7a7e870bd84f7257d Date: 2024-11-02T15:11:51.261Z Electron: 32.2.1 ElectronBuildId: undefined Chromium: 128.0.6613.186 Node.js: 20.18.0 V8: 12.8.374.38-electron.0 OS: Linux x64 6.11.5-300.fc41.x86_64
> 
> To fix it you can use the solution as mentioned above: ![image](https://private-user-images.githubusercontent.com/124620338/383240006-3ce95cec-3d57-4381-b288-f9b7d14766e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Mjg2MTAsIm5iZiI6MTczMDkyODMxMCwicGF0aCI6Ii8xMjQ2MjAzMzgvMzgzMjQwMDA2LTNjZTk1Y2VjLTNkNTctNDM4MS1iMjg4LWY5YjdkMTQ3NjZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMTI1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2Y3NmEyYzhhYWZiMDhjZWY2MWFlYzNjYmVlZWNhZjgwYjU4YWU4MWQxNzNhNWM4NjNhZjQyMmVkOWRlMTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3hzTvyyEc0ga3ZqNSAX4Z04tfeIfNkOYGWRncNtI0ko) change the title bar style to "custom", this will work as a temporary solution and honestly the custom bar looks way better...

It work on Fedora

**Comment by JeffofBread** [comment] 2024-11-07 03:31
Same issue, Fedora 39, VSCodium v1.95.1

**Comment by Burhanverse** [comment] 2024-11-07 09:58
> > Here the related issues: [microsoft/vscode#230604](https://github.com/microsoft/vscode/issues/230604) and [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723)
> > Based on the comments in [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723), Visual Studio Code has shipped with a custom Electron with the fix. And by using the setting `"window.titleBarStyle": "custom"`, it does fix the issue (It stops to use the system menu...)
> > I've tested it and it's working. You can do it with `Ctrl+,` then search `titleBarStyle` and select `custom`.
> 
> Damn thanks man switching to custom works fine now and the title bar looks so cool. I'm sure everyone will love it if it's set by default. Weird bug but cool fix lmao

**Comment by andros0689** [comment] 2024-11-07 16:54
> Here the related issues: [microsoft/vscode#230604](https://github.com/microsoft/vscode/issues/230604) and [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723)
> 
> Based on the comments in [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723), Visual Studio Code has shipped with a custom Electron with the fix. And by using the setting `"window.titleBarStyle": "custom"`, it does fix the issue (It stops to use the system menu...)
> 
> I've tested it and it's working. You can do it with `Ctrl+,` then search `titleBarStyle` and select `custom`.

Hello, thanks @daiyam it works for me in Fedora 41 (kernel version 6.11.5-300.fc41.x86_64)

**Comment by archiron** [comment] 2024-11-08 09:12
same issue for me. tried with snap and standalone app. Ubuntu 24.10

**Comment by bardicreels** [comment] 2024-11-08 11:49
same here, installed on debian and also the appimage.

**Comment by ctcl-bregis** [comment] 2024-11-08 13:51
Can confirm on Linux Mint Cinnamon 23
uname -a
```
Linux CTCL-WBPC1 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
codium -v
```
1.95.1
8798508b6fcf62248291cdf7a7e870bd84f7257d
x64
```
Installed via apt using repository specified on vscodium.com

**Comment by hutandyk6** [comment] 2024-11-08 15:46
try to make have potentional futher

**Comment by zero-stacks** [comment] 2024-11-08 16:49
> > codium-insiders is working fine and im using it meanwhile
> 
> using `codium-insiders` and for me it does also not work, same as `vscodium` and `vscodium-bin` with `Kernel: 6.6.54-2-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 14.2.1` and KDE plasma

Sorry at the time I had an older version of `codium-insiders`, because the GitHub insiders API request was rejected few times for the rpm repository I use to install it, and it could not get updates (unknown reason)

If u want to fix it, use [this solution](https://github.com/VSCodium/vscodium/issues/2082#issuecomment-2457699983) that other ppl and I mentioned above.

**Comment by LazyKarlson** [comment] 2024-11-09 13:50
Still crash after update
`Version: 1.95.2
Release: 24313
Commit: 7656a0bea17ba6cf301721572e10c9035bb378e6
Date: 2024-11-08T18:21:12.757Z
Electron: 32.2.1
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.5.0-44-generic`

console log
`[80919:1109/164743.845796:ERROR:browser_main_loop.cc(283)] GLib-GObject: ../../../gobject/gsignal.c:2777: instance '0x25fc01646690' has no handler with id '1869'
[80919:1109/164748.521716:FATAL:check.cc(376)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[1]    80919 trace trap (core dumped)  /usr/share/codium/codium`

**Comment by sid-the-sloth** [comment] 2024-11-09 18:14
> Here the related issues: [microsoft/vscode#230604](https://github.com/microsoft/vscode/issues/230604) and [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723)
> 
> Based on the comments in [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723), Visual Studio Code has shipped with a custom Electron with the fix. And by using the setting `"window.titleBarStyle": "custom"`, it does fix the issue (It stops to use the system menu...)
> 
> I've tested it and it's working. You can do it with `Ctrl+,` then search `titleBarStyle` and select `custom`.

Thank you for this fix. Now it works fine.

**Comment by zero-stacks** [comment] 2024-11-10 00:10
@daiyam you should make the custom bar on by default on codium(if you can) or at least think about it haha

**Comment by Cronus23** [comment] 2024-11-10 06:41
Same issue: POP_OS + cinnamon

**Comment by ahoehne** [comment] 2024-11-10 06:53
> Here the related issues: [microsoft/vscode#230604](https://github.com/microsoft/vscode/issues/230604) and [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723)
> 
> Based on the comments in [microsoft/vscode#232723](https://github.com/microsoft/vscode/issues/232723), Visual Studio Code has shipped with a custom Electron with the fix. And by using the setting `"window.titleBarStyle": "custom"`, it does fix the issue (It stops to use the system menu...)
> 
> I've tested it and it's working. You can do it with `Ctrl+,` then search `titleBarStyle` and select `custom`.

Thanks a lot, that worked.
Settings where mapped differently (`Ctrl,` instead of `Ctrl+` - not sure if i remapped that myself ;) ). Otherwise there's an Settings Icon in the bottom-left corner that works.

**Comment by Cronus23** [comment] 2024-11-10 06:58
That's a workaround, seems to work!

**Comment by TejaCEO** [comment] 2024-11-10 13:18
facing this issue in bookworm too unable to open file menu it results in crash

**Comment by daiyam** [comment] 2024-11-10 13:28
@ahoehne `Ctrl+,` means `Ctrl` and `,` at the same time 😉 It's a convention for shortcuts on Windows and Linux.

**Comment by lee-b** [comment] 2024-11-10 15:01
Fresh install of 1.95.2 on Linux Mint: Can confirm the "custom" titleBarStyle doesn't have the same crashing issue, as the native/default config, but this is a workaround, not a fix, of course.

**Comment by melroy89** [comment] 2024-11-10 20:36
Same

**Comment by the7erm** [comment] 2024-11-10 20:59
```$ codium  -v
1.95.2
7656a0bea17ba6cf301721572e10c9035bb378e6
x64
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"
```

Alt+f also causes the bug to occur.   This worked for me: https://github.com/microsoft/vscode/issues/230604   Thanks for the help.

**Comment by borodinalive** [comment] 2024-11-11 07:29
same issue
1.95.2.24313
Ubuntu 20.04

1.94.2.24286 is OK

**Comment by Spartan322** [comment] 2024-11-11 11:40
Version: 1.95.2
Release: 24313
Commit: 7656a0bea17ba6cf301721572e10c9035bb378e6
Date: 2024-11-08T18:21:12.757Z
Electron: 32.2.1
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.11.6-zen1-1-zen

Can confirm the same issue, setting `window.titleBarStyle` as `custom` does stop the crash however I despise clientside decorations.

**Comment by viniciusmelocodes** [comment] 2024-11-11 13:59
@Spartan322 working fine.

**Comment by valgameiroconsulting** [comment] 2024-11-11 16:45
I'm having the same problem on Ubuntu 22.04. I can use Ctrl-K-O fine, but when I click the File menu with the mouse, it crashes Codium. Had to downgrade to a 1.94 version.

**Comment by Plumeros** [comment] 2024-11-11 19:00
Same issue here on latest Debian 12. Kudos in advance for the one fixing the issue. :-)

**Comment by o7pacifica** [comment] 2024-11-11 20:20
Hey, same issue on Fedora 41. Thanks in advance to the people working on a fix!

**Comment by LobotomyTH** [comment] 2024-11-11 21:35
Same issue, Linux Mint 22 Wilma, all devices affected.

**Comment by etim808** [comment] 2024-11-12 07:52
same here on Debian 12

**Comment by dsommers** [comment] 2024-11-12 11:09
I've went through all the reports in this issue and summarized the distributions with these issues.  I think it's safe to assume this is a very broad issue hitting basically everyone.  For the sanity of the maintainer, maybe we can just report distributions not listed below from now?

* Arch (rolling releases)
* Debian: 10, 11, 12
* Endeavour (no versions mentioned)
* Fedora: 39, 40, 41
* Linux Mint: 21, 22
* Linux Mint Debian Ed: 6
* Mageia: 9
* Manjaro KDE: 6.1.5
* Pop!_OS: 22.04
* Red Hat Enterprise Linux: 8.10
* Ubuntu: 20.04, 22.04, 24.10
* ZorinOS: 17.2

I hope I've not missed anyone.  If it's a distro version missing, that's probably not as important any more - as this issue seems not to be tied to distro versions.  And most likely, any distro type will also be hit by this issue.

As several has mentioned, there is a workaround: Go to settings (keyboard shortcut `CTRL`+`,`), search up the `window.titleBarStyle` setting and chose `custom`.

And to repeat what we also know, this is not an issue in the VSCodium build itself but an issue inherited from the upstream VSCode project: https://github.com/microsoft/vscode/issues/230604 https://github.com/microsoft/vscode/issues/232723

**Comment by daiyam** [comment] 2024-11-12 11:28
Yes, I believe it's affecting all Linux distros.

The bug is in Electron (https://github.com/electron/electron/pull/44341).
It has already been backported for the internal build of Visual Studio Code.

**Comment by JesseSteele** [comment] 2024-11-12 21:35
Manjaro GNOME too, FWIW. Patiently waiting.

**Comment by nPHYN1T3** [comment] 2024-11-14 13:18
Yup same here on Arch.

**Comment by celenityy** [comment] 2024-11-15 04:30
Glad to hear I'm not the only one with this issue... Fedora 41. I just assumed it was something wrong with my set-up :P.

**Comment by importcjj** [comment] 2024-11-15 05:47
In arch, setting `window.titleBarStyle` to `custom` fixes my crash

**Comment by mahula** [comment] 2024-11-15 08:54
> In arch, setting `window.titleBarStyle` to `custom` fixes my crash

Exactly.
As written above in https://github.com/VSCodium/vscodium/issues/2082#issuecomment-2453379818, this is a worthy fix.

**Comment by nPHYN1T3** [comment] 2024-11-15 08:57
It works but now you're stuck with a piece of UI you had hidden for a reason, or at least I did.

**Comment by MelihDarcanxyz** [comment] 2024-11-15 18:59
I can reproduce this error both on Pop!OS and Arch Linux, on different machines.

**Comment by hafiz-muhammad** [comment] 2024-11-15 23:05
Happening to me also on Fedora 41.

**Comment by distinctjuggle** [comment] 2024-11-15 23:10
hey guys guess what - it's  happening to everyone on everything.  

Neat how this was [troubleshooted](https://github.com/VSCodium/vscodium/issues/2082#issuecomment-2453357552) and then [solved via workaround](https://github.com/VSCodium/vscodium/issues/2082#issuecomment-2453379818) a while ago, huh?  No need to keep posting about it with irrelevant information that helps no one and only obfuscates the real answers.

**Comment by daiyam** [comment] 2024-11-15 23:44
Good news, it has been backported (https://github.com/electron/electron/pull/44623) and [Electron v32.2.5](https://github.com/electron/electron/releases/tag/v32.2.5) has been released.
I'm making the updates and will release a new version soon.

**Comment by daiyam** [comment] 2024-11-16 01:53
[v1.95.3.24321](https://github.com/VSCodium/vscodium/releases/tag/1.95.3.24321) is fixing the issue.

**Comment by nPHYN1T3** [comment] 2024-11-16 17:19
Working on Arch - also thanks.

**Closed** 2024-11-17 09:27 UTC
Labels: bug

**Comment by Plumeros** [comment] 2024-11-18 06:10
thanks a lot :-)

**Comment by archiron** [comment] 2024-11-18 09:00
Version 1.95.3 working on my Ubuntu 24.10.
Many thanks !

**Comment by peaceAndHodl** [comment] 2024-11-25 12:26
ubuntu / gnome

the file menu doesn't crash the app anymore

HOWEVER it is still not possible to resize windows with mouse from window borders (full screen / minimize buttons are fine).

**Comment by teamkill3d** [comment] 2025-02-17 22:54
on KDE plasma and version 1.97.2, the problem persists
