### ISSUE TITLE
Whenever i try to select File bar from leftcorner VScodium crashes

### ISSUE THREAD

**Issue by sukirti2004** [VSCodium/vscodium#2106] opened 2024-11-12 01:30 UTC
Type: <b>Bug</b>

Just opening File bar

VSCodium version: VSCodium 1.95.2 (7656a0bea17ba6cf301721572e10c9035bb378e6, 2024-11-08T18:21:12.757Z)
OS version: Linux x64 6.8.0-48-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1999)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|7, 3, 1|
|Memory (System)|7.61GB (5.30GB free)|
|Process Argv|--extensions-dir /home/priyanshu/.var/app/com.vscodium.codium/data/codium/extensions --ozone-platform=x11|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-vibrancy-continued|ill|1.1.41
material-icon-theme|PKi|5.13.0

</details>

**Comment by Levalicious** [comment] 2024-11-12 02:55
Currently experiencing the same issue. 

VSCodium 1.95.2 (7656a0bea17ba6cf301721572e10c9035bb378e6, 2024-11-08T18:21:12.757Z)
Linux x64 6.2.0-39-generic

<details> 
<summary>System Info</summary>

|         Item        |                                                                                                                                                                                                             Value                                                                                                                                                                                                            |
|:-------------------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| CPUs                | Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 4204)                                                                                                                                                                                                                                                                                                                                                                        |
| GPU Status          | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_graphite: disabled_off video_decode: enabled video_encode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off webnn: disabled_off |
| Load (avg)          | 1, 2, 2                                                                                                                                                                                                                                                                                                                                                                                                                      |
| Memory (System)     | 62.61GB (54.38GB free                                                                                                                                                                                                                                                                                                                                                                                                        |
| Process Argv        |                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Screen Reader       | no                                                                                                                                                                                                                                                                                                                                                                                                                           |
| VM                  | 0%                                                                                                                                                                                                                                                                                                                                                                                                                           |
| DESKTOP_SESSION     | ubuntu                                                                                                                                                                                                                                                                                                                                                                                                                       |
| XDG_CURRENT_DESKTOP | ubuntu:GNOME                                                                                                                                                                                                                                                                                                                                                                                                                 |
| XDG_SESSION_DESKTOP | ubuntu                                                                                                                                                                                                                                                                                                                                                                                                                       |
| XDG_SESSION_TYPE    | x11                                                                                                                                                                                                                                                                                                                                                                                                                          |

</details>

I've already verified the bug still occurs when running codium with `--disable-extensions`.

(P.S. is there a nicer way to collect this info if I'm not filing the bug report myself? the bug report winow shows this info, but doesn't let me copy paste it so I typed this over manually).

**Comment by daiyam** [comment] 2024-11-12 08:45
Yes, duplicate of #2082

**Closed by daiyam** 2024-11-12 08:45 UTC
